app/src/marketplace/components/ProductTile/index.jsx
app/src/marketplace/components/ProductTile/productTile.pcss

[PLATFORM-218] Tile loading skeletons not showing properly

---

.travis.yml
app/.storybook/config.js
app/package-lock.json
app/package.json
app/travis_scripts/visual-tests.sh

I've set up [Chromatic](https://www.chromaticqa.com) for this repo. It takes visual snapshots of the state of our storybook and diffs against previous versions.
If you want to try it out, log in with github: 
https://www.chromaticqa.com/library?appId=5bf8ea538165920024d322ff
I've done two builds, Build 1 is on the current `development` branch, Build 2 is after I changed  `ProductTile`'s `text-align`.
To make a new build, check out this branch, run `npm ci` then `npm run chromatic` and it will bake a new build. Change something that would appear in storybook and re-run `npm run chromatic`. It should then detect your change and flag it for review 👍 
Ideally, `npm run chromatic` would run in CI and the PRs would need to be approved before merge and it appears possible to set up this exact …

Try Chromatic

---

app/src/shared/components/Dropdown/DropdownItem/dropdownItem.pcss
app/src/shared/components/Dropdown/DropdownItem/index.jsx
app/src/shared/components/Dropdown/dropdown.pcss
app/src/shared/components/Dropdown/index.jsx
app/src/shared/components/Search/index.jsx
app/src/shared/components/SvgIcon/index.jsx
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/flowtype/common-types.js
app/src/userpages/i18n/en.po
app/src/userpages/modules/canvas/actions.js
app/stories/shared.stories.jsx

Added new `Dropdown` component which handles state changes so it's much easier to use.
Also added needed filters for Canvas listing using this component.

[PLATFORM-216] Add Dropdown component for filters

---

app/src/userpages/components/Avatar/AvatarUpload/avatarUpload.pcss
app/src/userpages/components/Avatar/AvatarUpload/index.jsx
app/src/userpages/components/Avatar/NameAndEmail/index.jsx
app/src/userpages/components/Avatar/NameAndEmail/nameAndEmail.pcss
app/src/userpages/components/Avatar/avatar.pcss
app/src/userpages/components/Avatar/index.jsx
app/src/userpages/components/Header/header.pcss
app/src/userpages/components/Header/index.jsx
app/src/userpages/components/ProfilePage/ProfileSettings/index.jsx
app/src/userpages/components/ProfilePage/ProfileSettings/profileSettings.pcss
app/src/userpages/i18n/en.po
app/stories/userpages.stories.jsx

Adding this `Avatar` component here even though the drop state design is not done (https://share.goabstract.com/247a4b7d-7d25-4307-b8df-4e9673b5cada). The same component is used in the user page header and the profile setting and controlled with an `editable` flag. Also the upload is not hooked up anywhere yet because the backend doesn't support it.

[PLATFORM-225] Avatar component

---

app/src/shared/flowtype/stream-types.js
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/flowtype/states/stream-state.js
app/src/userpages/i18n/en.po
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/modules/userPageStreams/services.js
app/src/userpages/tests/modules/userPagesStreams/reducer.test.js
app/src/userpages/utils/constants.js

Also refactored usage of filters specified in constants.

[PLATFORM-261] Add search and filter support for stream listing

---

app/package-lock.json
app/package.json
app/src/marketplace/components/Layout/layout.pcss
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/TOCPage/TOCSection/index.jsx
app/src/userpages/components/TOCPage/TOCSection/tocSection.pcss
app/src/userpages/components/TOCPage/index.jsx
app/src/userpages/components/TOCPage/tocPage.pcss

Made TOCPage navigation sticky with css. I had to remove `overflow: hidden` from `Layout` because sticky will not not work if parents have overflow attribute. Could not see any visual changes after removing it should be ok.
Also added `react-scrollable-anchor` to enable smooth transitions when clicking anchor links. It also listens to scroll events so the anchor in the url will be updated while scrolling.

[PLATFORM-227] Make TOCPage navigation sticky

---

app/src/links.js
app/src/routes/definitions.json
app/src/userpages/components/StreamPage/Show/InfoView/index.jsx
app/src/userpages/components/StreamPage/Show/InfoView/infoView.pcss
app/src/userpages/components/StreamPage/Show/index.jsx
app/src/userpages/components/StreamPage/Show/streamShowView.pcss
app/src/userpages/components/StreamPage/constants.js
app/src/userpages/components/TOCPage/index.jsx
app/src/userpages/flowtype/states/stream-state.js
app/src/userpages/i18n/en.po
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/tests/modules/userPagesStreams/reducer.test.js

Add support for creating a new or updating an existing stream and editing 'Details' section.

[PLATFORM-278] Stream editor: Details

---

app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/modules/transactionHistory/actions.js

Transaction list wasn't working well, it refreshed itself every time the list has loaded. Also changed fetching the product name from the contract.

[PLATFORM-307] Fix transaction list, get products from contract

---

app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/components/Ports.pcss

Adds ability to rename ports by double-clicking on them.

[PLATFORM-354] Rename port

---

app/src/editor/canvas/components/PortDragger.jsx
app/src/editor/canvas/state.js

Fixes issue where trying to connect incompatible ports would crash the UI.

Noop when trying to connect incompatible ports.

---

app/src/docs/components/ApiPage/Content.mdx
app/src/docs/components/ApiPage/codeSnippets.js
app/src/docs/components/ApiPage/index.jsx
app/src/docs/components/DocsLayout/Navigation/navLinks.js
app/src/docs/components/DocsLayout/docsLayout.pcss

Only needs a quick glance.
Content is largely pulled together from different sources and will probably be reviewed at a later date once all the docs are ready.
Contains some minor intentional edits of the other docs pages.

[PLATFORM-314] API Page Content

---

app/package-lock.json
app/package.json
app/src/editor/dashboard/services.js
app/src/editor/shared/components/Client.jsx
app/src/editor/shared/services.js
app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx
app/src/userpages/components/StreamrClientProvider/index.jsx
app/src/userpages/components/WebComponents/StreamrWidget/index.jsx
app/src/userpages/flowtype/streamr-client-types.js

Updates streamr-client to 1.0.0.

[PLATFORM-328] Update streamr-client to 1.0.0

---

app/src/editor/canvas/state.js
app/src/editor/canvas/tests/mocks.js
app/src/editor/canvas/tests/variadic.test.js

Adds support for variadic outputs e.g. `GetMultiFromMap`.

[PLATFORM-231] Variadic outputs

---

app/src/editor/canvas/components/Cables.jsx
app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/mocks.js
app/src/editor/canvas/tests/state.test.js

Updates port connections on canvas update.

[PLATFORM-395] Update port connections when updating canvas

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/editor/shared/tests/ModuleSearch.test.jsx
app/src/userpages/flowtype/common-types.js

Streams can now be searched in the module search dialog.
Does not support displaying categories yet. Created a new task for it: https://streamr.atlassian.net/browse/PLATFORM-432.

[PLATFORM-333] Add stream search support for ModuleSearch

---

app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/components/Ports.pcss
app/src/shared/components/ContextMenu/ContextMenuItem/contextMenuItem.pcss
app/src/shared/components/ContextMenu/ContextMenuItem/index.jsx
app/src/shared/components/ContextMenu/contextMenu.pcss
app/src/shared/components/ContextMenu/index.jsx
app/stories/shared.stories.jsx

Adds right click context menu for ports. You can disconnect all connections from the port or toggle the export on/off.

[PLATFORM-430] Right-click context menu for ports

---

app/src/userpages/components/ProfilePage/index.jsx

Test to help the Staging environment update

---

.travis.yml

* Allow Platform Build Staging to run when not a pull request to deploy
* Allow development branch to be deployed into Lisboa environment

fix: Deployment in stg and lx:

---

.travis.yml

* The private environment should contain the latest marketplace to test

fix: Lx deployment:

---

app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx
app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/streamLivePreview.pcss
app/src/userpages/components/StreamPage/Show/PreviewView/index.jsx
app/src/userpages/components/StreamPage/Show/PreviewView/previewView.pcss
app/src/userpages/components/StreamPage/Show/index.jsx

Add getKeys to Stream Page, fix show/hide of StreamPreview when no data available, improved styling of the mobile stream preview

[PLATFORM-403-Addendum] Minor Stream Page fixes

---

.travis.yml

* Only deploy stable production version to Lisboa

fix: Lisboa deployment rules:

---

.codedeploy/.appspec.yml
.codedeploy/before_install.sh
.codedeploy/start_server.sh
.codedeploy/stop_server.sh
.travis.yml
app/travis_scripts/build-app-stg.sh

* Add codedeploy files
* Add building tar to travis

chore: DEVOPS-69 - Setup Codeploy for marketplace Staging:

---

.travis.yml

* Add to deploy on development branch

fix: Staging codedeploy:

---

app/.flowconfig
app/package-lock.json
app/package.json
app/src/marketplace/components/ActionBar/index.jsx
app/src/marketplace/components/Nav/index.jsx
app/src/marketplace/containers/EditProductPage/index.jsx
app/src/marketplace/containers/GlobalInfoWatcher/index.jsx
app/src/shared/components/FileUpload/index.jsx
app/src/shared/components/ModalDialog/index.jsx
app/src/shared/components/Nav/NavDivider/index.jsx
app/src/shared/components/Nav/NavDropdown/index.jsx
app/src/shared/components/Notifications/index.jsx
app/src/shared/components/Search/index.jsx
app/src/shared/components/WithCalendar/index.jsx
app/src/shared/contexts/Modal/index.js
app/src/shared/flowtype/common-types.js
app/src/shared/utils/withErrorBoundary.jsx
app/src/userpages/components/Avatar/CropAvatarDialog/index.jsx
app/src/userpages/components/StreamrClientProvider/index.jsx
app/src/userpages/components/WebComponents/StreamrChart/index.jsx
app/src/userpages/components/WebComponents/StreamrHeatmap/index.jsx
app/src/userpages/components/WebComponents/StreamrMap/index.jsx
app/src/userpages/components/WebComponents/StreamrTable/index.jsx

I went from `0.75.0` all the way to the most recent `0.96.0`. Did a bunch of stops down the road to make the migration self-explanatory. Each commit is a version that required some doing to get `No errors!`.
Hope it's clear and you guys like it. Cheers!

Updated flow-bin to the latest version (to date)

---

app/package-lock.json
app/package.json
app/src/marketplace/components/Footer/index.jsx
app/src/shared/components/Footer/footer.pcss
app/src/shared/components/Footer/index.jsx

Footer is static. Scrolling doesn't affect its position. Related changed:
- removed dead styling
- uninstalled `react-in-viewport` (unused)
🔥

[PLATFORM-427] No scroll-to-reveal behaviour for the footer

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/canvas/state.js
app/src/editor/shared/tests/ModuleSearch.test.jsx

Adds support for showing module category tree in the search. Categories can be toggled to show modules under it.

[PLATFORM-432] Add module search categories

---

app/src/docs/components/DocsLayout/Navigation/navigation.pcss
app/src/docs/components/DocsLayout/docsLayout.pcss
app/src/docs/components/IntroductionPage/introduction.pcss
app/src/docs/components/PageTurner/pageTurner.pcss
app/src/docs/components/Panel/panel.pcss
app/src/docs/components/Warning/warning.pcss
app/src/marketplace/components/ProductPageEditor/ProductDetailsEditor/productDetailsEditor.pcss
app/src/marketplace/styles/pcss/buttons.pcss
app/src/marketplace/styles/pcss/layout.pcss
app/src/shared/assets/stylesheets/buttons.pcss
app/src/shared/assets/stylesheets/variables.css
app/src/shared/components/Calendar/calendar.pcss
app/src/shared/components/DropdownActions/dropdownActions.pcss
app/src/shared/components/Meatball/meatball.pcss
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/Show/HistoryView/historyView.pcss
app/src/userpages/components/TOCPage/tocPage.pcss

Primary userpages buttons and renaming the streamr blue var.

[PLATFORM-479] Button styles

---

app/package-lock.json
app/package.json
app/src/editor/canvas/components/Ports.jsx
app/src/editor/shared/components/ColorPicker.jsx
app/src/editor/shared/components/ColorPicker.pcss

Added basic color picker using `react-color`. It doesn't match the designs 100% but it's pretty close.

[PLATFORM-409] Color picker component

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss

Added minimize feature and draggability for the module search. Also updated icons.
We are still missing clear icon for the input and also drag & drop module insertion. I thought we need to prioritise to get things done and we can live without these in the beta. I created following tasks for later:
https://streamr.atlassian.net/browse/PLATFORM-483
https://streamr.atlassian.net/browse/PLATFORM-484

[PLATFORM-453] Module search styling

---

app/src/editor/shared/tests/Client.test.jsx

I suspect this may be the cause of the CI failures.

Clean up client error handler in tests.

---

app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/shared/components/Notifications/Notifications.pcss
app/src/shared/components/Notifications/index.jsx
app/src/shared/components/Notifications/notificationStyles.js

Fixes notification style, position in editor.

[PLATFORM-467] Notification design feedback

---

app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/editor/shared/components/StreamSelector.jsx
app/src/editor/shared/components/StreamSelector.pcss

Add StreamSelector component for Stream module so that selected stream can be changed.
This component is shown on the Stream module so it's pretty easy to test just by adding any stream to the canvas.

[PLATFORM-409] StreamSelector component

---

app/package-lock.json
app/package.json
app/src/editor/shared/components/Client.jsx
app/src/editor/shared/tests/Subscription.test.jsx

Client & Subscription tests successfully run locally now.

Update to streamr client 2.0.0 beta.5

---

app/package.json
app/src/shared/components/Meatball/meatball.pcss
app/src/userpages/components/ProfilePage/DeleteAccount/DeleteAccountDialog/deleteAccountDialog.pcss
app/src/userpages/components/ProfilePage/DeleteAccount/DeleteAccountDialog/index.jsx
app/src/userpages/components/StreamPage/Show/HistoryView/historyView.pcss

Retrying this https://github.com/streamr-dev/streamr-platform/pull/324 as there were CI issues that may be solved in a new branch 🤷‍♂️

[PLATFORM-478] Streams/settings styling pass (rebuild..)

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss
app/src/editor/dashboard/components/ShareDialog.jsx
app/src/editor/dashboard/components/Toolbar.jsx

Update Dashboard styling to match: https://share.goabstract.com/986a1992-430c-465a-acc1-0b92d797a813
Removed also tick from canvas editor view when viewing realtime "reset and start" option in dropdown.

[PLATFORM-487] Dashboard Toolbar Styling

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/__snapshots__/services.test.js.snap
app/src/editor/canvas/tests/__snapshots__/state.test.js.snap

[PLATFORM-521] Set default run mode to 'realtime'

---

app/src/editor/canvas/components/KeyboardShortcutsSidebar.jsx

* Resets key pressed state whenever window loses or gains focus. Otherwise keys can get stuck in down state when focus is lost from window.
* Won't highlight shortcuts if user is currently focused in a form control/contenteditable.  Otherwise is annoying when editing something unrelated and shortcut keys that wouldn't actually fire anyway are flashing.

[PLATFORM-510] Shortcuts sidebar & focus handling

---

.travis.yml

* Remove platform public path enviroment variable

fix: Fix pull request asset path:

---

app/src/shared/components/AvatarCircle/avatarCircle.pcss
app/src/shared/components/DropdownActions/dropdownActions.pcss
app/src/shared/components/DropdownActions/index.jsx
app/src/shared/components/FallbackImage/index.jsx
app/src/shared/components/Meatball/meatball.pcss
app/src/shared/components/SvgIcon/index.jsx
app/src/shared/components/Table/table.pcss
app/src/shared/components/Tile/index.jsx
app/src/shared/components/Tile/tile.pcss
app/src/shared/components/WithHover/index.jsx
app/src/userpages/components/CanvasPage/List/canvasList.pcss
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/Layout/index.jsx
app/src/userpages/components/Layout/layout.pcss
app/src/userpages/components/PurchasesPage/index.jsx
app/src/userpages/components/PurchasesPage/purchases.pcss
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/List/streamList.pcss
app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/components/TransactionPage/List/list.pcss
app/src/userpages/i18n/en.po

See details here: https://streamr.atlassian.net/browse/PLATFORM-509
I fixed everything except the tile image sizing thing. It does not reproduce locally with current images we have for the products but you'll see the problem if one of the images has a different aspect ratio. I could not fix this without breaking bootstrap grid. Any ideas?

[PLATFORM-509] Core app style fixes

---

app/src/userpages/components/StreamPage/Show/index.jsx

To test: 
In the userpages, click 'Create Stream'. This should create the stream asset and redirect the browser to u/stream/show/new_stream_id.

[PLATFORM-492] Creates Stream Asset on Stream Show Route

---

app/src/editor/shared/tests/Subscription.test.jsx

Re-enable Subscription tests.

---

app/src/editor/shared/components/modules/Chart.jsx
app/src/shared/assets/stylesheets/common.pcss

* Changes chart font.
* Brings tooltips a little closer to mock.

[PLATFORM-545] Quick pass on Chart styles

---

app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/List/streamList.pcss

[PLATFORM-514] Bugfix: Min-height to streams table

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/index.pcss
app/src/editor/dashboard/components/Toolbar.jsx
app/src/editor/dashboard/index.jsx
app/src/editor/dashboard/index.pcss

[PLATFORM-553] Editor Loading States

---

.travis.yml

* Support beta deployment via BETA branch

chore: Beta deployment:

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/shared/components/SvgIcon/index.jsx

Clear field button now shows up in ModuleSearch text input when there's a search term present

[PLATFORM-525] Add clear field button for ModuleSearch

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss

Gets rid of the grey colour when disabled.

[PLATFORM-531] Start / Run / Stop button disabled state

---

app/src/shared/flowtype/stream-types.js
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/services.js

Adds a call for each stream list entry to fetch status and last updated date on load.

[PLATFORM-447] Stream list status

---

.travis.yml
app/README.md

I created separate project in LogRocket for beta and set the flag to enable it in beta env.
https://app.logrocket.com/et0uhu/streamr-frontend-beta

Enable LogRocket in beta env

---

.travis.yml
app/README.md
app/webpack.config.js

Latest report https://d1ozfnrmb08exd.cloudfront.net/report.html

Enable bundle analysis for PRs & staging.

---

app/src/shared/components/Onboarding/index.jsx
app/src/shared/components/Onboarding/onboarding.pcss

Safari
FF
@timoxley thanks for your input on this! 🙌

[PLATFORM-602] Fixed opening Onboarding component on FF and Safari

---

app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/flowtype/states/transaction-history-state.js
app/src/userpages/i18n/en.po
app/src/userpages/modules/transactionHistory/actions.js
app/src/userpages/modules/transactionHistory/reducer.js

Add new text for transaction list empty state + added some logic to prevent empty state from flashing before transactions come in.

[PLATFORM-607] Update transaction empty state

---

app/src/userpages/components/SnippetDialog/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/i18n/en.po

Removed stream name from title:

[PLATFORM-600] Change snippet dialog title

---

app/src/shared/components/Notifications/notificationStyles.js
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/i18n/en.po

Adds a notification to canvas list when copying canvas URL.

[PLATFORM-620] Add notification after canvas url copy

---

app/src/shared/flowtype/stream-types.js
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/i18n/en.po
app/src/userpages/modules/userPageStreams/actions.js

Adds an action to refresh stream from meatball menu.

[PLATFORM-606] Add action to refresh stream

---

app/src/shared/components/BodyClass/BodyClass.test.jsx
app/src/shared/components/BodyClass/index.jsx

I wanted to use this the other day for something but ran into a few issues, so I fixed them:
* Allows `className` updates via `props`
* Doesn't clobber classes added by other instances
* Adds basic tests

BodyClass component improvements

---

app/package-lock.json
app/package.json
app/webpack.config.js

re-juggling branches so we can get a testable deployment + discussion on an appropriate PR.
@fonty1 please evaluate the images generated when the PR gets deployed
*update*:  @fonty1: https://d1byvusjqrbmgh.cloudfront.net

Optimise Images V2

---

.travis.yml

* Start testing beta by pushing to production bucket and deployment in prod server

chore: Prepare deployment to production:

---

.travis.yml

- Fetch assets from cdn.streamr.com

fix: Add public path

---

app/src/marketplace/components/StreamPreviewPage/InspectorSidebar/index.jsx
app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx
app/src/shared/flowtype/user-types.js
app/src/shared/modules/user/actions.js
app/src/shared/test/modules/user/actions.test.js
app/src/shared/test/modules/user/reducer.test.js
app/src/shared/test/modules/user/selectors.test.js
app/src/shared/test/modules/user/services.test.js
app/src/userpages/components/ProfilePage/ProfileSettings/index.jsx
app/src/userpages/components/ProfilePage/ProfileSettings/profileSettings.pcss
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/tests/components/ProfilePage/ProfileSettings/profileSettings.test.jsx
app/test/unit/containers/EditProductPage/EditProductPage.test.jsx

Removing the Profile Timezone selector and all the associated references + tests.

[PLATFORM-640] Removing User Timezone

---

app/src/editor/shared/components/StreamSelector.jsx

Applies similar fixes to those applied to the stream/module search.
Not perfect but seems to fix the underlying critical bug reported in https://streamr.atlassian.net/browse/PLATFORM-663
@mikhaelsantos I've added you as a reviewer, when the PR deployment is available, can you confirm or deny that this fixes the issue?

[PLATFORM-663] Fix stream selector async issues

---

app/src/docs/content/code/gettingStarted.js
app/src/docs/content/gettingStarted.mdx

Docs - Include PythonRequests code snippet

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/canvas/index.jsx

See: https://streamr.atlassian.net/browse/PLATFORM-410
To test:
1. Add a module to a canvas
2. Select it
3. Open sidebar
4. Delete module
5. Sidebar should close

[PLATFORM-410] Close ModuleSidebar if module not found.

---

app/src/editor/canvas/components/Resizable/ResizeWatcher/index.jsx
app/src/editor/shared/components/Map/Map.jsx

[PLATFORM-666] Invalidate Map size when resizing

---

app/src/userpages/components/StreamPage/List/index.jsx

[PLATFORM-604] Remove addToCanvas button.

---

app/src/shared/components/Dropdown/index.jsx
app/src/userpages/components/ProfilePage/APICredentials/CredentialsControl/index.jsx
app/src/userpages/components/StreamPage/Show/ConfigureView/index.jsx
app/src/userpages/components/StreamPage/Show/HistoryView/index.jsx
app/src/userpages/components/StreamPage/Show/InfoView/index.jsx
app/src/userpages/components/StreamPage/Show/KeyView/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx
app/src/userpages/flowtype/states/stream-state.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/tests/modules/userPagesStreams/reducer.test.js

Now the stream edit view correctly respects user's permissions on given stream. If the user has no write permission, editable parts are disabled.

[PLATFORM-634] Stream edit view permissions

---

app/src/editor/canvas/components/CanvasSearch.jsx
app/src/editor/canvas/components/Toolbar.jsx

See: https://streamr.atlassian.net/browse/PLATFORM-685
Doesn't show up in overall list:
Also doesn't show up in direct search:

[PLATFORM-685] Remove current canvas from canvas list.

---

app/src/docs/content/tutorials.mdx

Replacing a placeholder with ReactPlayer video

Docs content video addition

---

app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/CanvasController/useCanvasLoadCallback.js
app/src/editor/canvas/components/Status.jsx
app/src/editor/canvas/components/Status.pcss
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss
app/src/editor/canvas/hooks/useCanvasPermissions.jsx
app/src/editor/canvas/index.jsx
app/src/editor/shared/components/Toolbar/toolbar.pcss

Details here: https://streamr.atlassian.net/browse/PLATFORM-591
I also disabled autosave for canvases we don't have write permission for. This is needed so that we don't get autosave failed notification.
Everything else is ready but I couldn't figure where to get owner's username. Do we even have an endpoint for fetching this data? I think we can get user's email address from permissions, but we'd still have to map it into a name somehow.

[PLATFORM-591] Toolbar styling for shared canvases

---

app/src/app/index.jsx
app/src/shared/components/MobileNav/index.jsx
app/src/shared/components/Nav/index.jsx

Resolving the right root for the right environment here.
https://streamr.atlassian.net/browse/PLATFORM-700
https://streamr.atlassian.net/browse/PLATFORM-701

[PLATFORM-700][PLATFORM-701] Logo/Marketplace root link fixes

---

.travis.yml

* Remove beta
* Prepare tagged deployment

chore: Remove beta:

---

app/src/app/index.jsx
app/src/shared/components/MobileNav/LogoItem/index.jsx
app/src/shared/components/Nav/LogoItem/index.jsx

The previous fix didn't work in production 🙈 best to have good ol' anchor tags I think.

[PLATFORM-700] Re-fixed root navigation

---

app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx

Quite self explanatory!
New ticket for the eventual functionality:
FE: https://streamr.atlassian.net/browse/PLATFORM-748
BE: https://streamr.atlassian.net/browse/CORE-1729

[PLATFORM-683] Hide 'Mine' & 'Sort' filter options in canvas, list and dashboard pages 

---

app/src/marketplace/styles/pcss/buttons.pcss
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx

This will fix https://streamr.atlassian.net/browse/PLATFORM-715. I made the `Create` buttons on the main views to be actual link buttons without the `button` wrapper like before.

[PLATFORM-715] Fix "Create" buttons to handle links better

---

app/src/shared/components/SelectInput/Select/index.jsx
app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogPermissionRow/ShareDialogPermission/index.jsx
app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogPermissionRow/index.jsx

Creating a more forgiving world. 
https://streamr.atlassian.net/browse/PLATFORM-710

[PLATFORM-710] Disables permission changes for the resource owner

---

app/webpack.config.js

Testing config options. Do not merge.

Sentry Debugging

---

app/src/app/index.jsx
app/webpack.config.js

Sentry testing

---

app/src/index.html

[PLATFORM-705] Update image for sharing

---

README.md
app/README.md
app/src/shared/components/DatePicker/index.jsx
app/src/shared/i18n/en.po
app/src/shared/utils/constants.js
app/src/userpages/components/StreamPage/Show/HistoryView/index.jsx
app/src/userpages/i18n/en.po

This PR contains only text changes, and consolidates the following tickets:
- [PLATFORM-753](https://streamr.atlassian.net/browse/PLATFORM-753): Fix help texts on stream page 
- [PLATFORM-863](https://streamr.atlassian.net/browse/PLATFORM-863): Ethereum Accounts help text change 
- [PLATFORM-804](https://streamr.atlassian.net/browse/PLATFORM-804): Text changes in historical data section of Stream view
- [PLATFORM-860](https://streamr.atlassian.net/browse/PLATFORM-860): Update READMEs

Various text changes

---

app/src/userpages/modules/userPageStreams/services.js

Change incorrect url
`/api/v1/stream/{id}/deleteDataUpTo`
to correct url
`/api/v1/streams/{id}/deleteDataUpTo`
Feel free to merge if tests pass

Fix deleteDataUpTo url

---

app/package-lock.json
app/package.json
app/src/analytics.js

[Sentry] Add rewrite integration

---

app/webpack.config.js

Potentially avoids minifying twice? Interested to see CI output. Don't merge.

[webpack] Use default production minifier.

---

app/src/userpages/tests/modules/dashboard/actions.test.js

Fix dashboard actions tests.

---

app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/shared/components/SearchPanel/SearchPanel.pcss

Small style tweaks for ModuleSearch, mainly font related.

[PLATFORM-801] Tweak ModuleSearch styles to match design

---

app/.stylelintrc
app/package-lock.json
app/package.json
app/postcss.config.js
app/scripts/postcss/ums.js
app/src/userpages/components/Header/Tab/tab.pcss

In this PR I make `um` a unit that you can use in your CSS. Unlink current `rem`, it always represents 16px.
Adding all of you as reviewers cause it'd be nice for all of us to be aware of its existence.
---
_`um` stands for Unit of measurement._

`um` as a real unit

---

app/src/newdocs/components/DocsLayout/Navigation/navLinks.js
app/src/newdocs/content/api.mdx
app/src/newdocs/content/canvases.mdx
app/src/newdocs/content/core.mdx
app/src/newdocs/content/dashboards.mdx
app/src/newdocs/content/marketplace.mdx
app/src/newdocs/content/products.mdx
app/src/newdocs/content/runningNode.mdx
app/src/newdocs/content/streams.mdx

Matching:
https://paper.dropbox.com/doc/Docs-Updated-Structure-Outline--Ad55Bas2n~7Jx8bCEhNzFtjXAg-uIJdQeNwC1ZvykWioFAgx
Empty files included so the repo can register the new placeholder folders

Updating Docs structure

---

app/package-lock.json
app/package.json
app/src/marketplace/components/ActionBar/SearchInput/index.jsx
app/src/marketplace/components/ActionBar/SearchInput/searchInput.pcss
app/src/marketplace/components/ActionBar/index.jsx
app/src/shared/components/EditableText/index.jsx

Added clear button for marketplace product search. It was more complicated than I thought since the input width is fluid in the designs. Ended up using `react-input-autosize` for getting input width resize dynamically when user writes a search term.

[PLATFORM-548] Add clear button for clearing Marketplace product search

---

app/src/shared/web3/web3Poller/web3Poller.js
app/src/shared/web3/web3Provider.js
app/test/unit/web3/web3Provider.test.js

Add fake provider as fallback when getting Web3 object

---

app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/List/streamsList.pcss
app/src/userpages/flowtype/actions/stream-actions.js
app/src/userpages/flowtype/states/stream-state.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/modules/userPageStreams/services.js
app/src/userpages/tests/modules/userPagesStreams/reducer.test.js
app/src/userpages/utils/constants.js

I removed the `min-height: 500px;` that was set on the list, apparently to meant to stop the meatball dropdown from being cropped when there were only a few streams in the list. For me seems to align nicely even when checking the last item on the list.

[PLATFORM-867] Add paging to stream list

---

app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/components/TransactionPage/List/list.pcss
app/src/userpages/modules/transactionHistory/reducer.js

Improve transaction pagination. Added padding to the table when fetching so it doesn't "jump" when scrolled to bottom and hitting "load more".

[PLATFORM-890] Improve transaction pagination

---

app/src/newdocs/content/code/streams.js
app/src/newdocs/content/streams.mdx

Added "Work with streams via SDKs" section.

[DOCS-38] Work with streams via SDK

---

app/src/marketplace/components/MarkdownEditor/index.jsx
app/src/marketplace/components/MarkdownEditor/markdownEditor.pcss
app/src/marketplace/containers/EditProductPage2/index.jsx
app/stories/marketplace.stories.jsx

Add reusable `MarkdownEditor` component and use it on `EditProductPage`.

[PLATFORM-921] Add MarkdownEditor for product description

---

app/src/newdocs/content/streams.mdx

This PR must make a reference to the protocol spec for readers interested in more details. The protocol spec is currently under review: https://github.com/streamr-dev/streamr-specs/pull/1.
Once the protocol PR is merged, the reference can be added and this PR can be merged.

[DOCS-20] Init signing doc

---

app/src/newdocs/content/streams.mdx

Partly recycled from V1 of the Streams documentation with a bit more information on what fields are.  
Should be compatible with https://github.com/streamr-dev/streamr-platform/pull/564

[DOCS-1] Intro to streams

---

app/src/marketplace/components/StreamSelector/index.jsx
app/src/marketplace/components/StreamSelector/streamSelector.pcss
app/src/marketplace/containers/AvailableStreams/index.jsx
app/src/marketplace/containers/EditProductPage2/EditorNav.jsx
app/src/marketplace/containers/EditProductPage2/StreamSelector.jsx
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/useProductActions.js
app/src/marketplace/i18n/en.po

~On top of #591~ First pass of stream selector that's pretty much the old component without any new styling. Selecting works and it updates the product accordingly.
Can be tested by going to any product page and adding `/edit2` to url.

[PLATFORM-925] Stream selector

---

app/src/auth/components/EthereumLogin/index.jsx
app/src/shared/utils/withWeb3.jsx
app/src/shared/web3/web3Provider.js

Make network check optional when calling `validateWeb3`.

[PLATFORM-956] Ethereum login should work regardless of selected network

---

app/src/marketplace/containers/AvailableCategories/index.jsx
app/src/marketplace/containers/EditProductPage2/Details.jsx
app/src/marketplace/containers/EditProductPage2/EditorNav.jsx
app/src/marketplace/containers/EditProductPage2/ProductDetails.jsx
app/src/marketplace/containers/EditProductPage2/details.pcss
app/src/marketplace/containers/EditProductPage2/index.jsx
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/useProductActions.js
app/src/shared/components/SelectInput/Select/index.jsx
app/src/shared/components/SelectInput/Select/selectInput.pcss
app/src/shared/components/SelectInput/index.jsx

First pass on the details section with category and admin fee, ~on top of #591~.

[PLATFORM-945] Product details section

---

app/src/userpages/components/StreamPage/Show/PreviewView/index.jsx
app/src/userpages/i18n/en.po

https://streamr.atlassian.net/browse/PLATFORM-984

[PLATFORM-984] Stream page data hint fix

---

app/src/editor/shared/components/modules/Chart.jsx

Not sure why but charts [were configured to not render for historical canvases](https://github.com/streamr-dev/streamr-platform/pull/626/files#diff-10ffa577d0578271496372a5d5325c71L89). Fixed this.
Also eslint was disabled for this file, I've re-enabled it and fixed warnings.

[PLATFORM-1000] Fix Chart rendering in Historical mode

---

app/src/editor/canvas/components/Preview.jsx
app/src/shared/components/Tile/tile.pcss
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx

[PLATFORM-1010] Add hover overlay to canvas/dashboard tiles.

---

app/src/userpages/components/StreamPage/Show/InfoView/index.jsx

Alternative fix for #644 
The underlying issue was using `setState` for `contentChanged` triggers a re-render which renders using the old name/description value, which is then immediately changed to the new value via prop, so because the input content changed, the input caret gets reset.
Also: 
* Fixes a `setState` after unmounted issue
* Only sets `contentChanged` if the content changes (not perfect, only detects this on first edit).

[PLATFORM-1019] Prevent resetting input caret while editing stream

---

app/src/docs/components/DocsLayout/Navigation/navigation.pcss
app/src/docs/components/DocsLayout/docsLayout.pcss
app/src/docs/components/DocsPages/CanvasModules/index.jsx
app/src/shared/components/Container/docs.pcss

Update width of main content in Docs to match design.

---

app/src/shared/components/Nav/nav.pcss

Fix top nav obscured by subnav/loading indicator

---

app/src/editor/canvas/components/Ports/Value/Select/index.jsx
app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/state/index.js
app/src/shared/components/EditableText/index.jsx

Boolean Select values

---

app/src/app/index.jsx
app/src/marketplace/components/ProductPage/productPage.pcss
app/src/marketplace/components/ProductPageEditor/productPageEditor.pcss
app/src/marketplace/containers/EditProductPage2/Preview.jsx
app/src/marketplace/containers/EditProductPage2/preview.pcss
app/src/marketplace/containers/ProductPage2/CollapsedText.jsx
app/src/marketplace/containers/ProductPage2/Page.jsx
app/src/marketplace/containers/ProductPage2/ProductDetails.jsx
app/src/marketplace/containers/ProductPage2/collapsedText.pcss
app/src/marketplace/containers/ProductPage2/index.jsx
app/src/marketplace/containers/ProductPage2/page.pcss
app/src/marketplace/containers/ProductPage2/productDetails2.pcss

Add new page for products. Matches new designs and will eventually support all community product features.
Check it out by replacing _/products/_ with _/products**2**/_ (e.g. http://localhost/marketplace/products2/5af088ad787786fa4f42695275bec834eeb8e16a45f65f4b5c657bf8ad505aba).

[PLATFORM-1025] New Product page layout

---

app/src/editor/canvas/components/Ports/Value/Map/index.jsx

Prevent crash on connecting Map value.

---

app/src/editor/canvas/components/ShareDialog.jsx
app/src/userpages/components/CanvasPage/List/index.jsx

[PLATFORM-655] Enable canvas embedding in production.

---

app/webpack.config.js

Add community products flag to webpack

---

app/src/docs/components/DocsLayout/docsLayout.pcss
app/src/docs/components/DocsPages/SDKs/index.jsx
app/src/docs/components/Warning/warning.pcss
app/src/docs/content/sdks/javaSdk.mdx
app/src/docs/content/sdks/javascriptSdk.mdx
app/src/docs/content/sdks/pythonSdk.mdx
app/src/docs/content/sdks/sdksOverview.mdx
app/src/docs/content/technicalNotes/howToContribute.mdx

[DOCS-81] SDK page content

---

app/src/marketplace/components/ExpirationCounter/expirationCounter.pcss
app/src/marketplace/components/ExpirationCounter/index.jsx
app/src/marketplace/containers/ProductPage2/Page.jsx
app/src/marketplace/containers/ProductPage2/ProductDetails.jsx
app/src/marketplace/containers/ProductPage2/index.jsx
app/src/marketplace/containers/ProductPage2/productDetails2.pcss
app/src/marketplace/modules/product/selectors.js
app/stories/marketplace.stories.jsx

Implements expiration counter as described here:
https://share.goabstract.com/e01f23a3-2198-41ce-961a-146ce7ecbeea?mode=build&sha=802210fc9cad4aad8a6c0d1054ff18e93e39de97
Counter is used on new product page to show remaining subscription time.
Check it out on storybook.

[PLATFORM-1031] Product expiration counter

---

app/src/editor/canvas/components/Camera/Camera.pcss
app/src/editor/canvas/components/Camera/index.jsx
app/src/editor/canvas/components/Camera/state.js
app/src/editor/canvas/components/ModuleRenderer/index.jsx
app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/hooks/useCanvasCamera.js
app/src/editor/canvas/index.jsx
app/src/shared/hooks/useGlobalEventWithin.js

Ensures module body visualisations like Table/Comment, and Port value UI like the stream selector, etc are scrollable, while rest of UI still zoomable.

Fix zoom vs scroll

---

app/src/editor/dashboard/components/Toolbar.jsx
app/src/editor/dashboard/components/Toolbar.pcss

Fix dashboard toolbar styling.

---

app/src/editor/canvas/index.jsx
app/src/marketplace/containers/EditProductPage2/index.jsx
app/src/shared/assets/stylesheets/variables.css
app/src/shared/components/Layout/index.jsx
app/src/shared/components/Nav/nav.pcss
app/src/shared/components/Toolbar/index.jsx
app/src/shared/components/Toolbar/toolbar.pcss
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx

Adds shadow under the nav for:
• Canvas editor
• Profile setting page
• Edit stream page
• Product creation page
@mondoreale you may have opinions about this, open to ideas/feel free to push to this PR.

[PLATFORM-1108] Nav Shadow

---

app/package-lock.json
app/package.json
app/src/editor/canvas/tests/java.test.js
app/src/editor/shared/components/Subscription.jsx
app/src/editor/shared/tests/Subscription.test.jsx

Old client no longer seems to work, any subscriptions with resends don't flow. Sometimes backend requests seem to never respond, which would be consistent with the tests that seem to be timing out inconsistently & intermittently.
This at least makes canvases work *sometimes*.

Update streamr-client to ^2.2.5.

---

app/src/docs/components/CanvasModuleHelp/canvasModuleHelp.pcss
app/src/docs/components/CanvasModuleHelp/index.jsx

Click on the module title to scroll to the module and append the relevant hash link to the end of the URL.

[DOCS-100] UI accessible hash links

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/shared/components/StatusIcon/index.jsx
app/src/shared/components/StatusIcon/statusIcon.pcss
app/src/shared/i18n/en.po
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx
app/stories/shared.stories.jsx

CSS solution for the status popover texts:
https://streamr.atlassian.net/browse/PLATFORM-1118

[PLATFORM-1118] Status popover text

---

.travis.yml
app/.dockerignore
app/Dockerfile
app/travis_scripts/deploy-docker.sh

- Dockerfile for platform
- Travis automation script for building docker image
Travis will first build the platform code and then "upload" it to the Docker image. Hence the Docker image is very simple as it only hosts static files. Drawback: inability to configure different settings. Upside: fast to start & low resource use.

Build docker image from Travis CI

---

app/src/shared/components/StatusIcon/statusIcon.pcss
app/src/userpages/components/StreamPage/List/streamsList.pcss

Quick fix for these issues w/ long names:
**Mobile before**
**Mobile after**
**Tablet before**
**Tablet after**

[PLATFORM-1135] Stream listing tablet/mobile overflow fixes

---

app/src/editor/shared/tests/Client.test.jsx
app/src/shared/components/StreamrClientContextProvider/index.jsx

[PLATFORM-1151] Restore ability to create unauthenticated streamr client.

---

app/Dockerfile
app/nginx.conf

Noticed that I need to to take react-router into account in the nginx configuration. Thus making sure stuff hits index properly. Related: https://github.com/streamr-dev/streamr-docker-dev/pull/44

Dockerfile: update to work with React Router

---

app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/marketplace/i18n/en.po
app/src/userpages/components/ProductsPage/index.jsx

As discussed with Matt, open product straight to editor from Products section.

[PLATFORM-1164] Open editor from product section tile

---

app/src/marketplace/containers/EditProductPage/Editor.jsx
app/src/marketplace/containers/EditProductPage/EditorNav.jsx
app/src/marketplace/containers/EditProductPage/SharedSecretEditor.jsx
app/src/marketplace/containers/EditProductPage/SharedSecrets.jsx
app/src/marketplace/containers/EditProductPage/sharedSecretEditor.pcss
app/src/marketplace/i18n/en.po
app/src/marketplace/modules/communityProduct/services.js
app/src/marketplace/modules/communityProduct/types.js

Almost forgot to create a PR for this but here it is.
Styles should get fixed when https://github.com/streamr-dev/streamr-platform/pull/778 is merged.

[PLATFORM-940] Add shared secrets to product settings

---

app/src/shared/components/TextField/NumberField/index.jsx
app/src/shared/components/TextField/index.jsx
app/src/shared/components/TextField/textField.pcss
app/src/userpages/components/StreamPage/Show/PartitionsView/partitionsView.pcss
app/src/userpages/components/StreamPage/Show/StatusView/index.jsx
app/stories/shared.stories.jsx

Add custom styled `NumberField` component which gets rendered when we have a `TextField` with `type="number"`. It has custom styled spin buttons.
Check it out on storybook 📖

[PLATFORM-1140] Add custom styled number input

---

.travis.yml
app/src/editor/canvas/tests/services.test.js
app/src/editor/shared/tests/ModuleSubscription.test.jsx
app/src/editor/shared/tests/Subscription.test.jsx
app/travis_scripts/deploy-docker.sh

Add new docker deploy script and use it for dev/nightly and production builds.
I'll add the cron job to Travis after we merge this.

[PLATFORM-1168] Docker versioning

---

app/src/shared/components/RadioButtonGroup/index.jsx
app/src/shared/components/RadioButtonGroup/radioButtonGroup.pcss
app/src/shared/components/RadioButtonGroup/readioButtonGroup.stories.jsx
app/stories/shared.stories.jsx

Changes `RadioButtonGroup` to use slider to indicate active state:

[PLATFORM-1160] Pricing Setting slider

---

app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/streamLivePreview.pcss
app/src/userpages/components/StreamPage/Show/PreviewView/index.jsx
app/src/userpages/components/StreamPage/Show/PreviewView/previewView.pcss
app/src/userpages/i18n/en.po

Live preview for stream editor is now styled according to design:
https://share.goabstract.com/47f70c6d-a1ad-44b6-b941-e24d1efe5b18?mode=build&sha=8b0bd88fa4a5781f3120beb9e6b7754b6a4245ab

[PLATFORM-1143] Style live preview for stream editor

---

app/src/userpages/components/StreamPage/Show/InfoView/index.jsx
app/src/userpages/modules/userPageStreams/reducer.js

Not sure why this is broken ATM the current code LGTM, but I'm obviously missing something!
This is a quick hotfix around the issue so users can edit the fields.

Hotfix for Stream Editor name/description inputs

---

app/src/userpages/modules/userPageStreams/reducer.js

This one is better than #812 cause it doesn't break fields editor.

Fix stream field inputs – reordering, names, etc.

---

app/package-lock.json
app/package.json
app/src/shared/modules/resourceKey/actions.js

Doesn’t seem to be needed/working.

Remove `react-notification-system-redux`

---

app/src/auth/components/TextInput/index.jsx
app/src/shared/components/TextField/NumberField/index.jsx

Fix for Stream page partitions number field only working when typing the number, ie. up/down buttons were not working. It's a bit of a hack but works for now.

Fix NumberField buttons not working

---

app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/i18n/en.po

The create button on the product listing page (core) had incorrect copy and was of a wrong kind, and only when the community products feature was disabled (in production). I fix it here.
💃

[PLATFORM-1196] Consistent "create" button styling

---

app/package.json

Increase storybook memory limit (Fix CI)

---

app/src/auth/components/Checkbox/checkbox.pcss
app/src/marketplace/components/Modal/GuidedDeployCommunityDialog/index.jsx
app/src/marketplace/components/Modal/ReadyToPublishDialog/readytopublish.pcss
app/src/shared/assets/images/checkbox-checked.svg
app/src/shared/assets/images/checkbox.svg
app/src/shared/components/Checkbox/checkbox.pcss
app/src/shared/components/ConfirmDialog/index.jsx
app/stories/shared.stories.jsx

Update to shared checkbox component to bring it in line with design:
Unchecked:
Checked:

[PLATFORM-2012] Update shared checkbox

---

app/src/marketplace/modules/deprecated/purchaseDialog/actions.js
app/src/marketplace/utils/web3.js
app/src/shared/hooks/useBalance.js
app/src/shared/hooks/useBalance.test.js
app/src/userpages/components/KeyField/KeyFieldEditor/index.jsx
app/src/userpages/components/KeyField/index.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/index.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/integrationKeyList.pcss
app/src/userpages/tests/components/KeyField/KeyField.test.jsx
app/src/userpages/tests/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/integrationKeyList.test.jsx
app/test/unit/utils/web3.test.js

Adds balance display for connected ethereum identities (in Profile):

[PLATFORM-872] Show ETH and data balance for connected accounts

---

app/package-lock.json
app/package.json

For whatever reason running canvases on 2.2.7 stopped working. Looks like with v3 it's fine again.

Update streamr-client to v3

---

app/README.md

Let me know if the standard deployment and hot fix procedures are clear. Feel free to add any 🌶tips.

[PLATFORM-1224] Update deployment documentation

---

.travis.yml

Update PR deploy url

---

app/src/auth/components/AuthPanelNav/authPanelNav.pcss
app/src/auth/components/Button/button.pcss
app/src/auth/components/Footer/index.jsx
app/src/auth/i18n/en.po
app/src/shared/i18n/cn.po
app/src/shared/i18n/de.po
app/src/shared/i18n/en.po
app/src/shared/i18n/es.po

Looks like this is all it takes! 💪

[PLATFORM-1232] Update styling for the auth pages

---

app/src/shared/components/StatusIcon/index.jsx
app/src/shared/components/StatusIcon/statusIcon.pcss
app/src/shared/i18n/en.po
app/src/userpages/components/ProductsPage/Members/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx
app/src/userpages/i18n/en.po

Add custom text to status icon tooltip so that we can add separate tooltips to Community member list.

[PLATFORM-1236] Add custom text to status icon tooltip

---

app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogPermissionRow/ShareDialogPermission/index.jsx
app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogPermissionRow/ShareDialogPermission/shareDialogPermission.pcss

Didn't notice that [`PLATFORM-647`](https://streamr.atlassian.net/browse/PLATFORM-647) is more of an idea. Anyway, materialized it. @mattatgit, thoughts?

[PLATFORM-647] Swap user id and name

---

.travis.yml
app/travis_scripts/smoke-test.sh

Add a simple smoke test to the check if container was started properly.

[PLATFORM-1235] Add smoke test for Docker builds

---

app/src/shared/contexts/ModalApi/index.jsx

Fixes issues where modals are left open after navigating away from the page, namely:
- Creating a new product and then hitting browser back button
- Clicking on purchase modal and then hitting browser back button

[PLATFORM-1243] Close modals on route change

---

app/src/marketplace/containers/EditProductPage/CoverImage.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.pcss
app/src/marketplace/containers/EditProductPage/ProductDescription.jsx
app/src/marketplace/containers/EditProductPage/ProductDetails.jsx
app/src/marketplace/containers/EditProductPage/ProductName.jsx
app/src/marketplace/containers/EditProductPage/ProductStreams.jsx
app/src/marketplace/containers/EditProductPage/editor.pcss
app/src/marketplace/i18n/en.po

Add product editor texts to translation file with docs links.
Toolbar button width issue is fixed in #858.

[PLATFORM-1206] Update product editor texts

---

app/src/marketplace/containers/ProductController/useEditableProductActions.js

See [`PLATFORM-1215`](https://streamr.atlassian.net/browse/PLATFORM-1215).

[PLATFORM-1215] Pre-set a non-zero product price when going from free to paid

---

app/src/userpages/components/ProductsPage/Members/index.jsx

Added fetching the member list after after removing.

[PLATFORM-1240] Fix removed join requests not being removed from the list

---

app/src/marketplace/components/ActionBar/actionBar.pcss
app/src/marketplace/components/Products/products.pcss
app/src/marketplace/containers/Products/index.jsx
app/src/marketplace/containers/Products/products.pcss
app/src/shared/components/Layout/Footer.jsx
app/src/shared/components/Layout/index.jsx

Change marketplace background to #F8F8F8 as requested in https://streamr.atlassian.net/browse/PLATFORM-1230
Design: https://share.goabstract.com/a590e0df-8cf7-4c4a-b75d-2b2b6c3de03a
For desktop, there is a separator above the footer. Not sure if this should be shown also for lower resolutions.

[PLATFORM-1230] Change marketplace background

---

app/src/marketplace/modules/allowance/services.js

Call the Uniswap adaptor contract, not the marketplace.

[PLATFORM-1270] Fix DAI getMyAllowance contract call

---

app/src/marketplace/components/NewProductPage.jsx
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/useNewProductMode.jsx
app/src/shared/contexts/Router/index.jsx

Add flag for new product, this won't trigger the nav validation until the user scrolls to each section. When editing, the sections are validated on load.

[PLATFORM-1265] Add url flag for new product creation

---

app/src/store.js

I can remember this working once upon a time but I can't remember what changed. Anyway, this should do the trick.

Enable redux dev tools in all environments

---

app/src/marketplace/components/Modal/CropImageModal/index.jsx
app/src/shared/components/DropdownActions/dropdownActions.pcss
app/src/shared/components/ImageUpload/index.jsx
app/src/userpages/components/ProductsPage/index.jsx

Went through styling tickets, most of the issues were fixed but here is a grabbag of those leftovers
https://streamr.atlassian.net/browse/PLATFORM-1155 Button & Input Field style fixes
- https://streamr.atlassian.net/browse/PLATFORM-1156 Button style fixes
- https://streamr.atlassian.net/browse/PLATFORM-1157 Input field fixes
- https://streamr.atlassian.net/browse/PLATFORM-1158 Other style fixes 
https://streamr.atlassian.net/browse/PLATFORM-1222 "View Product" links in Core should open the Marketplace in a new tab
https://streamr.atlassian.net/browse/PLATFORM-1239 Polish buttons & other components

Editor style fixes

---

app/src/marketplace/components/ProductPage/Description/description.pcss
app/src/marketplace/containers/ProductPage/RelatedProducts.jsx
app/src/shared/components/Container/product.pcss

Fixes:
- Description hugging the side in tablet
- Description vertical padding was uneven
- Related products only shoes 2 now instead of 3 on mobile devices

[PLATFORM-1285] - Minor styles on the product page

---

app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/TransactionPage/List/index.jsx

Now we are using `ago` from `$shared/utils/time` for displaying relative timestamps.

[PLATFORM-1281] Consolidate code for displaying relative timestamps

---

app/src/marketplace/components/Modal/InsufficientDaiDialog/index.jsx
app/src/marketplace/components/Modal/InsufficientDaiDialog/insufficientDaiDialog.pcss
app/src/marketplace/components/Modal/InsufficientDataDialog/insufficientDataDialog.pcss
app/src/marketplace/components/Modal/InsufficientEthDialog/insufficientEthDialog.pcss
app/src/marketplace/containers/EditProductPage/PublishModal.jsx
app/src/marketplace/containers/deprecated/WithContractProduct/index.jsx
app/src/marketplace/i18n/en.po
app/src/shared/components/Dialog/Container/container.pcss
app/src/shared/components/Dialog/ContentArea/contentArea.pcss
app/src/shared/components/Web3ErrorDialog/UnlockWalletDialog/index.jsx
app/src/shared/components/Web3ErrorDialog/UnlockWalletDialog/unlockWalletDialog.pcss
app/src/userpages/components/ProfilePage/IdentityHandler/AddIdentityDialog/index.jsx
app/stories/modal.stories.jsx

[PLATFORM-1284] Improve change current wallet dialogue

---

app/src/shared/components/MobileNav/Bar/bar.pcss
app/src/shared/components/MobileNav/index.jsx
app/src/shared/components/MobileNav/mobileNav.pcss
app/src/shared/components/Nav/AvatarItem/index.jsx
app/src/shared/components/SvgIcon/index.jsx
app/src/shared/i18n/en.po

Changes core responsive menu to match design:
**Signed out** 
Design
Implementation
https://share.goabstract.com/34d27f84-98cb-44b4-9f3a-fc668bc91937?mode=design&sha=8e5e8db7de798d4970de1594ea92ea8f22776f34
**Signed in**
Design
Implementation
https://share.goabstract.com/f80f3c4f-9807-405d-a4dd-c1b08f1fe75f?mode=design&sha=8e5e8db7de798d4970de1594ea92ea8f22776f34
Also added truncation of of ETH address username in desktop menu:

[PLATFORM-961] Refactor responsive menu

---

app/src/marketplace/i18n/en.po
app/src/shared/components/HoverCopy/index.jsx
app/src/shared/i18n/en.po
app/src/userpages/components/Avatar/NameAndUsername/index.jsx
app/src/userpages/components/ProductsPage/MenuItems.jsx
app/src/userpages/components/ProductsPage/index.jsx

Added contract address copy feature to data union header (on address hover) and into tile meatball menu.
In depth description can be found here: https://streamr.atlassian.net/browse/PLATFORM-1291

[PLATFORM-1291] Add copy feature for contract address

---

app/src/auth/components/LoginPage/index.jsx

Changes eth login to be visible only when there is an url flag, `/login?ethLogin=true`

Hide eth login button behind flag

---

app/src/auth/components/SessionProvider/index.jsx
app/src/auth/tests/SessionProvider.test.jsx
app/src/marketplace/containers/ProductPage/index.jsx
app/src/marketplace/containers/deprecated/ProductPage/index.jsx
app/src/shared/modules/user/reducer.js
app/src/shared/test/modules/user/reducer.test.js
app/test/unit/containers/ProductPage/ProductPage.test.jsx

Hotfixing #942 to `master`, requesting sanity check :)

Workaround for Marketplace expired token (Hotfix to master)

---

.travis.yml

* After updating cdn invalidate cache to fetch all new resources

feat: Cache invalidation:

---

app/src/docs/components/DocsLayout/index.jsx
app/src/shared/hooks/useScrollToTop.js

Quite decent quick fix for [`PLATFORM-1353`](https://streamr.atlassian.net/browse/PLATFORM-1353).
Added a cute little hook for pathname change handling.

[PLATFORM-1353] Scroll docs to top on pathname change

---

.gitignore
.travis.yml
app/.eslintrc.js
app/cypress.json
app/cypress/support/commands.js
app/cypress/support/index.js
app/package-lock.json
app/package.json
app/src/auth/components/AuthPanel/index.jsx
app/src/auth/components/LoginPage.spec.js
app/src/auth/components/Logo/index.jsx
app/travis_scripts/e2e-tests.sh

Started working on [`PLATFORM-1360`](https://streamr.atlassian.net/browse/PLATFORM-1360) and quickly realized that some kind of validation would help my work a lot.
Decided to try out https://www.cypress.io/
First impressions?
- It's heavy. Already disabled recording video of a test suite running – lol. And I'm going `--headless`.
- It's not fast (multiple seconds per spec). I wouldn't expect light speed from a e2e testing tool anyway but yeah. 😅 
- It's useful. Already helped me to identify a misspelled helper route, yay.
- Offers a pretty useful UI (see `npx cypress open`) if you care about that kind of stuff.
- The convention is to name cypress tests "specs" which I like! I put mine next to components I spec.
More coming. Let's iterate over it. If you guys have any other suggestions, …

[PLATFORM-297] End-to-end testing w/ Cypress

---

app/bin/routes
app/src/app/index.jsx
app/src/auth/components/AuthPanelNav/index.jsx
app/src/auth/components/ForgotPasswordPage/index.jsx
app/src/auth/components/LogoutPage/index.jsx
app/src/auth/components/RegisterPage/index.jsx
app/src/auth/components/ResetPasswordPage/index.jsx
app/src/auth/components/SignupPage/index.jsx
app/src/auth/components/UsernamePasswordLogin/index.jsx
app/src/auth/utils/loginInterceptor.js
app/src/auth/utils/userAuthenticated.js
app/src/editor/canvas/components/EmbedToolbar.jsx
app/src/marketplace/containers/ProductPage/Hero.jsx
app/src/routes/definitions.json
app/src/shared/components/MobileNav/index.jsx
app/src/shared/components/Nav/AvatarItem/index.jsx
app/src/shared/components/Nav/index.jsx
app/src/userpages/components/ProfilePage/ProfileSettings/ChangePasswordDialog/index.jsx

First round of `links` → `$routes` migration. Everything should work as expected!

Update route helpers for auth pages

---

app/src/docs/components/DocsLayout/docsLayout.pcss
app/src/docs/components/Pages/Sdk/sdk.pcss
app/src/docs/content/sdk/overview.mdx
app/src/docs/docsMap.js
app/src/links.js

In this PR:
- Feature SDK matrix for the three SDKs
- Updated SDK structure to match designs
@timoxley @harbu can you both comment on the accuracy of these capabilities -
- Are they up to date?
- Are there any other features we should include in this matrix?
**Updated 12.55pm EET:**
Original list:
https://github.com/streamr-dev/streamr-platform/pull/573/files/c3d5f853c64dc5dbac4f10e6b7ce570f7f36792f#diff-45bc07b7a6d850331b3e31dc2461cae9
https://share.goabstract.com/e313b1de-68b7-4c52-9ec8-62d6f8cdbb6c?mode=design&sha=a252e81af348b72654620ebb7be05eb030243947
@mattatgit PR URL **Updated 1.55pm EET:** : http://streamr-marketplace-pr-263aaa5ebdfb0b422da1b5951054eeb6352eec16.s3-website-eu-west-1.amazonaws.com/docs/sdk/overview

[DOCS-109] SDK Feature Matrix

---

.travis.yml

* Import configs
* Remove unecessary job (deployed only on branch beta)

chore: Centralise configs:

---

app/src/docs/components/DocsLayout/Navigation/navigation.pcss

Adds 34px to width of docsnav.

[DOCS-122] Widen docs navigation 

---

app/src/docs/components/DocsLayout/Navigation/index.jsx
app/src/docs/components/Search/index.jsx
app/src/docs/components/Search/search.pcss

Persist the search icon, as expected, on [esc] and search result click.

[DOCS-128] Search icon disappearing bugfix

---

app/src/app/Docs.jsx
app/src/docs/docsMap.js
app/src/docsLinks.js
app/test/unit/app/Docs.test.jsx

minor fix to avoid duplicate active selections

[DOCS-130] Navbug fix

---

app/src/shared/components/Sidebar/Header.jsx
app/src/shared/components/Sidebar/Sidebar.pcss
app/src/userpages/components/ShareSidebar/RadioButtonGroup/RadioButtonGroup.pcss
app/src/userpages/components/ShareSidebar/ShareSidebar.pcss
app/src/userpages/components/ShareSidebar/ShareSidebar.test.jsx
app/src/userpages/components/ShareSidebar/Sidebar.jsx
app/src/userpages/components/ShareSidebar/index.jsx
app/src/userpages/components/ShareSidebar/state.js
app/src/userpages/i18n/en.po

Also:
https://streamr.atlassian.net/browse/PLATFORM-1387

[PLATFORM-1387] Sharing sidebar design fixes

---

app/src/marketplace/components/StreamSelector/index.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.pcss
app/src/marketplace/i18n/en.po
app/src/userpages/i18n/en.po
app/test/unit/components/StreamSelector/StreamSelector.test.jsx

Addressing small UI tweaks from Matt (in [PLATFORM-1401](https://streamr.atlassian.net/browse/PLATFORM-1401))
[PLATFORM-1405](https://streamr.atlassian.net/browse/PLATFORM-1405):
- Change product editor stream selector sort options to name, created & added
[PLATFORM-1413](https://streamr.atlassian.net/browse/PLATFORM-1413):
- Change DU pages toolbar buttons to "View on Marketplace" and "Edit product"
[PLATFORM-1412](https://streamr.atlassian.net/browse/PLATFORM-1412):
- Change pending members empty state text
[PLATFORM-1411](https://streamr.atlassian.net/browse/PLATFORM-1411):
- Rename DU product tile options (“View members”, “View stats” & “View product”)
[PLATFORM-1403](https://streamr.atlassian.net/browse/PLATFORM-1403):
- Change DU fix price toggle label font weight

DU Pre-launch issues 

---

app/src/shared/components/TOCPage/TOCNav.jsx
app/src/userpages/modules/transactionHistory/services.js

Turns out I don't know how unix timestamps work 🙄

[PLATFORM-1422] Fix transaction list timestamp

---

app/src/marketplace/containers/ProductPage/Description.jsx
app/src/marketplace/containers/ProductPage/Page.jsx

I'll need to rush this past the goalie, but please take a look when you get a chance. Somewhat related to https://streamr.atlassian.net/browse/PLATFORM-1424 but for the product page specifically of all products.

[PLATFORM-1427] Hide subscriber info for free products

---

app/cypress/integration/ProductPage.spec.js
app/cypress/support/commands.js
app/src/auth/utils/loginInterceptor.js
app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/CanvasController/useCanvasLoadCallback.js
app/src/editor/dashboard/index.jsx
app/src/marketplace/containers/EditProductPage/ProductName.jsx
app/src/marketplace/containers/ProductController/index.jsx
app/src/marketplace/containers/ProductController/tests/useProductLoadCallback.test.jsx
app/src/marketplace/containers/ProductController/useContractProductLoadCallback.js
app/src/marketplace/containers/ProductController/useProductLoadCallback.js
app/src/marketplace/containers/ProductPage/index.jsx
app/src/shared/components/NotFoundPage/index.jsx
app/src/shared/hooks/useStreamPermissions.js
app/src/userpages/components/ProductsPage/Members/index.jsx
app/src/userpages/components/ProductsPage/Stats/index.jsx
app/src/userpages/components/StreamPage/index.jsx

Fix product loading so that only published products can be accessed on the product page. Trying to view a draft product now shows 404 page.

[PLATFORM-1374] Handle draft product loading permission

---

app/src/marketplace/containers/EditProductPage/EditorNav.jsx
app/src/marketplace/containers/EditProductPage/editorNav.pcss

Makes product editor nav less jumpy as reported in https://streamr.atlassian.net/browse/PLATFORM-1435

[PLATFORM-1435] DU side nav jumps around when list elements are clicked

---

app/src/docs/content/dataUnions/dataUnionsCore.mdx
app/src/docs/content/dataUnions/introToDataUnions.mdx
app/src/marketplace/components/Modal/GuidedDeployDataUnionDialog/index.jsx
app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/marketplace/i18n/en.po
app/src/shared/i18n/en.po
app/src/shared/utils/constants.js
app/src/shared/utils/text.js
app/test/unit/utils/text.test.js

Update DU member limit in texts where it is referred to to. Let me know if I missed any!

[PLATFORM-1433] Update DU member limit to UI texts

---

app/src/docs/components/Pages/Introduction/introduction.pcss
app/src/docs/content/introduction/introduction.mdx

Fix intro panel tile + fix duplicate sentence

[DOCS-114] [DOCS-115]

---

app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleRenderer/index.jsx
app/src/editor/dashboard/services.js
app/src/editor/shared/components/ModuleSubscription.jsx
app/src/editor/shared/components/RunStateLoader.jsx
app/src/editor/shared/services.js
app/src/shared/modules/resourceKey/selectors.js
app/src/userpages/flowtype/streamr-client-types.js

Fixes a bug that caused at least the Button and Text modules to not work.
**Steps to reproduce**
1) Create a canvas
2) Add Button module
3) Start canvas
The button should be active once the canvas is started.

[PLATFORM-1444] Fix canvas interact permission

---

app/src/shared/components/FieldList/FieldItem/fieldItem.pcss
app/src/shared/components/FieldList/FieldItem/index.jsx
app/src/userpages/components/StreamPage/Edit/ConfigureView/NewFieldEditor/newFieldEditor.pcss
app/src/userpages/components/StreamPage/Edit/ConfigureView/configureView.pcss
app/src/userpages/components/StreamPage/Edit/ConfigureView/index.jsx

This should round out:
https://streamr.atlassian.net/browse/PLATFORM-1429 &
https://streamr.atlassian.net/browse/PLATFORM-1352

[PLATFORM-1429][PLATFORM-1352] Stream fields alignment, replace meatball with trash can

---

app/package-lock.json
app/package.json
app/src/auth/i18n/en.po
app/src/docs/i18n/en.po
app/src/editor/i18n/en.po
app/src/marketplace/i18n/en.po
app/src/shared/i18n/cn.po
app/src/shared/i18n/de.po
app/src/shared/i18n/en.po
app/src/shared/i18n/es.po
app/src/userpages/i18n/en.po
app/webpack.config.js

Another quick one. Seems like a fair improvement, especially in terms of how you look them up. `t` uses dot notation now `msgid` does that too!

I18n keys: change ## to a dot

---

app/src/utils/streamSnippets.js

Quick PR where I unify all stream code snippets making them use priv key as the auth method.

[PLATFORM-1447] Unify stream snippets

---

app/src/marketplace/components/ProductPage/ProductDetails/index.jsx

[PLATFORM-1453] Disable purchase/request button while whitelist status is being checked

---

app/src/marketplace/containers/ProductPage/useDataUnionStats.js
app/src/marketplace/i18n/en.po

https://streamr.atlassian.net/browse/PLATFORM-1451

[PLATFORM-1451] Show revenue share instead of admin fee in DU stats

---

app/src/marketplace/containers/ProductPage/DataUnionStats.jsx
app/src/marketplace/containers/ProductPage/MembersGraph.jsx
app/src/marketplace/containers/ProductPage/dataUnionStats.pcss
app/src/marketplace/i18n/en.po
app/src/shared/components/DataUnionStats/index.jsx
app/src/shared/components/TimeSeriesGraph/index.jsx
app/src/userpages/components/ProductsPage/Stats/index.jsx
app/src/userpages/components/ProductsPage/Stats/stats.pcss

Fixes https://streamr.atlassian.net/browse/PLATFORM-1445.
Also made TimeSeriesGraph to always fill parent so now it scales better when screen size changes. Previous version had fixed width and height.

[PLATFORM-1445] Fix product page layout breaking on small screens

---

app/src/editor/canvas/components/CanvasController/useCanvasPermissions.jsx
app/src/editor/canvas/index.jsx
app/src/editor/dashboard/components/Toolbar.jsx
app/src/editor/dashboard/index.jsx
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/ShareSidebar/Sidebar.jsx
app/src/userpages/components/ShareSidebar/index.jsx
app/src/userpages/components/ShareSidebar/state.js
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/flowtype/actions/permission-actions.js
app/src/userpages/i18n/en.po
app/src/userpages/modules/permission/actions.js
app/src/userpages/modules/permission/reducer.js

Refactor sidebar to show the current user. Now it will show the active user on top and handles reloading the permissions after closing the sidebar.

[PLATFORM-1448] Refactor sidebar to allow deleting own permission

---

app/src/docs/components/DocsLayout/DocsNav.jsx
app/src/docs/content/introduction/introduction.mdx
app/src/routes/definitions.json
app/src/shared/components/Layout/Footer.jsx
app/src/shared/components/Layout/Nav.jsx
app/src/shared/i18n/en.po
app/src/shared/i18n/es.po

Couple renames, tweaks and fixes.

[FRONT-2] Core app → consistency pass on tablet

---

app/src/marketplace/containers/ProductPage/MembersGraph.jsx

Use streamr-client Subscription to get stream data instead of HTTP API.

[FRONT-149] Fix data union members graph

---

app/src/shared/components/Layout/Nav.jsx
app/src/shared/components/Tile/index.jsx
app/src/userpages/components/TransactionPage/List/NoTransactions/index.jsx

I'm pretty sure I found them all. I like the new way better. It's explicit! Cheers

Move hashes into route options

---

app/cypress/integration/LoginPage.spec.js
app/src/auth/components/AuthPanel/index.jsx
app/src/auth/components/UsernamePasswordLogin/index.jsx
app/test/unit/components/AuthPage/AuthPanel/index.test.jsx

Brings back the signup link to login page.

[FRONT-188] Restore signup link

---

app/src/marketplace/components/Products/NoProductsView/index.jsx
app/src/shared/components/EmptyState/index.jsx
app/src/shared/components/GenericErrorPage/index.jsx
app/src/shared/components/NotFoundPage/index.jsx
app/src/shared/i18n/en.po
app/src/userpages/components/CanvasPage/List/NoCanvases/index.jsx
app/src/userpages/components/DashboardPage/List/NoDashboards/index.jsx
app/src/userpages/components/ProductsPage/Header.jsx
app/src/userpages/components/ProductsPage/Members/NoMembers/index.jsx
app/src/userpages/components/ProductsPage/NoProducts/index.jsx
app/src/userpages/components/PurchasesPage/NoPurchases/index.jsx
app/src/userpages/components/StreamPage/List/NoStreams/index.jsx
app/src/userpages/components/TransactionPage/List/NoTransactions/index.jsx

Fix console warning in Subscriptions page empty state when nesting `<div>` inside `<p>`.

[FRONT-189] Fix console warning in Core > Subcriptions

---

app/src/userpages/components/ProfilePage/ProfileSettings/index.jsx

Removed old limitations for email editing. The email field is editable always now.

[FRONT-218] Enable email address editing

---

app/package-lock.json
app/package.json
app/src/docs/components/DocsLayout/DocsNav.jsx
app/src/shared/components/Layout/Nav.jsx
app/src/userpages/components/ShareSidebar/Share.jsx

Fixes current `Button` usages to new version from `streamr-layout`. This will enable us to use `Nav` fixes from newest version of `streamr-layout`.
PS. This is still waiting for `streamr-layout` publish. After that I can update the package version here.

Update to use new Button from streamr-layout

---

app/src/marketplace/containers/ProductPage/MembersGraph.jsx
app/src/shared/components/TimeSeriesGraph/index.jsx
app/src/shared/utils/getClientConfig.js

Fixes MemberGraph to show changes more accurately. Now it displays a "staircase" graph which better visualizes actual member count changes.

[FRONT-55] Fix member graph

---

app/src/userpages/i18n/en.po

Fixed a few inaccuracies and outdated bits in the Stream page copy. Text changes only.

Text fixes on stream page

---

app/src/shared/i18n/en.po

This will fix stream status to show `Inactive` instead of `No data yet`.

[FRONT-175] Fix inactive stream status

---

app/src/shared/components/List/index.jsx
app/src/userpages/components/TransactionPage/List/index.jsx

Transaction list table layout was broken and is fixed now. Also updated how we show payments done with ETH or DAI.

[FRONT-85] Fix transaction list layout and improve currency display

---

app/src/marketplace/i18n/en.po

Update connect/signing modal explainer text

---

.travis.yml

Add missing DATAUNION_VERSION flag

---

app/src/marketplace/containers/EditProductPage/Preview.jsx
app/src/marketplace/containers/ProductPage/DataUnionStats.jsx
app/src/marketplace/containers/ProductPage/MembersGraph.jsx
app/src/marketplace/containers/ProductPage/MembersGraphV2.jsx
app/src/marketplace/containers/ProductPage/Page.jsx
app/src/marketplace/containers/ProductPage/SubscriberGraph.jsx
app/src/marketplace/modules/contractProduct/services.js
app/src/marketplace/modules/dataUnion/services.js
app/src/shared/components/ActivityList/index.jsx
app/src/shared/utils/ethereum.js
app/src/shared/web3/abis/dataunion.json
app/src/shared/web3/config.js
app/src/userpages/components/ProductsPage/Stats/index.jsx
app/test/unit/web3/config.test.js

This PR adds a new component `MembersGraphV2` which uses sidechain to fetch data needed for displaying the the graph.
Also fixes `MembersGraph` to work on DU1 products. This was broken due to `streamr-client` changes.

[FRONT-272] Members graph for DU2

---

app/src/marketplace/containers/ProductPage/PurchaseModal.jsx
app/src/marketplace/containers/ProductPage/usePurchase.js
app/src/marketplace/modules/product/services.js
app/src/shared/utils/constants.js

>  Add a gas modifier that gets added to the gas limit in case the product being purchased is a DU2 product. The modifier should have the value of 250,000.
Adds a modifier to gas limit if a DU2 product is being purchased.

[FRONT-311] Buying a DU2 product requires more gas, increase gas limit

---

app/src/marketplace/containers/Products/index.jsx
app/src/marketplace/modules/dataUnion/reducer.js
app/src/marketplace/modules/productList/actions.js

Fixes DU stats loading on product page.

[FRONT-317] Fix DU member count badge not shown in marketplace

---

app/src/marketplace/modules/dataUnion/hooks/useDataUnionMembers.jsx

Small fix to correct `removeMembers` call signature.

Fix removeMembers parameters

---

app/src/marketplace/containers/ProductController/tests/ValidationContextProvider.test.jsx
app/src/marketplace/utils/product.js
app/src/userpages/components/DataUnionPage/Item.jsx
app/src/userpages/components/DataUnionPage/index.jsx

On top of #1234 , this adds the deploy dialog to the DU list view and handles updating the incoming `beneficiaryAddress`.

[FRONT-405] Deploy DU from list view (2/2)

---

app/cypress/integration/StreamPage.spec.js
app/src/marketplace/containers/EditProductPage/ConnectEthIdentity.jsx
app/src/marketplace/containers/EditProductPage/Editor.jsx
app/src/marketplace/containers/EditProductPage/EditorNav.jsx
app/src/marketplace/containers/EditProductPage/index.jsx
app/src/marketplace/containers/EditProductPage/useIsEthIdentityNeeded.js
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/index.jsx
app/src/marketplace/containers/ProductController/tests/ValidationContextProvider.test.jsx
app/src/marketplace/containers/ProductController/useResetDataUnionCallback.js
app/src/marketplace/modules/dataUnion/actions.js
app/src/marketplace/modules/dataUnion/constants.js
app/src/marketplace/modules/dataUnion/reducer.js
app/src/marketplace/utils/product.js
app/src/marketplace/utils/validate.js
app/src/userpages/components/DataUnionPage/Item.jsx
app/src/userpages/components/DataUnionPage/index.jsx
app/test/unit/utils/product.test.js

In preparation for adding the deploy dialog to DU list view, this adds validation to the publish option in the list. See comments for notes.
Missing from this PR, will be be added in 2/2:
- Add deploy option & hide publish if DU not deployed
- Deploy dialog
- Handle saving of incoming beneficiary address when DU is deployed

[FRONT-405] Deploy DU from list view (1/2)

---

app/src/routes/definitions.json
app/src/shared/components/Layout/Footer.jsx

Update footer links to match public site.

[FRONT-659] Sync Core footer and website footer

---

app/src/shared/web3/web3Provider.js

Wallet locked dialog was not shown on purchase because `eth_requestAccounts` call in MetaMask waits forever for user to unlock the account. Promise is not rejected even if you discard the notification so I added a superficial timeout for that.
Now user will see `Wallet is locked` dialog if account is locked in MetaMask when trying to purchase a product.

[FRONT-723] Fix wallet locked dialog not being shown on purchase

---

app/src/shared/components/PermissionsProvider/groups.js
app/src/shared/components/PermissionsProvider/index.jsx
app/src/shared/components/PermissionsProvider/operations.js
app/src/shared/components/PermissionsProvider/usePersistPermissionDiff.js
app/src/shared/components/PermissionsProvider/utils/combine.js
app/src/shared/components/PermissionsProvider/utils/combine.test.js
app/src/shared/components/PermissionsProvider/utils/countOperations.test.js
app/src/shared/components/PermissionsProvider/utils/getOperationKeys.test.js
app/src/shared/components/PermissionsProvider/utils/getPermissionsDiff.js
app/src/shared/components/PermissionsProvider/utils/getPermissionsDiff.test.js
app/src/shared/components/PermissionsProvider/utils/identifyGroup.test.js
app/src/shared/components/PermissionsProvider/utils/lookup.test.js
app/src/shared/components/PermissionsProvider/utils/reducer.js
app/src/shared/components/PermissionsProvider/utils/reducer.test.js
app/src/shared/components/PermissionsProvider/utils/toOperationId.test.js
app/src/shared/components/PermissionsProvider/utils/toOperationKey.js
app/src/shared/components/PermissionsProvider/utils/toOperationKey.test.js
app/src/shared/components/PermissionsProvider/utils/toOperationName.js
app/src/shared/components/PermissionsProvider/utils/toOperationName.test.js
app/src/shared/utils/sharing/canShareToUserId.js
app/src/userpages/components/ShareSidebar/AnonAccessSelect.jsx
app/src/userpages/components/ShareSidebar/Checkbox.jsx
app/src/userpages/components/ShareSidebar/NewShareForm.jsx
app/src/utils/address0.js

[FRONT-814] Permissions sidebar

---

app/src/marketplace/components/Modal/GetCryptoDialog/index.jsx
app/src/marketplace/components/Modal/GetDataTokensDialog/index.jsx

https://uniswap.io -> https://app.uniswap.org

[FRONT-913] Fix Uniswap link addresses

---

app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/index.jsx

StreamPage no longer needs a chain connection on MetaMask. There was a bug with client that has already been fixed 🎉

[FRONT-848] Network switch dialog shown prematurely

---

app/src/config/development.toml
app/src/config/production.toml
app/src/getters/getCoreConfig.js
app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/marketplace/containers/EditProductPage/TokenSelector.jsx
app/src/marketplace/containers/EditProductPage/state.js
app/src/marketplace/containers/EditProductPage/tests/EditControllerProvider.test.jsx
app/src/marketplace/containers/EditProductPage/tests/productState.test.js
app/src/marketplace/containers/EditProductPage/tests/usePublish.test.jsx
app/src/marketplace/containers/EditProductPage/usePublish.js
app/src/marketplace/containers/ProductController/useProductLoadCallback.js
app/src/marketplace/containers/ProductPage/DataUnionStats.jsx
app/src/marketplace/containers/ProductPage/MembersGraph.jsx
app/src/marketplace/flowtype/global-types.js
app/src/marketplace/modules/dataUnion/actions.js
app/src/marketplace/modules/dataUnion/hooks/useAllDataUnionStats.js
app/src/marketplace/modules/dataUnion/hooks/useDataUnionMembers.jsx
app/src/marketplace/modules/dataUnion/services.js
app/src/userpages/components/DataUnionPage/Item.jsx
app/src/userpages/components/DataUnionPage/ManageJoinRequests.jsx
app/src/userpages/components/DataUnionPage/ManageMembers.jsx
app/src/userpages/components/DataUnionPage/Management.jsx

Can't reopen #1238 so here's a copy. @tumppi, `development` branch is deprecated. Let's wait for `brubeck` to land and (then) target this PR at `master`.

[FRONT-413] Dataunion management to use subgraph

---

app/src/shared/components/Rect.tsx
app/src/shared/components/Spinner/index.tsx
app/src/shared/components/Tile/Badge.tsx
app/src/shared/components/Tile/Label.ts
app/src/shared/components/Tile/Summary.tsx
app/src/shared/components/Tile/Tile.stories.tsx
app/src/shared/components/Tile/index.tsx

Styling & solving typescript errors

[FRONT-1125] Project tile

---

app/src/docs/content/streamrNetwork/installingABrokerNode.mdx

Net 719 docs update broker instructions

---

app/package.json
app/src/config/development.toml
app/src/marketplace/components/ActionBar/index.tsx
app/src/marketplace/components/Projects/index.tsx
app/src/marketplace/containers/Projects/index.tsx
app/src/pages/AbstractStreamEditPage/InfoSection/StreamId.tsx
app/src/services/marketplace.ts
app/src/services/projects.ts
app/src/shared/components/Notifications/index.tsx
app/src/shared/components/Tile/index.tsx
app/src/shared/hooks/useDeepEqualMemo.ts
app/src/shared/web3/abis/marketplace.json
app/src/shared/web3/abis/projectRegistry.json

Adds services for loading projects from subgraph and saving them to smart contracts.
Project listing will now load projects from The Graph.

[FRONT-1160] Smart contract backend

---

app/src/pages/AbstractStreamEditPage/state.ts

We remove what's on the current list but is not on the new list.

FRONT-1326: Fix disabling storage nodes

---

app/src/shared/hooks/usePreventNavigatingAway.ts

The `usePreventNavigatingAway` can do 2 things now:
1. Block navigating away (reloads, native link click, etc.), and
2. Block the internal router (history).

FRONT-1316: Prevent internal navigation *if*

---

app/src/pages/AbstractStreamEditPage/RelatedProjects.tsx
app/src/pages/StreamPage.tsx
app/src/services/projects.ts

Add `This stream belongs to following projects` section to stream views.

[FRONT-1333] Stream view related projects

---

app/src/pages/AbstractStreamEditPage/AccessControlSection/index.tsx
app/src/pages/AbstractStreamEditPage/HistorySection/index.tsx
app/src/pages/AbstractStreamEditPage/InfoSection/index.tsx
app/src/pages/AbstractStreamEditPage/PartitionsSection.tsx
app/src/pages/StreamEditPage.tsx
app/src/pages/StreamPage.tsx
app/src/shared/stores/streamAbilities.ts

I add "Stream" to the names, do some minor restructuring and unleash Prettier upon it.
I'm prepping to add something similar (ability hooks) for projects very soon. cc @tumppi

Rename abilities util/store

---

app/src/shared/stores/streamAbilities.ts

Fixed `useStreamAbility` to fetch public permissions if user is not logged in.

[FRONT-1379] Logged out stream permissions

---

app/src/shared/components/Tabs.tsx

The new designs have more "squareish" tabs, so I already updated the styles for Tabs component

Updated the styles of Tabs component

---

app/src/shared/hooks/usePreventNavigatingAway.ts

FRONT-1481: Fix back button blockade

---

app/src/shared/stores/streamAbilities.ts

This fixes the `useStreamAbility` hook quite nicely.

FRONT-1490: Fix local stream permission invalidation

---

src/components/ActionBars/OperatorActionBar.tsx
src/getters/getBalance.ts
src/hooks/useDelegateAndUndelegateFunds.ts
src/modals/DelegateFundsModal.tsx
src/modals/UndelegateFundsModal.tsx
src/utils/delegation.ts

What I also did here is I moved the delegation & undelegation logic to a hook because this was getting too big to be kept inside of a component & also now it will be possible to use it in other components as well.

[FRONT-1563] Delegation validation

---

package-lock.json
package.json

https://linear.app/streamr/issue/FRONT-1593/update-streamr-config

FRONT-1593 - Update Streamr Config

---

src/pages/SingleOperatorPage.tsx

Plus, inform them where the monies go.

FRONT-1608: Allow strangers to collect operators earnings

---

src/components/Nav/index.tsx
src/shared/components/Popover/index.tsx

I also give the dropdown more distinguishable shadow.

FRONT-1615: Update Network dropdown's active item's styling

---

src/generated/gql/du.ts
src/generated/gql/network.ts
src/getters/index.ts
src/parsers/OperatorParser.ts
src/queries/network.ts

@tumppi & @mondoreale - let's merge it when those changes in the graph will be deployed to Mumbai

New graph data mappings

---

src/forms/createSponsorshipForm.ts
src/hooks/sponsorships.ts
src/modals/CreateSponsorshipModal.tsx
src/pages/SponsorshipsPage.tsx
src/services/sponsorships.ts
src/utils/sponsorships.tsx

Few notes:
- I make the modal deal with the entire creating process internally = dropped `onSubmit` or `onResolve` callbacks which were more of a problem than a solution (redundant back & forth dance with the input data).
- I drop a whole bunch of dynamic (and unused) properties, and 
- make the modal deal with exceptions in a more mature manner.

"Create sponsorship" modal retouch

---

src/components/ActionBars/AboutEntity.tsx
src/components/ActionBars/SponsorshipActionBar.tsx
src/components/Table.tsx
src/getters/index.ts
src/parsers/OperatorParser.ts
src/parsers/SponsorshipParser.ts

Clarity ftw.
Addresses
- FRONT-1645
- FRONT-1629

FRONT-1645: Conditionally show sponsorship's "Funded until", rename Active to Paying

---

src/services/sponsorships.ts

Added 1.5x multiplier to `sponsorship.stake()` contract call.

[FRONT-1650] Sponsorship staking gasLimit multiplier

---

src/components/ActionBars/SponsorshipActionBar.tsx
src/components/QueriedSponsorshipsTable.tsx
src/hooks/operators.ts
src/hooks/sponsorships.ts
src/hooks/useSponsorshipFundingHistoryQuery.ts
src/modals/FundSponsorshipModal.tsx
src/pages/SingleSponsorshipPage.tsx
src/services/sponsorships.ts
src/utils/sponsorships.tsx

The refactored modal does not disappear until blocks are in sync. Plus, I push the idea of invalidating only active queries.

Refactor "Sponsor a sponsorship" modal, utils, and services

---

.github/workflows/ci.yml
src/app.tsx
src/getters/confirm.ts
src/modals/ConfirmationModal.tsx
src/modals/OperatorModal.tsx
src/pages/SingleOperatorPage.tsx
src/services/operators.ts
src/services/sponsorships.ts
src/utils/blocks.ts
src/utils/index.tsx

Using the info icon known from info toasts.
---
I also bake in more "wait for block sync as long as necessary" logic refactoring here.

FRONT-1648: Friendlier icon in the confirmation box

---

src/components/ActionBars/NetworkActionBar.styles.tsx
src/components/ActionBars/SponsorshipActionBar.tsx
src/components/ImageFilePicker.tsx
src/components/Layout.tsx
src/components/NetworkUtils.tsx
src/components/QueriedSponsorshipsTable.tsx
src/getters/index.ts
src/hooks/operators.ts
src/hooks/sponsorships.ts
src/modals/ConnectModal.tsx
src/modals/DelegateFundsModal.tsx
src/modals/EditStakeModal.tsx
src/modals/FundSponsorshipModal.tsx
src/modals/JoinSponsorshipModal.tsx
src/pages/NetworkOverviewPage.tsx
src/pages/OperatorsPage.tsx
src/pages/SingleOperatorPage.tsx
src/services/sponsorships.ts
src/utils/sponsorships.tsx

On top of a lot of rearrangements and simplifications it also makes each possible workflow wait for the Graph to sync to the given block height. It's neat!

Refactor stake editing

---

src/shared/stores/operatorReachability.ts

This should do it.
---
This reverts commit daa4f9c5bcf0135db3e1afbf01c645ec5250890e.

FRONT-1653: Add real node reachability check

---

package-lock.json
package.json
src/shared/components/StreamrClientProvider.tsx

See https://github.com/streamr-dev/streamr-client-react/commit/7ce420843da57d5a0bf5dbe884011c1eb5047c34 for more details.

Apply the new fix for the "Client destroyed" exception

---

src/generated/gql/ens.ts
src/getters/index.ts
src/pages/AbstractStreamEditPage/InfoSection/useStreamOwnerOptionGroups.ts
src/queries/ens.ts
src/shared/stores/wallet.ts

For ENS domains I switch from contract-based fetching to fetching the ENS subgraph.

FRONT-1710: Resolve the "Failed to fetch ens domain name" issue

---

src/components/FloatingToolbar.tsx
src/hooks/useInViewport.ts
src/pages/ProjectPage/EditorNav.tsx
src/pages/StreamPage.tsx
src/shared/components/Button/index.tsx
src/shared/components/ModalDialog/index.tsx

FRONT-1692: Make Save button sticky for Streams and Projects

---

src/generated/gql/network.ts
src/queries/network.ts

The default (100) is already too small.

FRONT-1729: Fetch the first 1k sub-collection items

---

src/components/QueriedSponsorshipsTable.tsx
src/generated/gql/network.ts
src/getters/index.ts
src/hooks/sponsorships.ts
src/modals/CreateSponsorshipModal.tsx
src/pages/AbstractStreamEditPage/SponsorshipsTable.tsx
src/pages/StreamPage.tsx
src/queries/network.ts

Sponsorships are now listed in stream view. There is a CTA to create one if there is none.

[FRONT-1672] Add some Sponsorship features to the Stream view

---

src/components/QueriedSponsorshipsTable.tsx
src/components/Table.tsx

Fixes APY and funded until display on sponsorship listing page.

[FRONT-1746] Sponsorship funded until & APY display

---

src/components/Table.tsx
src/pages/SingleOperatorPage.tsx
src/services/sponsorships.ts
src/shared/stores/uncollectedEarnings.ts

Uncollected earnings are now updated once per second so operators can see how much they are earning.

[FRONT-1597] Update uncollected earnings in realtime

---

src/pages/SingleOperatorPage.tsx

We now got 2, for v0 and v1. Current version is v2.
Cheers!

FRONT-1817: Update the "outdated operator contract" warning

---

src/components/SponsorshipFilterButton.tsx
src/generated/gql/network.ts
src/getters/index.ts
src/hooks/sponsorships.ts
src/pages/SponsorshipsPage.tsx
src/queries/network.ts
src/shared/components/SvgIcon/index.tsx
src/shared/components/Toggle/index.tsx
src/shared/components/Toggle/toggle.stories.tsx

Adds filtering capabilities to sponsorship listing. Users can now hide e.g. inactive and without funding sponsorships.

[FRONT-1736] Sponsorship list filtering

---

src/components/AddressTable.tsx
src/consts.tsx
src/hooks/operators.tsx
src/modals/CreateSponsorshipModal.tsx
src/modals/DelegateFundsModal.tsx
src/modals/EditStakeModal.tsx
src/modals/ForceUndelegateModal.tsx
src/modals/FundSponsorshipModal.tsx
src/modals/JoinSponsorshipModal.tsx
src/modals/OperatorModal.tsx
src/modals/UndelegateFundsModal.tsx
src/services/operators.ts
src/services/projects.ts
src/services/sponsorships.ts
src/shared/stores/purchases.ts
src/shared/stores/wallet.ts
src/utils/tx.ts

In this PR I address the issue where the UI does not react to transaction replacement (repriced or cancelled).

FRONT-1887: Better handling of replaced transactions

---

package-lock.json
package.json
src/components/QueriedSponsorshipsTable.tsx
src/components/QueriedStreamsTable.tsx
src/components/StreamIdDropdown.tsx
src/hooks/operators.tsx
src/hooks/projects.tsx
src/hooks/sponsorships.ts
src/hooks/streams.tsx
src/hooks/useSponsorshipFundingHistoryQuery.ts
src/pages/OperatorsPage.tsx
src/pages/ProjectListingPage.tsx
src/stores/streamDraft.tsx
src/utils/tokens.ts

This needs some manual testing.

FRONT-1892: Upgrade to `@tanstack/react-query` v5

---

src/modals/AccessPeriodModal.tsx
src/modals/AccessingProjectModal.tsx
src/modals/ProjectModal.tsx
src/modals/PurchaseCompleteModal.tsx

Fixes mainly project purchase flow

[FRONT-1456] Mobile UX fixes

---

src/components/Stats.tsx
src/generated/gql/indexer.ts
src/generated/gql/network.ts
src/getters/getNeighbors.ts
src/getters/getStreamStats.ts
src/hooks/streams.tsx
src/hooks/useStreamStats.tsx
src/queries/indexer.ts
src/services/streams.ts

Pretty much copied the logic from network-explorer. Let's add this feature to the shared library once we have it.

Add stream latency calculation
