streamr-dev/hub

app/jsconfig.json

I'd like to add jsconfig.json to the project root so that vscode will know how to follow path aliases. With this addition `Go to definition (F12)` works with path aliases.

Add jsconfig.json for vscode

---

app/package-lock.json
app/package.json
app/webpack.config.js

I'm working on async `zxcvbn` loading. It's going pretty well. 💃 I'd like to merge this little puppy first tho. I saw @fonty1 using it long time ago, thought it's kinda cool; why don't we use it?
It is useful to analyze both production and development bundles that's why it's included for both envs. You have to explicitly request it when running `npm run build` (via the optional `ANALYZE` env variable).
Example:
```
ANALYZE=1 NODE_ENV=production node --max_old_space_size=4096 ./node_modules/.bin/webpack
```
Thoughts?

Add webpack-bundle-analyzer

---

app/package.json
app/src/editor/components/Canvas.jsx
app/src/editor/components/Module.jsx
app/src/editor/components/ModuleSearch.jsx
app/src/editor/components/ModuleSidebar.jsx
app/src/editor/components/Port.jsx
app/src/editor/components/TextInput.jsx
app/src/editor/components/Toolbar.jsx
app/src/editor/components/UndoContainer.jsx
app/src/editor/index.jsx
app/src/editor/services.js
app/src/editor/state.js
app/src/editor/tests/UndoContainer.test.jsx
app/src/editor/utils/autosave.js
app/src/shared/components/Toggle/index.jsx
app/src/userpages/modules/canvas/actions.js

* Enables Start/Stop buttons
* Enables historical "speed" settings
* Enables/disables "reset & start" functionality based on canvas "serialised" status.
* Disables editing & undo while canvas is running.
* Adds temporary swapping to historical canvases.
* Adds workaround for serverside `/canvases?adhoc=false` responding with `adhoc` canvases.
* Adds tests around undo/redo functionality.
* Automatically subscribes to streams for running canvas
* Automatically unsubscribes if running canvas ends.
* Automatically reverts to "parent" canvas if a historical canvas is ended.
To Test:
1. Open Any Canvas.
2. Create a new Canvas via the "…" menu  on the left of the canvas.
2. Add a clock & a table module.
2. Change the clock's unit to "hour" ("second" will flood the dev env with too many events …

[PLATFORM-33] Start/stop canvases + start options

---

app/src/shared/components/Search/index.jsx
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/flowtype/common-types.js
app/src/userpages/flowtype/states/dashboard-state.js
app/src/userpages/i18n/en.po
app/src/userpages/modules/canvas/actions.js
app/src/userpages/modules/dashboard/actions.js
app/src/userpages/modules/dashboard/reducer.js
app/src/userpages/modules/dashboard/selectors.js
app/src/userpages/modules/dashboard/services.js
app/src/userpages/tests/modules/dashboard/actions.test.js
app/src/userpages/tests/modules/dashboard/reducer.test.js
app/src/userpages/utils/constants.js

Added search and filtering for dashboard listing. Also made default filters constant since canvases, dashboards and streams will use the same filters.
PS. I modified Search component to do debouncing so we don't have to make debounced versions of the redux actions

[PLATFORM-224] Add search and filtering capabilities to dashboard listing

---

app/src/editor/components/Canvas.jsx
app/src/editor/components/Canvas.pcss
app/src/editor/components/Ports.jsx
app/src/editor/components/Ports.pcss
app/src/editor/state.js

To test:
* Add the `Multiply` module to a canvas
* Note the A & B ports have inputs. These inputs allow setting the initial value.
* Note that unlike params, initial value inputs are not disabled when connected.
Also
* All ports with inputs now have placeholder text.
* Input text is selected when input gets focus

[PLATFORM-170] Input initial value

---

app/src/shared/modules/user/actions.js
app/test/unit/modules/user/actions.test.js

The cause of this issue is that when Stream preview page was added as an actual page, there is a call to `getApiKeys` which will log the user out if it fails. I added a check that the logout only happens if a session already exists.

[PLATFORM-257] View live data while Logged out

---

app/src/editor/components/Canvas.jsx
app/src/editor/components/Status.jsx
app/src/editor/components/Status.pcss
app/src/editor/index.jsx

Shows relative "updated" time in bottom right corner of editor. Updates every ~10s.
It'd be possible to do this relative time setup with `moment` but that's a massive dependency and we should be phasing it out in favour of `date-fns` or `luxon`.

[PLATFORM-189] Show relative canvas updated time.

---

app/src/editor/components/Cables.jsx
app/src/editor/components/Canvas.jsx
app/src/editor/components/Module.jsx
app/src/editor/components/Module.pcss
app/src/editor/components/Ports.jsx
app/src/editor/components/Ports.pcss
app/src/editor/components/Status.jsx
app/src/editor/index.jsx
app/src/editor/state.js
app/src/editor/utils/Dragger.js
app/src/editor/utils/dnd.js

This was a real PITA, but we got there. The primary issues were resolvable with reasonable performance without removing react-dnd by working around some react-dnd perf gotchas. There's still a small delay when you start dragging, but when React is running in production mode, this delay becomes unnoticeable. 
* Dragging modules actually drags the module element, rather than an image of the module. Without this, the dragged module appears translucent, scales weirdly, and captures weird images when things like port options are open. Switching from dragging images to dragging DOM elements in a performant manner is really the primary purpose of this PR.
* Port no longer shows weird preview when being dragged.
* Fixed cable/module flickering after drag/drop.
* Reduced the delay between starting …

[PLATFORM-209] Smooth drag/drop

---

app/src/routes/definitions.json
app/src/shared/modules/user/actions.js
app/src/shared/test/modules/user/actions.test.js
app/src/userpages/components/ProfilePage/ProfileSettings/index.jsx
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/tests/components/ProfilePage/ProfileSettings/profileSettings.test.jsx
app/src/userpages/tests/components/ProfilePage/profilePage.test.jsx

Add saving to user profile top bar button. Saving doesn't actually work because the API endpoint `/profile/update` is outside the `/api/v1` namespace (same problem happens with changing the password). But that should be changed in the backend so left it as it is for now.

[PLATFORM-298] Add saving to profile

---

app/src/shared/web3/web3Poller/web3Poller.js

Prevents repeated web3 poller warnings from appearing. 
i.e. prevents this:
If the same warning would be logged twice in a row, the second one will be ignored.
This allows new warnings to be shown.
Alternatively this could suppress any warning that had already been seen, however this runs the risk of suppressing too much.
Another alternative would be to specifically suppress the repeated "Provider not set or invalid" messages.
Also, perhaps this should only be enabled in development.

Suppress repeat web3 warnings

---

app/src/marketplace/i18n/en.po
app/src/shared/components/Tile/index.jsx
app/src/shared/components/Tile/tile.pcss
app/src/userpages/components/ProductsPage/index.jsx

Small fix for canvas tile menu. I also sneaked in the product tile menu in the user pages Products section which was missing.

[PLATFORM-301] Fix canvas tile menu, add menu to user product listing

---

app/src/editor/index.jsx
app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx

Paid product streams not working because the `authKey` was not sent but the `stream-client`.

[PLATFORM-327] Rollback changes for streamr-client apikey init

---

app/src/marketplace/utils/auth.js
app/src/shared/modules/user/reducer.js
app/src/shared/modules/user/selectors.js
app/src/shared/test/modules/user/selectors.test.js

Not sure where this behaviour change was introduced (???!) but for some reason the app now seems to want to re-authenticate on every page refresh.
This issue is that the `redux-auth-wrapper`'s `authenticatingSelector` does a check for the `user.isFetchingUserData` flag to determine whether authentication is in progress:
https://github.com/streamr-dev/streamr-platform/blob/c9bbd6fed56d486951690a7ad3d1f0bbe613dbab/app/src/marketplace/utils/auth.js#L20-L23
And `pollLogin` calls `getUserData` which sets the `user.isFetchingUserData` flag, however *it doesn't get executed until `onComponentDidMount`*:
https://github.com/streamr-dev/streamr-platform/blob/c9bbd6fed56d486951690a7ad3d1f0bbe613dbab/app/src/marketplace/containers/GlobalInfoWatcher/index.jsx#L57-L70
This occurs *after* the …

Prevent login redirect occurring before auth has been checked

---

app/src/app/index.jsx

Route path fix to allow for base URL matching i.e. canvas/editor and dashboard/editor

Quick fix for Dashboard route

---

app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/components/Ports.pcss

As far as I can tell, there doesn't seem to be any way to toggle "export" for ports in the new designs.
i.e. 
Upcoming work with canvas custom module needs this ability.
This PR adds a port export toggle using the same system for toggling driving input/no repeat:
Once @mattatgit returns perhaps he will have a better idea. Perhaps it was intended as a right click menu.

[PLATFORM-353] Port toggle export

---

app/src/docs/components/ApiPage/Content.mdx
app/src/docs/components/DocsLayout/docsLayout.pcss

Small PR for styling for table usage inside the Docs. ~Ended up with the vanilla reactstrap implementation because we don't need much from it:~
Update: Decided on using the native implementation of table. 
~And, also added the inline highlighting of keywords:~
Update: Decided on using the native implementation of 'KBD' for inline highlighting.
Designs:
https://share.goabstract.com/73496436-3d33-45af-b79d-afc7f696bc30

[PLATFORM-394] Docs Tables

---

app/src/userpages/flowtype/common-types.js
app/src/userpages/modules/canvas/actions.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/utils/filters.js
app/test/unit/utils/filters.test.js

This filters uiChannel streams out of the userpages streams listing page.
Note lots of random streams for UI components:
Note the much smaller list of streams after uiChannel streams are removed:
This is the same listing of streams shown in the old UI:
----
* Now allows pages to define their own default filter parameters. e.g. before every filter query got `adhoc=false` even though it's only relevant to canvas requests.
* Should generally prefer using `undefined` over `null` as `null` prevents application of default value via destructuring or function args or when using utilities like `lodash/defaults`.

[PLATFORM-396] Don't show uiChannel streams in streams listing page

---

app/package-lock.json
app/package.json
app/src/editor/canvas/services.js
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/__snapshots__/services.test.js.snap
app/src/editor/canvas/tests/__snapshots__/state.test.js.snap
app/src/editor/canvas/tests/mocks.js
app/src/editor/canvas/tests/services.test.js
app/src/editor/canvas/tests/state.test.js
app/src/editor/canvas/tests/utils.js
app/src/editor/canvas/tests/variadic.test.js
app/src/editor/dashboard/services.js
app/src/editor/shared/components/Client.jsx
app/src/editor/shared/services.js
app/src/editor/shared/tests/autosave.test.jsx
app/src/editor/shared/utils/autosave.js
app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx
app/src/userpages/components/StreamrClientProvider/index.jsx
app/src/userpages/components/WebComponents/StreamrWidget/index.jsx
app/src/userpages/flowtype/streamr-client-types.js
app/test/test-utils/setupTests.js

* Adds some tests for editor apis.
* Hits locally running server, thus these tests currently won't run in CI.
* Note method for creating throwaway user in `editor/canvas/test/util.js`.
* Added tests for most service calls, but none around module apis since they're not accessed via /api/v1/ and thus don't work with the bearer auth.
* Update: also added some tests around the autosave functionality.
Invoke the api tests with `npm run test-local`
Could possibly look into using something like https://netflix.github.io/pollyjs/ so tests can run in CI.

Editor API tests

---

.travis.yml

Removed unneeded trailing slash on the API url that breaks the API call when formatUrl helper is not used.

[PLATFORM-411] Editor on staging display bug

---

app/src/editor/canvas/components/Canvas.pcss

Fixes both click to deselect PLATFORM-416 & click to close sidebar drawer PLATFORM-417 issues.
Also I cannot reproduce PLATFORM-418: scrollbars on sidebar open but I recall this being an issue in the past. Perhaps @mattatgit is looking at an older version and PLATFORM-418 is already fixed?

[PLATFORM-416] Ensure canvas background is focusable.

---

app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/components/Ports.pcss
app/src/editor/canvas/state.js

[PLATFORM-424] Don't show own module port states when dragging connection

---

app/webpack.config.js

Git information currently missing from 'production' deployments e.g. staging.

Enable git information via streamr.info for prod builds.

---

app/src/shared/i18n/en.po
app/src/shared/utils/web3.js

Small fix that adds a translation to unknown network name when e.g. trying to purchase a product in the wrong network. This comes up in staging where the network name is not part of the predefined `ethereumNetworks` constant.
Before:
After:

[PLATFORM-434] Add name for private network

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ShareDialog.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/editor/dashboard/components/DashboardModuleSearch.jsx
app/src/editor/shared/components/Modal.jsx
app/src/editor/shared/utils/autosave.js

Adds a notification when autosaving fails in editor. Not sure what else we should notify but maybe it'll give some indication that things start failing. Can be tested by blocking the autosave request in console.
I had to refactor the modal logic a bit since it's using the shared `Modal` component and notifications are not shown if a modal is open. Previously, the editor modals were always in the DOM, just hidden which meant they were always "open" internally.

[PLATFORM-109] Editor notification when autosave fails

---

app/src/editor/canvas/components/Cables.jsx
app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/state.test.js

@juhah I checked out your branch and worked on top of it to add a lot more tests around basic canvas state operations.
Also noticed that the disconnection on subcanvas change wasn't happening in the UI, turns out updateCanvas wasn't being called in a few locations so it wasn't sanitising the canvas data. This is fixed with this PR.
One change to note is the canvas state now throws for a lot more cases when it can't find modules/ports. The idea is to try to surface missing module/port issues closer to the source of the problem, rather than waiting for an undefined value to propagate.

Tests for basic canvas operations

---

app/src/editor/canvas/index.jsx

Simply creates a new canvas if user navigates to `/canvas/editor/` without any canvas id.
Also fixes "New Canvas" button in nav dropdown + "Create Canvas" button on userpages canvases view i.e.
Ideally it would use a fake canvas until user the edits something, but we've discussed this in the past and this solution will do for now.

[editor canvas] Create new canvas when canvas url has no id.

---

app/src/marketplace/components/Nav/index.jsx
app/src/shared/components/Nav/NavDropdown/navDropdown.pcss

Prevents page reload when using the current editor nav menu:
This menu needs redoing shortly but this is a quick fix so the menu works more normally today.

Use router links for editor menu

---

app/package-lock.json
app/package.json
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss
app/src/editor/shared/components/RenameInput.pcss
app/src/shared/assets/images/tick.svg
app/src/shared/components/Calendar/calendar.pcss
app/src/shared/components/StatusIcon/index.jsx
app/src/shared/components/StatusIcon/statusIcon.pcss
app/src/shared/components/SvgIcon/index.jsx
app/src/shared/components/Tooltip/index.jsx
app/src/shared/components/Tooltip/tooltip.pcss
app/src/shared/components/WithCalendar/index.jsx
app/stories/shared.stories.jsx

Adds toolbar styling. Not 100% according to design but pretty close 😛 Had some trouble overriding `reactstrap` styles, might have been better just to use normal buttons but the button groups we already there...
Normal state:
Canvas actions:
Run/stop button:
Realtime/historical:

[PLATFORM-431, PLATFORM-412] Toolbar styling & Tooltips

---

app/package.json
app/src/editor/canvas/tests/services.test.js

Possible that the CI flakiness is caused by not waiting long enough for the services to respond.
The `getSessionToken` call in particular seems to take some time when the docker environment has just booted. This PR raises the initial connection wait time from 5 seconds to a minute.

Wait up to a minute to connect to services in test.

---

app/src/editor/shared/components/modules/Chart.jsx
app/src/editor/shared/components/modules/Table.jsx

Fixes `initRequest` calls to be consistent for table & chart modules.
I don't see much behavioural difference with this change but it matches the old UI behaviour.

Chart & Table init requests

---

app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/components/Ports.pcss

* Removes the temporary "EX" option from the hover menu.
* Add orange "exported" port colour (from https://share.goabstract.com/e7a8ad3f-bdbe-4431-acab-44ecd585c227).
* Updated DI/NR colours (both are blue now according to abstract).
* Switches 'toggle export' text between 'enable export' & 'disable export' based on port export state. (as discussed https://share.goabstract.com/dc943ddb-bd93-4260-abf9-c77df13c2acf)

Update indicators for exported ports

---

app/src/editor/shared/components/modules/Table.jsx

e.g. `ListAsTable` will send changes for the same row (note though it doesn't send the edit row command). Current code appends the item so you end up with multiple table rows when there should only be one. This fixes the behaviour so it will update a row if it finds a row with the same id already in the set.

Fix table row update

---

app/src/editor/canvas/components/PortDragger.jsx
app/src/editor/canvas/components/Ports.jsx
app/src/editor/canvas/components/Ports.pcss
app/src/editor/canvas/services.js
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/state.test.js
app/src/editor/canvas/tests/utils.js
app/src/editor/canvas/tests/variadic.test.js

* Reworked the canvas editor tests to use live module definitions.
* Added tests for variadic outputs
* Creates new input/output pairs when something is connected to input of previous pair.
* When linked input is disconnected, linked output is also disconnected.
* Removes spurious pairs from end of ports list, like normal variadics but makes sure to remove both input and output.
* `displayName` of incoming connection's output port is adopted when connecting to a variadic input.
* if variadic input has a `linkedOutput`, same `displayName` is copied to output.
* On disconnection, `displayName`s are reset to use index e.g. `in1`, `out2`, etc.
* Linked variadic outputs are hidden until linked input is connected.
* Appropriate port `longName` is maintained based on port index e.g. `Table.in1`. …

[PLATFORM-450] Linked Variadic Ports

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/services.js
app/src/editor/canvas/state.js
app/src/editor/dashboard/services.js

This allows tests to fetch module categories data, and should fix the CORS issue preventing loading of module categories on staging i.e.
```
Access to XMLHttpRequest at 'https://ee-staging.streamr.com/module/jsonGetModuleTree' from origin 'https://marketplace-staging.streamr.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
This is preventing @mattatgit from properly testing.

Load module data from new api/v1 modules routes.

---

app/src/editor/canvas/components/Canvas.pcss

100% width and 100% height + bottom and right margins make the box exceed the available space and cause scrollbars.
@timoxley, let me know if there's anything I missed or should know about those margins I've thrown away. We may want to address it differently.

[PLATFORM-488] Prevent scrollbars around the canvas box

---

app/src/editor/shared/components/modules/Button.jsx
app/src/editor/shared/components/modules/Canvas.jsx
app/src/editor/shared/components/modules/ExportCSV.jsx
app/src/editor/shared/components/modules/Label.jsx
app/src/editor/shared/components/modules/Scheduler.jsx
app/src/editor/shared/components/modules/Switcher.jsx
app/src/editor/shared/components/modules/Table.jsx
app/src/editor/shared/components/modules/TextField.jsx

Currently a historical canvas run with a 1second clock -> table will totally freeze the current browser tab, due to too many queued renders inside the table component.
This PR throttles existing component subscription message handlers, batching updates where appropriate (e.g. table).
To test: connect a clock to a table, run in historical mode. It should display some values then revert back to old canvas (this reverting behaviour is a known, unrelated issue). Previously, the entire tab would lock up.

Throttle subscription message handlers appropriately.

---

app/travis_scripts/build-docker-env.sh
app/travis_scripts/utils.sh

CI builds are frequently getting stuck waiting for either data-api or e&e (less common) to come up and end up waiting a full hour before travis kills the script and reports failure. Restarting a stuck build often makes it magically work. This is very annoying to say the least. Despite data-api being restarted after e&e is up, it still frequently doesn't start properly 😡. It probably got restarted too soon? Who knows.
**This PR changes the build script to not wait forever, instead performs a number of retries before deciding it's not going to happen.**
**This PR also adjusts the logic to try connect to data-api for a short while, if it doesn't come up it will try restarting it again.** 
This doesn't really fix whatever the underlying problem is with reliably starting `data-api` but this PR …

Restart data-api a second time if not up after first restart. Limit service check retries. 

---

app/src/editor/canvas/components/DragDropContext.jsx
app/src/editor/canvas/components/ModuleDragger.jsx
app/src/editor/canvas/state.js

Currently clicking on a module can trigger the start of the module drag-drop process, which is fine except for the fact that even if you don't actually move the module (i.e. just clicked on it), it registers a "move module" event in the undo history. This leads to undo/redo sometimes seemingly requiring multiple attempt to get it activate. Undo/redo is actually working but it's just undoing/redoing pointless "move module exactly where it was already" actions.
This PR bails out of creating the undo entry if there was no movement in the drag/drop.

Avoid creating undo entry for drag drop events with no movement.

---

app/package.json

In case you have your `NODE_ENV` set to something e.g. `development` by default.

Force NODE_ENV=test for npm test.

---

app/src/editor/shared/components/Map/Map.jsx

Fixes Map to have default coordinate reference system which was overwritten in https://github.com/streamr-dev/streamr-platform/pull/300.
Also we now use Carto Voyager tilemap by default as per Matt's request.

[PLATFORM-476] Map fixes

---

app/src/editor/canvas/components/CanvasSearch.pcss
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss
app/src/shared/components/SvgIcon/index.jsx
app/src/shared/components/WithCalendar/index.jsx
app/src/shared/components/WithCalendar/withCalendar.pcss

Address design feedback for Editor toolbar, fixes:

Editor Toolbar design feedback

---

app/src/editor/canvas/services.js
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/__snapshots__/services.test.js.snap
app/src/editor/canvas/tests/__snapshots__/state.test.js.snap
app/src/editor/canvas/tests/services.test.js

e.g. `Untitled Canvas` becomes `Untitled Canvas (2)` if you already have an `Untitled Canvas`
To test, try duplicate an existing canvas.

[PLATFORM-174] Soft-deduplicate canvas names on canvas creation.

---

.travis.yml
app/travis_scripts/build-docker-env.sh

* Enables retrying CI test runs.
* Also fixes logging step (syntax works in zsh but not bash) and cleans up.

Add travis_retry to CI test runs

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss

The start/run button text should switch between "RUN" & "START" based on whether user has chosen realtime or historical mode.
See mocks:
* https://share.goabstract.com/2830d496-15f1-4fce-8ffe-8bd7b1afafa8
* https://share.goabstract.com/c1cf1d18-3fcf-4c8a-85a9-73acfcb355b4
Also prevents toolbar items from shifting 1px when toggling between realtime & historical modes on a slightly width-constrained screen.

Toolbar start/run button text

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleDragger.jsx
app/src/editor/dashboard/components/Dashboard.jsx
app/src/editor/shared/components/ModuleHeader/index.jsx
app/src/editor/shared/components/ModuleHeader/moduleHeader.pcss

Modules currently can't be dragged to reposition them on the dashboard. This fixes that by reading dragHandle consistently from the shared module styles. 
Logged by @mattatgit in https://streamr.atlassian.net/browse/PLATFORM-519

Fix draggability for dashboard modules.

---

app/src/editor/canvas/index.jsx

Currently this doesn't work for http module's VERB select. The module that comes back doesn't have layout information, etc.
@juhah maybe you can recall better than I but I don't think the Stream module needs to be special-cased, nor does it need to be conservative about what it sends as the config in `getModule`. Maybe you can break it?

Fix load definition to always pass existing module config.

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/adhoc.test.js
app/src/editor/canvas/tests/services.test.js

This "fixes" some difficult issues with historical runs.
1. Refreshing the page while viewing a historical run will return to that historical run.
2. Historical runs now need to be "exited" after they stop.
3. "Exiting" will clear the UI data and switch user back to editing the original canvas. 
* Redirecting to the historical canvas prevents historical runs from being "lost", and also prevents background canvas edits.
* Exit state means historical visualisation data will not disappear until user commands it so.
* The exit state exists so we don't have to do any trickery to "pretend" the adhoc historical canvas is actually the original canvas. i.e. once user hits exit, there's a clean break between the two canvases.
* This also reinforces the concept of realtime/historical runs being …

[PLATFORM-459] Historical Runs

---

app/src/index.html

You may have noticed the favicon goes missing after the page loads. This seems to fix that. A bunch of other tags in the header were being (unintentionally?) removed as well. It's possible there are unintended side effects of now *not* removing these header items.

Prevent react-helmet from clobbering header content (fixes favicon).

---

app/test/unit/analytics.test.js

Converts sinon/assert tests in #347 to Jest.
@juhah I thought we decided to standardise on using `jest`'s built-ins instead of `sinon`+`assert`?

Convert analytics tests to jest.

---

app/package-lock.json
app/package.json
app/src/editor/shared/components/Map/Map.jsx
app/src/editor/shared/components/ModuleUI.jsx
app/src/editor/shared/components/modules/Heatmap.jsx
app/src/editor/shared/components/modules/Map.jsx

Added Heatmap module with help of `react-leaflet-heatmap-layer`. The new heatmap library does not have the same parameters as the component in the old editor had, so most of the module parameters actually do nothing.
The heatmap that gets drawn looks a bit different with this version and the old editor. Could not spot where the difference comes from but might be related to the parameters or the fade-in/out algorithm. IMO the new heatmap looks a lot better :)
Also this version does not implement fade-in/out. I have created https://streamr.atlassian.net/browse/PLATFORM-513 so that we can implement it later if actually needed.

[PLATFORM-245] Heatmap module

---

app/src/editor/canvas/services.js
app/src/editor/canvas/tests/services.test.js
app/src/editor/dashboard/services.js
app/src/editor/shared/tests/uniqueName.test.js
app/src/editor/shared/utils/uniqueName.js

See tests for usage.
1. No more parens around index.
2. "Duplicate" now adds "Copy" to file name.
3. Creating new increases index.
4. Factored into reusable utility
5. Added deduping to dashboard name.
Doesn't dedupe when user creates custom name. Deferring for now: https://streamr.atlassian.net/browse/PLATFORM-549

[PLATFORM-524] Update deduping naming scheme

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/RunController.jsx
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/hooks/useCanvasNotifications.jsx
app/src/editor/canvas/hooks/useCanvasStateChangeEffect.js
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/adhoc.test.js
app/src/editor/dashboard/index.jsx
app/src/editor/shared/components/Client.jsx
app/src/editor/shared/components/ModuleSubscription.jsx
app/src/editor/shared/components/Subscription.jsx
app/src/editor/shared/components/SubscriptionStatus.jsx
app/src/editor/shared/tests/Client.test.jsx
app/src/editor/shared/tests/Subscription.test.jsx
app/src/editor/shared/utils/autosave.js

* Subscriptions register themselves with SubscriptionController.
* RunController keeps track of current pending/starting states and exposes start/stop/exit api.
* On starting a historical canvas, RunController will wait for registered subscriptions before issuing the start command.
To test: start & stop realtime & historical canvases. Data should flow.

[PLATFORM-472] Subscribe to streams before starting historical canvases

---

app/src/editor/shared/tests/Subscription.test.jsx

I have a feeling the environment isn't coming up fully functional and that's the reason for the failures. It seems to connect and whatnot but published messages never seem to appear in the stream, which is why the subscription tests are failing. The tests work in my local environment. 
Will merge if/when CI goes green.

Temporarily skip Subscription tests for CI.

---

app/src/userpages/components/Layout/index.jsx

Added an always on scrollbar to the core pages to stop the jumping from one tab to another when one tab has a scrollbar and one does not.

[PLATFORM-517] Stop horizontal jumping on core pages bug

---

app/package.json
app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss

Made the search window resizable and made search results names & descriptions truncate instead of wrapping.
I left the module tree unchanged so it will still wrap when module name or category is too long. I thought that it's better this way because when user uses the tree to browse modules, he or she is not knowing exactly what to search so it's good that category and name are shown fully.

[PLATFORM-522] Module search scalability

---

app/src/marketplace/components/ProductTile/productTile.pcss
app/src/shared/assets/stylesheets/variables.css
app/src/shared/components/Tile/tile.pcss
app/src/userpages/components/CanvasPage/List/canvasList.pcss
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/components/ProductsPage/products.pcss
app/src/userpages/components/PurchasesPage/purchases.pcss

Implementing this:
https://app.goabstract.com/projects/667a5970-5f1f-11e9-bf62-2556403415af/branches/e81395ea-cee8-4dc8-95f8-badab055aa60/commits/995b11e9015108f9e9b274b70cbdb10a880c030f/files/632368C4-4D71-4548-97F3-468F89D29073/layers/46BFE6D0-4488-4263-8DD8-85DBA3F614DF?mode=design
***From Jira***
One problem is that current designs for Core > Products uses a badge to show drafts & published products, and this design prevented us showing a friendly "Updated" or "Created" date, making it hard for users to know which drafts or products they had created. Proposed update also unifies display with other tiles (eg canvases) where green is active, current, while grey is used for non-active items.
So changes are: remove badges, add Created / Updated friendly date, show Drafts in #323232 and …

[PLATFORM-518] Implement consistent tile & list styles across Core app

---

app/src/editor/canvas/components/Cables.jsx
app/src/editor/canvas/components/Canvas.pcss
app/src/editor/canvas/components/Preview.jsx
app/src/editor/canvas/components/Preview.pcss
app/src/editor/canvas/state.js
app/src/editor/dashboard/components/Dashboard.jsx
app/src/editor/dashboard/components/Preview.jsx
app/src/shared/components/Tile/index.jsx
app/src/userpages/components/CanvasPage/List/canvasList.pcss
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx

* Maintains a 318/200 ratio (from mocks).
* Small canvases are drawn at least "1680px" wide, this ensures small canvases don't display as a few gigantic modules.
* Large canvases scale module "details" down as appropriate, maintaining aspect ratio.
* Roughly "simulates" `react-grid-layout` rendering.
----
No custom UI for individual modules, let's do that in another pass, it's made more complicated for dashboards as we don't know the module `id` upfront (i.e. it's type e.g. "Table", etc), we only know its `hash` (the "real" unique id for a module on a canvas).

[PLATFORM-480] Generated Canvas & Dashboard previews

---

app/webpack.config.js

I'm not sure if anyone else has been having this same problem but for me webpack seems to be running out of memory with increasing frequency. This is annoying.
Some quick googling turned up this: https://github.com/webpack/webpack/issues/6929#issuecomment-447118252
```js
// file: webpack.config.js
optimization: {
splitChunks: {
chunks: 'all',
},
},
```
This seems to work? I've been running builds with this setting on for the last two days and I haven't seen an out of memory error since. 🤷‍♀
Other consequence of this change is that we're now serving the app in (at least) two bundles, one vendor bundle containing everything in `node_modules`, and another bundle containing everything else. Have seen no problems as a result of this, everything appears to just work. These bundles are loaded in …

"Fix" webpack out of memory issues

---

app/src/shared/components/EditableText/editableText.pcss
app/src/shared/components/EditableText/index.jsx

Very quick fix for the cursor situation. `EditableText` in idle state comes with the default one. I also disabled spell checking and autocomplete in that component.

[PLATFORM-533] Module header cursors

---

app/src/editor/canvas/state.js
app/src/editor/canvas/tests/services.test.js

The client-generated module hash was larger than the valid Java `Integer` range supported by `hash` on the server, so the `hash` that comes back from the server was different than the `hash` that the client sent, which causes the subscriptions to disconnect and reconnect due to the container thinking the original module (+ subscription) had been removed and a new module added.
To test: 
1. Create a new Canvas
2. Create a test stream + add a numeric "message" field (or whatever)
3. Grab your API key and created stream id.
4. Publish a message to the stream using cli-tools:
```
npm install -g @streamr/cli-tools
echo -n '{"message": 1}' | publish-to-stream-dev $STREAM_ID $API_KEY
```
Message should appear.
Previously the message would be lost.

[PLATFORM-557] Ensure generated module hash is within valid range for server.

---

app/src/editor/canvas/components/ModuleSearch.jsx

I changed the minimising behaviour so that it expands if minimised and a search text is entered (instead of disabling). I also made the box smaller (max height) by default to what it is in the designs (352px).

[PLATFORM-504] Module Search Panel minimising behavior

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/canvas/index.jsx
app/src/editor/canvas/state.js
app/src/shared/components/SvgIcon/index.jsx

Modules can be now dragged and dropped from module search into the canvas. Or actually that is the only way to add modules now. Also the search window now stays open until you close it so you can easily build the canvas.
Position of the module is calculated from the drop position.

[PLATFORM-483] Insert modules with drag and drop

---

app/src/editor/canvas/components/ModuleSearch.pcss

Apparently this only appears if devtools is closed? ??

Adjust module drag image layout to fix weird padding.

---

app/src/shared/components/EditableText/index.jsx

Fixes console log warnings when focusing module input value or canvas name.

Fix console warning when focusing EditableText

---

app/src/editor/canvas/components/Preview.jsx

Wraps a try/catch around the code which does any canvas "validation". Not totally robust, ideally we could wrap the entire component, but I think there's some issues with that + hooks due to no current equivalent of `componentDidCatch` or `getDerivedStateFromError` but "they will be added soon". This should cover us for now.

[PLATFORM-582] Canvas Preview Errors

---

app/src/analytics.js

Prevents LogRocket from sending username and password from login request. Can be tested locally by adding the slug to `.env` and checking the result in LogRocket:
`LOGROCKET_SLUG=et0uhu/streamr-frontend-local`

[PLATFORM-587] Hide sensitive data from LogRocket

---

app/src/editor/dashboard/index.jsx

Quick fix since this a blocker. Should be refactored to use similar loading as canvas.

[PLATFORM-572] Create new dashboard editor is not opening

---

app/src/shared/components/Spinner/spinner.pcss

Fixes spinner size in dialogs.

[PLATFORM-610] Dialog wait state spinner size

---

app/package-lock.json
app/package.json
app/src/editor/canvas/components/CanvasSearch.jsx
app/src/editor/canvas/components/CanvasSearch.pcss
app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/dashboard/components/DashboardModuleSearch.jsx
app/src/editor/dashboard/components/DashboardModuleSearch.pcss
app/src/editor/shared/components/SearchPanel/SearchPanel.pcss
app/src/editor/shared/components/SearchPanel/SearchPanel.stories.jsx
app/src/editor/shared/components/SearchPanel/index.jsx
app/src/editor/shared/components/Sidebar/sidebar.pcss
app/src/editor/shared/tests/ModuleSearch.test.jsx

* Factors out shared UI/behaviour from canvas' `ModuleSearch` into editor/shared `SearchPanel`
* (re)implements module search for both dashboard & canvas on top of new `SearchPanel`
* Also reimplements canvas search.
* Fixes a bunch of little issues with module search.
Need to get this in asap for @mattatgit's demo.
Known issue: Dashboard module search draggable bounds have an incorrect vertical offset.
~~edit: uh, there is a problem with canvas open menu, hang on.~~ Fixed.

[PLATFORM-519] Dashboard module search

---

app/src/userpages/components/Avatar/NameAndEmail/nameAndEmail.pcss

[PLATFORM-608] Remove letterspacing from username / email

---

app/package-lock.json
app/package.json
app/src/auth/utils/getSessionToken.js

`StreamrClient` does not give us response bodies, statuses, etc. on failure. We need them so we're waiting for streamr-dev/streamr-client-javascript/pull/60. This here is just a preparation.

[PLATFORM-499] Human-friendly login failure messages

---

app/src/editor/canvas/components/Ports/Value/Select/index.jsx

~I've used solution suggested by @juhah here!~ It fixes preselecting the valueless option that acts as a placeholder.

[PLATFORM-585][PLATFORM-538] Fix select's (port value) placeholder

---

app/src/app/index.jsx

These are the only routes that need it, as well as location's `search` is the only thing needing forwarding. `react-router` doesn't do it OOTB.

[PLATFORM-630] Forward `search` in auth redirections

---

app/package-lock.json
app/package.json
app/webpack.config.js

I noticed we're serving a whopping 722KB png as our 404: https://beta.streamr.com/images/404_blocks@2x.png
Rather than hand-optimise this one image I dropped in [imagemin-webpack-plugin](https://github.com/Klathmon/imagemin-webpack-plugin#readme) to do it for us automatically.
This optimises that ~722KB image to ~94KB (-86%). Still large and could probably be optimised further but this is a "free" 86% reduction and I can't tell the difference between the two (left optimised, right original):
This optimises most/all other images on the site, some other examples:
* `404_blocks.png`: 201KB -> 25KB (-87%)
* `app_crashed@2x.png`: 168KB -> 31KB (-81%)
* `empty_state_icon@2x.png`: 108KB -> 9.6KB (-91%)
* etc
It is possible this optimisation degrades other images too much, I didn't see anything …

Automatically Optimise Image Assets 

---

app/webpack.config.js

* Injects appropriate hash into asset file names for production builds. Used `contenthash` where possible, which should enable some degree of long-term caching, though we'll get more benefit from that by splitting the bundle into more chunks.
* Standardises on :8 length hashes.

[PLATFORM-642] Asset Filename Hashes

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/shared/components/ConfirmDialog/confirmDialog.pcss
app/src/shared/components/ConfirmDialog/index.jsx
app/src/shared/components/Dialog/index.jsx
app/src/shared/i18n/en.po
app/src/shared/utils/confirm.jsx
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/i18n/en.po

Adds an option confirm dialog to never show it again which is stored in local storage. There's no way to reset it again except by removing the local storage value.
- Uses shared `Checkbox` component which is not styled as in the mock
- Added confirm modal also to canvas delete
- Removed stream/canvas name from modal title

[PLATFORM-516] Permanently delete item modal improvements

---

app/src/userpages/components/ShareDialog/shareDialog.pcss
app/src/userpages/i18n/en.po

Update share dialog options:
> Option 1 old: Anyone you've invited
> Option 1 new: Private — only people you’ve invited
> Option 2 old: Anyone with the link and anyone you invited 
> Option 2 new: Public — viewable by anyone with the link or via the API

[PLATFORM-654] Share dialog texts

---

app/src/editor/shared/components/Map/Map.jsx
app/src/editor/shared/components/Map/Map.pcss

This small update sets min/default sizes for all Map module types to match the design. This includes:
- Map Geo
- Map Image
- Heatmap
And anything else that uses `Map` component. Preview:
cc @mattatgit @hpihkala 
_(Thank gods I built the resize constraint mechanism this way, yay!)_ 💃

[PLATFORM-648] Larger Map modules

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss

See https://streamr.atlassian.net/browse/PLATFORM-669
Disables the disabling of the "Reset & Start" menu item, since it seems harmless to add even if current canvas is not serialized.
To test: open canvas start button menu in realtime mode, reset and start should always be clickable whether "save state" is enabled or if the canvas has previously run with "save state" enabled i.e. canvas has `serialized: true` flag set

[PLATFORM-669] Allow 'reset and start' to start canvas even if canvas not serialized

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/search.test.js

Modules starting with a search term now sort before other modules, but after exact matches.
See ticket for detail: https://streamr.atlassian.net/browse/PLATFORM-650
We should migrate to some sort of more sophisticated search scoring algorithm at some point. I played around with https://fusejs.io/ for this PR, but I couldn't seem to get it to guarantee exact matches would sort before matches that start with a term e.g. searching for "Count" would sort "Count By Key" before "Count". Gave up and implemented a naive solution and here we are.

[PLATFORM-650] Search Priority

---

app/src/editor/canvas/components/KeyboardShortcutsSidebar.jsx

Hides all the shortcuts that aren't currently implemented (i.e. most of them)
Should probably just delete these but I've hidden them with a vague hope that it's less copy/pasting later when the shortcuts actually get implemented.

[PLATFORM-573] Hide unimplemented shortcuts.

---

app/src/app/index.jsx
app/src/marketplace/utils/auth.js
app/src/shared/components/MobileNav/index.jsx
app/src/shared/components/Nav/index.jsx
app/src/shared/modules/user/reducer.js
app/src/shared/test/modules/user/reducer.test.js

I make `/u` the new default and remove `redirect` param from login routes if its value is `/`. Note that you can still tell it to take you to `/` after login. You'd have to do it by hand tho.

[PLATFORM-631] Make `/u` the new default post-login location

---

app/src/shared/components/ConfigureAnchorOffset/index.jsx
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx
app/src/userpages/components/TOCPage/index.jsx

There were 2 bugs. This PR solves one of them.
1. `react-scrollable-anchor` removes the hash using `history.replaceState`. It doesn't trigger location change via `react-router`. It also doesn't trigger `hashchanged` event which means when you scroll to the top of the page (which removes the hash) `TOCPage` highlights an item with the last known id.
2. Because of the floating `Save & exit` toolbar the offsets were calculated incorrectly for our case.
I fixed "2". Still looking into "1".

[PLATFORM-636] ToC hightlighting doesn't follow scroll properly

---

app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.jsx

Updates the code editor's handling of `moduleErrors`. More to do to get proper flagging/handling of canvas.moduleErrors but the original ticket is about fixing existing moduleErrors usage.
Builds on top of #427, but not setting that as base yet so we get a PR deployment.
Relevant commit in 2e894c2
To test:
1. *make sure you're using up-to-date engine and editor docker environment.*
2. add java module
3. edit code
4. add syntax error
5. apply
6. see appropriate error message in code editor

[PLATFORM-629] Update moduleErrors handling

---

app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/CanvasController/useCanvasCreateCallback.jsx
app/src/editor/canvas/components/CanvasController/useCanvasLoadCallback.js
app/src/editor/dashboard/index.jsx

Currently if you try access a canvas or dashboard that doesn't exist, it will keep re-trying to access it forever, essentially starting a DOS attack on the server. It's a bad bug that's easily stumbled upon.
This PR is a quick fix that simply redirects to `/404` whenever loading a canvas or dashboard fails for whatever reason.
Really should use inline, context-aware 404 "pages" for canvas and dashboards, but 404/non-200 handling needs some refactoring as mentioned in https://streamr.atlassian.net/browse/PLATFORM-628

[PLATFORM-486] Redirect to /404 on not found dashboard/canvas.

---

app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.jsx
app/src/editor/canvas/components/CodeEditor/index.jsx
app/src/editor/canvas/components/Module.pcss
app/src/editor/canvas/index.jsx
app/src/editor/shared/components/modules/Comment.pcss
app/src/editor/shared/components/modules/Custom.jsx

* Currently the code prop is only copied to state on mount. If a new prop code arrives, e.g. after sending or via canvas undo/redo, that update is ignored. Fixed this so it only reads local state until "apply" step is complete, then it'll read from props until an `onChange` happens.
* if you close the editor and open it again before the "apply" is complete, it'll show a flash of the old content stored in the canvas. Fixed it so that it updates the canvas immediately when you hit "apply" so it'll show latest content on subsequent open/close.
* Prevented edits while apply is pending, prevents at least one scenario where the shown code gets out of sync with what's saved.
**update**: Also set it up to work like our other text inputs:
* Persists content to canvas on blur, this should prevent …

[PLATFORM-664] Fix code editor state/async issues

---

app/src/editor/canvas/components/Cables.jsx
app/src/editor/canvas/components/DragDropContext.jsx

Quick fix I did a week or so back but didn't get around to pushing.
Not critical but noticeably improves module & cable drag/drop perf in the editor. 
Fix was to re-render cables only when a drag occurs, rather than on every animation frame.
To test: 
1. Drag a module/cable around on whatever branch you are currently on.
2. Note it's a bit choppy, especially compared to dragging the module search.
3. Check out this branch. 
4. Drag module/cable around. 
5. Notice dragging is now a lot smoother.

Improve editor drag/drop perf

---

app/src/editor/canvas/state.js

Basically, when this sees an initialValue set to an erroneous `{}` instead of `null`, this sets the `initialValue` back to `null`. Possible the underlying bug in CORE-1718 has other victims, we can work around them as they are discovered.
See https://streamr.atlassian.net/browse/CORE-1718

Add workaround for CORE-1718

---

app/src/editor/shared/components/Sidebar/Header.jsx
app/src/editor/shared/components/Sidebar/sidebar.pcss

Automatically picks up the branch name & commit hash from git. It's currently baked in by webpack at build time so you'll need to restart webpack to see this change in a local branch. Should probably fix it eventually so webpack updates these vars each build but this is good enough for now.
See https://streamr.atlassian.net/browse/PLATFORM-691 for detail.
----
Applying these changes on top of the `beta` branch would look like this (screenshot from cherry-picked commit and rebuilt beta branch):
And on a PR branch: 
Note it auto-splits branch and hash onto multiple lines, but this shouldn't ever need to happen for stuff end users see as those branch names aren't so long.
Hides the commit hash & branch name for the eventual deployment on `master`. Could drop the commit hash entirely if it's …

[PLATFORM-691] Add branch name & commit into sidebar version header.

---

app/src/marketplace/components/StreamPreviewPage/InspectorSidebar/index.jsx
app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx

Datapoint schema changed, needed an update on the frontend.
You can use this script to test:
```
const StreamrClient = require('streamr-client')
var API_KEY = 'tester2-api-key'
var client = new StreamrClient({
url: 'ws://localhost:8890/api/v1/ws',
restUrl: 'http://localhost/streamr-core/api/v1',
auth: {
apiKey: API_KEY,
},
})
async function pushToStream() {
const stream = await client.getOrCreateStream({
id: 'O-gSWcgiRCyStUPuOTaYtQ',
})
await client.publish(stream.id, {
temperature: 25.4,
humidity: 10,
happy: true
})
setTimeout(async () => {
const fetchedStream = await client.getStream(stream.id)
console.log(fetchedStream.config.fields)
}, 2000)    
}
pushToStream()
```
Should see the timestamps appear:

[PLATFORM-633] Show timestamp column in live stream preview

---

app/src/editor/shared/components/Sidebar/Header.jsx

Temporary workaround for git branch & tag information missing for beta builds.

Hardcode version & 'beta' in sidebar

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/Module.pcss
app/src/editor/i18n/en.po

When canvas modules crash, there's currently no way to remove them. This fixes that by rendering the error message as a stub module that can be selected and deleted.
Idea is that this is a response to errors like https://github.com/streamr-dev/streamr-platform/pull/444 
Mock: 
https://app.goabstract.com/projects/667a5970-5f1f-11e9-bf62-2556403415af/branches/e81395ea-cee8-4dc8-95f8-badab055aa60/commits/bc9c29c3fbd56c88266ec01cf9a22634702d2cfe/files/632368C4-4D71-4548-97F3-468F89D29073/layers/0A6DD9FA-8B20-4503-BC11-03793EECCEB3?mode=build&selected=1488291044-FDE65107-D110-4521-8F6A-9D46A79C021B
Mild deviation from mock, with approval from matt: exception message rendered as monospace, exception message area is scrollable.
If you add a `throw new Error('oops')` into …

Module exception handling

---

app/src/editor/canvas/components/CanvasController/useCanvasLoadCallback.js
app/src/editor/dashboard/index.jsx

Was missing `return` statements after error redirect.

Prevent "cannot read id on undefined" exception on bad canvas/dasboard load

---

app/src/editor/canvas/hooks/useCanvasNotifications.jsx
app/src/editor/canvas/index.jsx
app/src/shared/components/Notifications/BasicNotification/basic.pcss
app/src/shared/components/Notifications/BasicNotification/index.jsx
app/src/shared/utils/constants.js

Shows canvas notifications any time there's a "module warning" or "notification" event on the canvas main uiChannel.
To test: make a canvas something like this, start then stop:
I haven't yet figured out (or even looked very hard TBH) a way to trigger "notification" type events.
See https://streamr.atlassian.net/browse/PLATFORM-662 for more info. I added a new comment regarding the hopelessness of our situation.

[PLATFORM-662] Show module warning notifications

---

app/src/links.js
app/src/marketplace/components/Footer/index.jsx
app/src/routes/definitions.json

Other links seem to work just fine. I only re-linked "Try the Editor". It points to the actual editor now.

[PLATFORM-704]  Link “Try the Editor” in the footer to the Editor

---

app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx
app/src/marketplace/components/StreamPreviewPage/index.jsx
app/src/marketplace/i18n/en.po
app/src/userpages/components/StreamPage/Show/PreviewView/index.jsx
app/src/userpages/components/StreamPage/Show/PreviewView/previewView.pcss
app/src/userpages/flowtype/streamr-client-types.js

No design for this but this adds a bit more feedback for the user for the Stream Preview inside the Stream Details page and in the product 'view live data' page. 
Also fixed the resend. The old app actually did the resend, what changed is the StreamrClient resend spec.

[PLATFORM-707] Stream Preview Fix

---

app/src/editor/canvas/state.js
app/src/editor/canvas/tests/canvas.test.js
app/src/editor/canvas/tests/connection.test.js
app/src/editor/canvas/tests/services.test.js
app/src/editor/canvas/tests/state.test.js
app/src/editor/canvas/tests/utils.js
app/src/editor/canvas/tests/variadic.test.js

Fixes an issue preventing a production canvas from working. 
See: https://streamr.atlassian.net/browse/PLATFORM-758
Production canvas in question rendering locally with the fixes in this PR:
To test: 
1. Create a new canvas (canvas 1)
2. Add the PassThrough module
3. Export the input on the PassThrough (bonus: note it adds a new placeholder input)
4. Create another new canvas.
5. Add canvas module.
6. Select canvas 1 as subcanvas. 
7. Note it doesn't break. 
Current `development` breaks at step 7 with same error as reported in JIRA ticket.
Alternatively you could start the app pointed at the production endpoints:
```
STREAMR_API_URL=https://www.streamr.com/api/v1
STREAMR_WS_URL=wss://www.streamr.com/api/v1/ws
STREAMR_URL=https://www.streamr.com
```
And test that the production canvas: …

[PLATFORM-758] Don't perform variadic handling on subcanvases

---

.travis.yml

sentry-release script didn't run in production, I think this will fix it.

Adding full path to sentry-release script

---

app/src/analytics.js
app/src/shared/utils/diagnostics.js
app/webpack.config.js

According to https://docs.sentry.io/platforms/javascript/react/:
> You should init the Sentry browser SDK as soon as possible during your application load up, before initializing React
This PR initialises the analytics before doing anything else except loading babel-polyfill due to: 
https://github.com/streamr-dev/streamr-platform/blob/development/app/webpack.config.js#L43

Init analytics before doing anything else.

---

app/src/userpages/components/CanvasPage/List/NoCanvases/index.jsx
app/src/userpages/components/DashboardPage/List/NoDashboards/index.jsx
app/src/userpages/components/ProductsPage/NoProducts/index.jsx
app/src/userpages/components/StreamPage/List/NoStreams/index.jsx
app/src/userpages/i18n/en.po

Currently empty state views for the userpages are showing text `Click the button above to create one` even though on mobile we hide the `Create` button. This PR fixes that by using media query and showing a different text: `Use the desktop app to make one`.

[PLATFORM-719] Add correct texts for mobile empty states in the userpages

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/shared/components/ModuleHeader/index.jsx
app/src/editor/shared/components/ModuleHeader/moduleHeader.pcss
app/src/editor/shared/components/ModuleHeaderButton/index.jsx
app/src/editor/shared/components/ModuleHeaderButton/moduleHeaderButton.pcss

A couple of things happen here.
- Tweaked the icons. They're 24x24 again, and are custom for the header – I re-exported them. I'm not sure if I'm a fan of the one-for-all `SvgIcon` solution anymore. 😕 
- Buttons are no longer `40x40` – didn't work for multiple buttons. Button section is `n • 24px` wide and `24px` high, plus the section is surrounded with `padding: 8px`.
Preview

[PLATFORM-735] Module's hamburger visibility

---

app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/shared/components/Onboarding/index.jsx
app/src/shared/components/Onboarding/onboarding.pcss
app/src/shared/hooks/useGlobalEventWithin.js
app/src/shared/hooks/useKeyDown.js

It had to be this way. 😢 My js-less component lost its way and it's got a state now.
Cheer up tho! It's not all that bad! 🎉 
I did manage to extract some of that new funcitonality and created 2 new hooks!
1. `useGlobalEventWithin(string, Ref<Element>, (boolean) => void, ?string)` – allows you to trigger a `(boolean) => void` callback when a given ~~error~~ event happens. The callback has 1 argument which indicates whether the event happened inside a given element or outside of it.
2. `useKeyDown({ [string]: () => void })` – sets up a global `keydown` listener for given keys. You give it an object of key bindings e.g. `{ Escape: () => {} }` and it does the rest.
These are all secondary changes. The main issue – Onboarding not working on mobile – has been resolved with the help of them …

[PLATFORM-720] Fix Onboarding menu on mobile

---

app/src/editor/canvas/components/CanvasController/useUpdatedTime.js
app/src/editor/canvas/index.jsx
app/src/editor/dashboard/index.jsx

See https://streamr.atlassian.net/browse/PLATFORM-718
Autosave wasn't properly cleaned up after deleting a dashboard or canvas, specifically, it tries to autosave just before unmounting the canvas/dashboard, even if it's unmounting because the canvas/dashboard was deleted.
To test:
1. Create a Canvas/Dashboard
2. Open Dev Console
3. Delete the Canvas/Dashboard
Note that it:
* redirects back to the canvases/dashboards page
* canvas/dashboard is gone, and
* there's no 404 errors in the console
I want to get the autosave out of `canvas/index.jsx` and into hooks so it can be tested in isolation but when I started refactoring it out there was a bit too much so I cut my losses and present this PR with a minor piece of transitional refactoring.

[PLATFORM-718] No autosave on unmount after deleting a dashboard or canvas

---

app/src/analytics.js
app/src/editor/canvas/services.js
app/src/editor/canvas/tests/adhoc.test.js
app/src/editor/canvas/tests/utils.js

Currently the app will continually redirect to a missing historical canvas if the historical canvas ended without unlinking itself from the parent (e.g. user closed tab).
https://streamr.atlassian.net/browse/PLATFORM-791
https://streamr-team.slack.com/archives/G80NM66KS/p1559016138010200
Now it unlinks & loads the original canvas if there's any problem loading the historical canvas.
Hard to test manually, but I put automated tests around it. basically you need to start a historical canvas, delete the historical canvas (not the original) before the app knows the canvas has stopped and to unlink, then try reloading the original canvas, it shouldn't 404.

[PLATFORM-791] Fix canvas 404'ing when historical canvas gone away

---

app/src/userpages/modules/userPageStreams/actions.js

Error handling that just *works*.
If you want to test, it's the `Autodetect fields` in the Stream Edit page

[PLATFORM-778] Detect fields endpoint fix

---

app/src/analytics.js

This may resolve the issue where some errors are not being logged in production, when the same error is are being logged successfully in other environments.

Whitelist streamr urls for Sentry.

---

app/package-lock.json
app/package.json
app/src/editor/shared/components/modules/ExportCSV.jsx
app/src/routes/definitions.json

With newest e&e, the `/canvas/downloadCsv` endpoint is now under `/api/v1/` so we'll need these changes for download to work.
We need to use https://github.com/eligrey/FileSaver.js/ for saving the file because authentication is needed on the endpoint and therefore we cannot use a simple link.

[PLATFORM-747] Fix ExportCSV module to use new API endpoint

---

app/src/editor/shared/components/Preview/ModulePreview/Chart/index.jsx
app/src/editor/shared/components/Preview/ModulePreview/Table/index.jsx
app/src/marketplace/components/Modal/SetPriceDialog/PaymentRateEditor/FixedPriceSelector/index.jsx
app/src/marketplace/components/ProductPage/StreamListing/index.jsx
app/src/marketplace/components/Table/CollapseRow/index.jsx
app/src/shared/components/SvgIcon/ImageUploadIcon/index.jsx
app/src/shared/components/SvgIcon/index.jsx

**tl;dr** Chrome exposes elements with ids as `window` properties, i.e. `<div id=“a”></div>` is accessible via `window.a`. Longer ids are less likely to cause conflicts with… browser extensions.
I don't feel like it's a proper solution to the problem. Why? The exception tells us that `indexOf` is not a function. It means that `a[b].target.className` is somehow defined. Here's what Chrome thinks `window.a` is on core pages:
_(`window.b` is part of the same svg, so `a[b]` kinda makes sense.)_
I'd treat this PR as an attempt to solve the issue rather than the actual fix. Hope that's good enough.
FYI, [an article](https://medium.com/@amir.harel/a-b-target-classname-indexof-is-not-a-function-at-least-not-mine-8e52f7be64ca) what helped me identify the issue

[PLATFORM-730] Longer ids for the rescue!(?)

---

app/src/editor/canvas/components/Toolbar.pcss
app/src/shared/components/Calendar/calendar.pcss

In this PR I force the calendar to persist its vertical position for months with different number of displayed weeks, i.e.
@mattatgit please note that the same happens when you're in year view and decade view.

[PLATFORM-527] Fix jumping calendars in the toolbar

---

app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss

In this PR I make the tooltip display different copy for when the module panel is open and close. I also use different color for the "+" icon for both states.
---

[PLATFORM-576] Dynamic "Add module" button tooltip

---

app/src/auth/components/LogoutPage/index.jsx
app/src/shared/modules/user/actions.js
app/src/shared/test/modules/user/actions.test.js
app/src/shared/utils/storage.js

The aim of this PR is to flush all user data on logout. The store gets forgotten because we pretty much redirect away from the app (`window.location=`), and `sessionStorage` and `localStorage` are cleared up manually in `logout` action.
Guys, let me know if you think it's gonna do the trick. Thanks!
PS. @timoxley check out the `useIsMounted` hook I made! 🍰 
---
Tickets addressed in this PR:
- [`PLATFORM-709`](https://streamr.atlassian.net/browse/PLATFORM-709)
- [`PLATFORM-601`](https://streamr.atlassian.net/browse/PLATFORM-601)

[PLATFORM-709] Flush user data on logout

---

app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/canvas/components/Ports/Value/Text/index.jsx
app/src/editor/canvas/components/Resizable/SizeConstraintProvider/Probe/probe.pcss
app/src/editor/canvas/components/Resizable/SizeConstraintProvider/index.jsx
app/src/editor/canvas/components/Resizable/index.jsx
app/src/editor/shared/components/ModuleHeader/index.jsx
app/src/editor/shared/components/ModuleHeader/moduleHeader.pcss
app/src/shared/components/EditableText/index.jsx
app/src/shared/components/TextControl/index.jsx

In this PR I make module titles take part in module size constraining. It makes the thing respect multiple buttons in the module title bar (`ModuleHeader`) and dynamic size of the actial title.
It's kind of a new situation cause usually the resizing comes from the outside (user drags the resize handler thus controls the size). Here we have a situation where component inside of the module box tells the box what's the current min size and the module box acts accordingly.
Anyway, long story short, looks like I got it! Let me know what you think (go, try to break it). 💃 
---
Tickets addressed in this PR:
- [`PLATFORM-570`](https://streamr.atlassian.net/browse/PLATFORM-570) Minimum module size should take module name into account
- [`PLATFORM-689`](https://streamr.atlassian.net/browse/PLATFORM- …

[PLATFORM-570] Module titles vs min. module widths

---

app/src/editor/shared/components/modules/Table.jsx
app/src/editor/shared/components/modules/Table.pcss

Here's how it looks like with the fix applied:
Thoughts?

[PLATFORM-728] Fix vertical alignment of Table module cells

---

app/src/app/index.jsx
app/src/editor/canvas/components/Embed.jsx
app/src/editor/canvas/components/Embed.pcss
app/src/links.js
app/src/marketplace/components/NotFoundPage/index.jsx
app/src/marketplace/i18n/en.po
app/src/marketplace/styles/pcss/buttons.pcss
app/src/routes/definitions.json
app/src/shared/components/EmptyState/emptyState.pcss

Adds a customised error page for canvas embed urls and updates `NotFound` page to have link buttons for core app and landing page. I also updated `special-btn` style as requested by Matt & Saori.
This page will be displayed until we have implemented embedding.

[PLATFORM-712] Gracefully handle embed urls

---

app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/modules/userPageStreams/actions.js

Quick fix to run status update calls in series instead of firing everything at once. Let's add paging in a separate issue.

[PLATFORM-632] Streams list jams the browser if the user has many streams

---

app/package.json
app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/state.test.js
app/src/shared/components/WithCalendar/index.jsx

Prevents selecting a begin/from date later than end/to date.
If begin > end, it will set the other date to the value that was just set. This feels reasonable when I played around with it.
Also set it up to block starting of a canvas if invalid to/from dates are set, but also to be able to recover in the case that one has (i.e. unlinks from parent if fails to stop adhoc canvas).
----
Also there was yet another subtle bug caused by copying props to state but not updating state when props change (in this case calendar UI wouldn't update when selected date changed). This is killing me, we need a lint rule or something.

[PLATFORM-713] begin/end dates

---

app/src/editor/shared/components/Map/Map.jsx
app/src/editor/shared/components/modules/Map.jsx

If module has option `autoZoom` enabled the Map will now zoom so that current viewport covers all markers.

[PLATFORM-649] Add autoZoom

---

app/src/editor/shared/tests/ModuleSubscription.test.jsx

I have a feeling that module subscription data isn't flowing correctly with the most recent updates to the docker environment.
This test fails in my recently updated local dev environment, but passed in @fonty1's less recently updated local dev environment.
Subscriptions seem to work (i.e. tests pass), but not for canvas module `uiChannel`s.
Interested whether it works in CI i.e. is it just something on my machine, or is there a problem with the docker setup.

Test module subscriptions work with current docker env

---

app/src/shared/components/FormControl/index.jsx

Makes shared FormControl extend PureComponent to prevent pointless/recursive setState calls.
Possible fix for recursive rendering issue on staging.

Possible fix to staging login recursive rendering issue

---

app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.jsx
app/src/editor/shared/components/modules/Solidity.jsx

Solidity editor wasn't persisting code to canvas correctly and was firing errors on blur, both due to missing `onChange` prop. Added `onChange` and prevented crash due to missing `onChange`.

Fix solidity editor onChange

---

app/src/editor/shared/components/SearchPanel/SearchPanel.pcss

Seems to work, but for how long?
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/vAcR9UdJwJw
Nah, that's been open since 2012, so probably won't go away before we get:
https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property

[PLATFORM-917] Prevent search content jumping as scrollbar appears/disappears

---

app/src/editor/i18n/en.po
app/src/editor/shared/components/Chart/RangeSelect/index.jsx
app/src/editor/shared/components/Chart/RangeSelect/rangeSelect.pcss
app/src/editor/shared/components/Chart/approx.js
app/src/editor/shared/components/Chart/chart.pcss
app/src/editor/shared/components/Chart/index.jsx
app/src/editor/shared/components/UiSizeConstraint/index.jsx
app/src/editor/shared/components/modules/Chart.jsx
app/src/editor/shared/components/modules/Chart.pcss
app/src/shared/components/AutosizedSelect/autosizedSelect.pcss
app/src/shared/components/AutosizedSelect/index.jsx

In this PR I make the Chart module resizeable and steer the styling towards the designs, as far as possible.
Few noteworthy things:
- it's mostly running on hooks
- comes with the refactored `RangeSelect` component and nicer ranging
- tried to optimize redrawing so that the resizing is smooth(er)
@mattatgit the styling isn't 100% accurate. The library we're using for this is flexible but has its limitations. I went through a couple of painful styling rounds for this and would say it's 80% of what we planned. Hope that's "good enough" for you, sir.
PS. Guys, ignore the `um` part. There's a separate PR for it. It just happens to be here. :)

[PLATFORM-539] Chart module resizing

---

app/src/shared/modules/integrationKey/services.js

Adding an ethereum account is broken in latest development, due to `web3-beta.55` upgrade (#517).
`web3.eth.personal.sign` requires a password but is actually ignored by Metamask so need only to pass empty string.

[PLATFORM-891] Fix adding ethereum identity

---

app/src/auth/components/EthereumLogin/index.jsx

Fixes ethereum login in `development` by passing the instance of the `web3` injected by Metamask directly to the `StreamrClient` as the used provider. Using the wrapped provider does not work for some reason `web3-beta.55` (https://github.com/MetaMask/metamask-extension/issues/6080).
This will work for now as the `validateWeb()` helper takes care of approving the usage and Metamask injects the provider. In the (near) future though, Metamask will stop injecting its `web3`.
We should move to `ether.js` soon because `web3` is a mess.

Fix ethereum login

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/index.jsx
app/src/editor/shared/utils/boundingBox.js

When you add modules by clicking an item on the ModuleSearch list, we are now running a simple collision detection algorithm to see if we'd overlap with another module and apply an offset if needed.
Currently we are using a placeholder for the module size (100px * 50px) since we don't know the module size until it has been added to the canvas.

[PLATFORM-489] Add module stacking when using click insert from ModuleSearch

---

app/src/shared/components/EditableText/index.jsx

Currently double-clicking module header, then clicking it again does not allow editing. Due to module dragCancel class reference being missing. This fixes it.

Fix text editing after double-clicking then clicking module header.

---

app/src/userpages/components/TransactionPage/List/NoTransactions/index.jsx
app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/i18n/en.po

No accounts linked:
One account linked + selected in Metamask, no transactions:
One account linked + another account selected in Metamask, no transactions (text is changed to "link the **current** account"):
If any of the linked accounts have transactions, then the list is shown and there is no hint that the current account is not linked:

[PLATFORM-878] Update transactions empty state

---

app/src/editor/canvas/components/DragDropContext.jsx
app/src/editor/canvas/components/PortDragger.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/state.js
app/src/editor/canvas/tests/connection.test.js
app/src/editor/canvas/tests/services.test.js
app/src/editor/canvas/tests/variadic.test.js

Ensures connections are restored as well as they can be after loading new module definition.
To test:
1. Connect Constant Text to HTTP Module's body input
2. Change HTTP Module verb to anything else
3. Note connection persists
Alternatively try using anything that uses a Contract type input.

[PLATFORM-626] Fix module connection states after definition load

---

app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/shared/components/Map/Map.jsx
app/src/editor/shared/components/modules/Map.jsx

Map center and zoom level changes are now saved into module options so they are persisted with autosave.

[PLATFORM-915] Persist Map center and zoom level changes

---

app/src/newdocs/content/api.mdx

This doc section describes the 3 different ways to authenticate using the API.
Once we have the doc for clients (JS, Java and Python), would be good to have a reference note to remind the reader that the libraries already implement these methods. Especially for the challenge-response authentication which is not trivial to use without an already implemented tool.
Would be nice to have all auth methods in the [cli tool](https://github.com/streamr-dev/cli-tools) and mention and reference here that the tool implements these authentication methods.

init auth doc

---

app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/services.js
app/src/editor/canvas/state/index.js
app/src/editor/canvas/state/linking.js
app/src/editor/canvas/tests/adhoc.test.js
app/src/editor/canvas/tests/linking.test.js

The parent/child feature needed some adjustment, historical runs shouldn't affect other users thus the linkage between parent->child shouldn't live in the parent canvas. 
This stores it in localStorage. Child -> parent link is still on the child, since we always want to be able to return to the parent. This also saves on network round-trips and simplifies the implementation.
To test: historical runs should continue to work as they do today.

[PLATFORM-918] Use localStorage for adhoc canvas linkage

---

app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/ModuleDragger.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/state.js

Updates modules after module options set.
To test: change number of inputs in Chart module options. After autosave you should see the inputs change. Making subsequent changes to options or repositioning module should not break things, but will delay change being reflected, it waits until no changes since last change to apply changes from autosave response.

[PLATFORM-914] module options update

---

app/src/userpages/components/StreamPage/List/index.jsx

If the user's local time is not exactly accurate, they might see future versions of the verbal descriptions in "Last Data" column on stream list page, like "in a few seconds" or "in a minute".
Added `moment.min` to check that the date is not past the present. If and invalid moment is one of the arguments, nothing is shown.

[PLATFORM-635] Prevent future timestamps in stream list

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/shared/components/SearchPanel/SearchPanel.pcss

* Adds two workarounds for a chrome rendering `overflow: overlay` bug causing stream search results to disappear.
* Treat "streams" keyword the same as "stream".
Not entirely sure this fixes the reported issue, as I'm not sure I was able to reproduce, see: https://streamr.atlassian.net/browse/PLATFORM-957

[PLATFORM-957] Fix module selector's disappearing & non-clickable results

---

app/src/editor/canvas/components/CanvasSearch.pcss

Not sure when this regressed but here's a fix.

Vertically center text in canvas search rows

---

app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/canvas/components/Ports/Port/port.pcss
app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/connection.test.js
app/src/editor/canvas/tests/variadic.test.js

A user reported an issue whereby they could not connect a passthrough output.
In this case the input was not connected so the connection was prevented by sanitising code that disconnects a linked output's connections when the linked input is disconnected. This is normally a valid operation, however in this case **the linked input was exported** so the actual connection state is unknown. Linked output ports with an exported linked input should be able to be connected. This PR fixes that (see 0cfcc01)
I have confirmed that this fixes the issue with the production canvas.
Also added some additional fixes and tests:
* Show red 'can't connect' state when trying to connect a linked output whose input is not connected or exported (d94d7a693)
* All connections deemed invalid will be disconnected …

Fix connection issue with exported passthrough 

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/index.jsx
app/src/editor/shared/utils/boundingBox.js

Also set it to select the module after adding, this ensures it always renders on top:
Please test, try break.
Break = module appears at same position as another module or somewhere that isn't *near* the modulesearch box, or otherwise hidden.

Ensure added modules are offset from module closest to ModuleSearch

---

app/src/editor/canvas/components/DragDropContext.jsx

Prevents crash if use tries to delete a module while also dragging it. Solution is to disable all keyboard events while dragging, except those explicitly handled by the dragger e.g. escape.

[PLATFORM-692] Fix crash if deleting module while dragging

---

app/src/editor/canvas/components/CanvasController/useCanvas.jsx
app/src/editor/canvas/components/CanvasController/useCanvasUpdater.jsx
app/src/editor/canvas/index.jsx
app/src/editor/dashboard/index.jsx
app/src/editor/shared/components/UndoControls.jsx
app/src/shared/components/UndoContextProvider/index.jsx
app/src/shared/test/components/UndoContext.test.jsx

Moving `UndoContext` under `shared` so it can be used outside of the editor.

Move UndoContext to shared

---

app/src/editor/canvas/components/CanvasSearch.jsx
app/src/editor/canvas/components/CanvasSearch.pcss
app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/index.pcss
app/src/editor/dashboard/components/DashboardModuleSearch.jsx
app/src/editor/dashboard/components/DashboardModuleSearch.pcss
app/src/editor/shared/components/SearchPanel/ListBox.jsx
app/src/editor/shared/components/SearchPanel/SearchPanel.pcss
app/src/editor/shared/components/SearchPanel/index.jsx

Works for Canvas, Module & Dashboard search panels in the editor.
* Up/Down to change selection.
* Enter to confirm selection.
* First item selected by default.
* Selection loops around when at start/end of list.
* Focus stays in search box (if it was focused).
* Keyboard controls are responsive when mouse hovered over the list.
* Scrolls to selected item when selection changes.
* Smooth scrolling in Chrome/Firefox (Safari needs polyfill)
There's a warning in console about invalid ref propType due to outdated `react-router-dom`, attempting to upgrade. **update**: nope, cascading updates needed. We can live with the warning.

[PLATFORM-494] Editor Search Panel Keyboard controls

---

app/src/docs/components/ApiPage/index.jsx
app/src/docs/components/GettingStartedPage/index.jsx
app/src/docs/components/IntroductionPage/index.jsx
app/src/docs/components/MarketplacePage/index.jsx
app/src/docs/components/StreamrEnginePage/index.jsx
app/src/docs/components/TutorialsPage/index.jsx
app/src/docs/components/UserPage/index.jsx
app/src/docs/components/VisualEditorPage/index.jsx
app/src/marketplace/containers/ProductPage/index.jsx
app/src/marketplace/containers/Products/index.jsx
app/src/newdocs/components/DocsPages/API/index.jsx
app/src/newdocs/components/DocsPages/Canvases/index.jsx
app/src/newdocs/components/DocsPages/Core/index.jsx
app/src/newdocs/components/DocsPages/Dashboards/index.jsx
app/src/newdocs/components/DocsPages/DataToken/index.jsx
app/src/newdocs/components/DocsPages/GettingStarted/index.jsx
app/src/newdocs/components/DocsPages/Introduction/index.jsx
app/src/newdocs/components/DocsPages/Marketplace/index.jsx
app/src/newdocs/components/DocsPages/Products/index.jsx
app/src/newdocs/components/DocsPages/RunningNode/index.jsx
app/src/newdocs/components/DocsPages/SDKs/index.jsx
app/src/newdocs/components/DocsPages/Streams/index.jsx
app/src/newdocs/components/DocsPages/TechnicalNotes/index.jsx
app/src/newdocs/components/DocsPages/Tutorials/index.jsx

Fixes this `react-helmet` "Uncaught RangeError: Maximum call stack size exceeded" issue reported by @fonty1:
See:
* https://github.com/nfl/react-helmet/issues/437
* https://github.com/nfl/react-helmet/issues/373
Never use `<Helmet><title>`, use `<Helmet title="" />` instead
----
@fonty1 also I think the docs titles are probably back to front? It should have the current doc name first, rather than "Streamr Docs"
e.g. 
"Introduction | Streamr Docs" vs
"Streamr Docs | Introduction". 
i.e. most significant bit first.
Otherwise if you have a bunch of docs tabs open (especially likely for docs) all you'll see is "Streamr Docs …", "Streamr Docs …", "Streamr Docs …", "Streamr Docs …". The other page titles are also around the other way, so should probably change just for consistency if nothing …

Add workaround for react-helmet + useEffect bug.

---

app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/state.test.js

This PR ensures empty double values are saved/sent to the server as `undefined` rather than empty string. Empty string causes a `500` error on server :rage1:
Not sure how this hasn't come up as an issue before as it seems to affect every input/param.
1. Add Equals module.
2. Set "tolerance" to any number.
3. Click canvas background to blur input & commit change
4. Select & delete the tolerance value
5. Click canvas background to blur input & commit change (input should be empty)
6. Wait for autosave
Autosave fails with `500` error:
```js
{
code: "NumberFormatException"
message: "empty String"
}
```
Also note this is a frustratingly bad error message as it doesn't indicate which module or port caused the issue. Just terrible.
It saves correctly. 🎆

Fix setting double inputs to empty string

---

app/package.json

Sometimes things get confused. Wiping the various build caches can help.
This PR adds a convenience `npm run clean-cache` script which:
* Wipes the `babel` & `eslint` caches in  `node_modules/.cache`
* Removes built files in `dist`
* Cleans `jest`'s cache
* Kills the `flow` server(s) and wipes the `flow` cache in `/tmp/flow`
Try running this before `npm start` if you're seeing build errors and they don't make no damn sense.

Add clean-cache npm script.

---

app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/flowtype/states/stream-state.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/tests/modules/userPagesStreams/reducer.test.js

Re-requests a new stream list on stream page mount. This ensures we're showing at least the first page of the latest results. By default this will show the most recently created stream first. 
Also removes the list of streams on unmount to prevent any flash of streams which are about to get clobbered when the new stream list update finishes on remounting. Also fixes an issue where duplicate streams would appear in the list.
Note the start/end of "pages" in the client will immediately desync with the start/end of the pages on the server any time the list of streams is mutated by adding, removing or updating something that affects the list item content or ordering. Pagination desync means items may be missing or appear out of order.
To test:
1. Open Streams list.
2. Create & Save new …

[PLATFORM-978] Update stream list after creating stream

---

app/src/auth/components/SessionProvider/index.jsx
app/src/auth/utils/loginInterceptor.js
app/src/docs/components/ApiPage/index.jsx
app/src/docs/components/GettingStartedPage/index.jsx
app/src/docs/components/IntroductionPage/index.jsx
app/src/docs/components/MarketplacePage/index.jsx
app/src/docs/components/StreamrEnginePage/index.jsx
app/src/docs/components/TutorialsPage/index.jsx
app/src/docs/components/UserPage/index.jsx
app/src/docs/components/VisualEditorPage/index.jsx
app/src/editor/shared/utils/api.js
app/src/index.jsx
app/src/marketplace/containers/ProductPage/index.jsx
app/src/marketplace/containers/Products/index.jsx
app/src/newdocs/components/DocsPages/API/index.jsx
app/src/newdocs/components/DocsPages/Canvases/index.jsx
app/src/newdocs/components/DocsPages/Core/index.jsx
app/src/newdocs/components/DocsPages/Dashboards/index.jsx
app/src/newdocs/components/DocsPages/DataToken/index.jsx
app/src/newdocs/components/DocsPages/GettingStarted/index.jsx
app/src/newdocs/components/DocsPages/Introduction/index.jsx
app/src/newdocs/components/DocsPages/Marketplace/index.jsx
app/src/newdocs/components/DocsPages/Products/index.jsx
app/src/newdocs/components/DocsPages/RunningNode/index.jsx
app/src/newdocs/components/DocsPages/SDKs/index.jsx
app/src/newdocs/components/DocsPages/Streams/index.jsx
app/src/newdocs/components/DocsPages/TechnicalNotes/index.jsx
app/src/newdocs/components/DocsPages/Tutorials/index.jsx
app/src/setup.js
app/webpack.config.js

Converts session provider to use `window.localStorage` instead of `window.sessionStorage`. This fixes the core issue of needing to login when you open multiple tabs.
To handle the logout case I've added a redirect to the login page (and back to current page) on detecting a 401 response from any API endpoint as discussed.
There may be issues with this change should any API responses respond with a 401 and a redirect to login is not appropriate. I couldn't see any references to a 401 status checks in the existing code, but it's possible that there's some non-discriminating error handler that will no longer be run due to this interceptor. Perhaps not.

[PLATFORM-475] Share session across tabs, redirect to login on auth failure

---

app/src/marketplace/components/ProductTypeChooser/index.jsx
app/src/marketplace/containers/CreateProductPage/index.jsx
app/src/marketplace/flowtype/product-types.js
app/src/marketplace/modules/editProduct/services.js

Add logic for POSTing an empty product when we have selected type from `ProductTypeChooser`.
Current backend will reject the call but it should start working after https://github.com/streamr-dev/engine-and-editor/pull/628 is merged.

[PLATFORM-968] Create empty product

---

app/src/editor/canvas/components/Ports/Value/Select/select.pcss

To test:
1. Create a `MovingAverage` module.
2. Note that the dropdown for `Window Type` is visible.

[PLATFORM-981] Fix "possible values" dropdown to be visible.

---

app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/state.test.js
app/src/shared/components/EditableText/editableText.pcss
app/src/shared/components/EditableText/editableText.stories.jsx
app/src/shared/components/EditableText/index.jsx

Fixes issue where value of `0` was not operating correctly. 
Also fixes clipping right-hand side of placeholder text.
To test:
1. Create a `MovingAverage` module.
2. Note that defaults for `windowLength` & `minSamples` inputs are filled with the default value of zero (fixes original issue).

[PLATFORM-982] Fix default values

---

app/src/userpages/components/StreamPage/Show/ConfigureView/NewFieldEditor/index.jsx
app/src/userpages/components/StreamPage/Show/ConfigureView/index.jsx
app/src/userpages/components/StreamPage/constants.js
app/src/userpages/i18n/en.po

In stream field config, the dropdown label `Object` has the wrong value `object`. The correct value is `map`. Fixed according to issue description - kept user facing label as `Object` but use the value `map`.

[PLATFORM-979] Wrong key for "Object" type

---

app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/CanvasController/useAutosaveEffect.js
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleDragger.jsx
app/src/editor/canvas/components/PortDragger.jsx
app/src/editor/canvas/components/Ports/Plug/index.jsx
app/src/editor/canvas/components/Ports/Value/Select/index.jsx
app/src/editor/canvas/components/Ports/Value/Select/select.pcss
app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/components/Ports/Value/value.pcss
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js
app/src/editor/canvas/state/diff.js
app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/changes.test.js
app/src/editor/canvas/tests/connection.test.js
app/src/editor/canvas/tests/diff.test.js
app/src/editor/canvas/tests/state.test.js
app/src/editor/canvas/tests/variadic.test.js
app/src/editor/shared/utils/autosave.js
app/src/shared/components/TextControl/index.jsx
app/src/shared/hooks/usePending.jsx

Set up to read in values in from server on autosave. Won't clobber modules that have changed since the autosave was triggered.
* Values should update appropriately when connections are made https://github.com/streamr-dev/streamr-platform/pull/598#pullrequestreview-266618452
* Options changes should trigger module content updates e.g. chart module input counts.
* Disconnecting should restore previously set value.
A few things to improve still before this is ready:
* Loading indicator is a bit much
* Handling stuff which is not changed but is currently being edited/dragged when server response comes back.
* Verifying undo/redo works as expected.
@juhah can you do me a favour and test that the logic you added for the Java/Ethereum contract modules still works as expected? I believe the new …

Update with server state on autosave

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/ModuleSearch.pcss
app/src/editor/shared/components/SearchPanel/SearchPanel.pcss

Clip long module/stream results text with ellipsis.
Show full text in native tooltip.

[PLATFORM-955] Clip long module/stream results text with ellipsis.

---

app/src/marketplace/components/ProductPage/index.jsx
app/src/marketplace/components/ProductPageEditor/index.jsx
app/src/marketplace/components/Steps/index.jsx
app/src/marketplace/components/Steps/steps.pcss
app/src/marketplace/containers/EditProductPage2/editProductPage.pcss
app/src/marketplace/containers/EditProductPage2/index.jsx
app/src/shared/components/Buttons/buttons.pcss
app/src/shared/components/ConfirmDialog/confirmDialog.pcss
app/src/shared/components/ConfirmDialog/index.jsx
app/src/shared/components/Toolbar/index.jsx
app/src/shared/components/Toolbar/toolbar.pcss
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/ShareDialog/ShareDialogContent/shareDialogContent.pcss
app/src/userpages/components/StreamPage/Show/index.jsx
app/stories/shared.stories.jsx

Make toolbar full width in product, profile and stream edit page. Added also a `middle` prop that can be used for the wallet status icon (can be seen in storybook). I removed the padding from the `Buttons` component which was used in these components (other than the toolbar):
- `Steps`
- `ConfirmDialog`
- `Dialog`
- `KeyFieldEditor`
- `ShareDialogContent`
- `SnippetDialog`
I checked that these should work as before but let know if there are problems.

Refactor Toolbar for full width

---

app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/canvas/components/PortDragger.jsx
app/src/editor/canvas/components/Ports/Dragger/dragger.pcss
app/src/editor/canvas/components/Ports/Plug/index.jsx
app/src/editor/canvas/components/Ports/Plug/plug.pcss
app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/index.jsx
app/src/editor/shared/components/Module.pcss

This is an initial step towards embeds. 
Currently there are some UI editing features left enabled when they should not be (see list below). The server permissions system will block the changes from being applied, but the UI does still allow changes. Shared canvases need to have all editing features disabled. Embedded canvases are shared canvases.
This PR prevents "adjustments" when a canvas is "not adjustable" and prevents "edits" when the canvas is "not editable". This PR also hides the module search whenever the canvas is "not editable".
Modules may be repositioned or resized so long as the canvas is "adjustable", but edits to the following are blocked while "not editable":
* Sidebar option changes
* Port connections
* Port value changes
* Module deletion via Delete key
* Port …

[PLATFORM-992] Block edits while canvas is not editable

---

app/src/editor/shared/components/Chart/index.jsx
app/src/editor/shared/components/modules/Chart.jsx

Reproduced issue reported in https://streamr.atlassian.net/browse/PLATFORM-998
At around 800 points the current chart implementation slows to a crawl. Unusable. 
This PR moves data handling out of React into the chart lib.
Diff updates are pushed on each change rather than the entire dataset.
1. Create Canvas with a `Clock` set to 1s, plugged into the trigger on a `RandomNumber`, plugged into a Chart.
2. Run in Historical mode, 10x speed.
3. Before this PR it would slow to a crawl in <30s, now it appears to continue working indefinitely. Chart also seems to survive 100x & 1000x speeds.
Below screenshot shows similar setup to above description:

[PLATFORM-998] Chart Performance

---

app/src/editor/canvas/components/Cables.jsx

Problem looks like this:
Issue is caused by a delayed canvas update arriving during a drag operation e.g. autosave. This canvas update triggers re-reading port positions, which then applies the drag offset which was calculated from the previous position of the module. 
This is a quick fix that disallows position updates for cables during a drag operation. Cables can still get out of alignment if port positions actually change (e.g. multi-user env). Not perfect, but better.
1. Connect some stuff
2. Move something
3. Before autosave kicks in, start dragging a module around.
4. Keep dragging, cables should not get out of alignment once autosave is done.

[PLATFORM-976] Fix glitching cables

---

app/src/editor/canvas/components/Cables.jsx
app/src/editor/canvas/components/Canvas.jsx
app/src/editor/canvas/components/Canvas.pcss
app/src/editor/canvas/components/DragDropContext.jsx
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleDragger.jsx
app/src/editor/canvas/components/PortDragger.jsx
app/src/editor/canvas/components/Ports/Dragger/dragger.pcss
app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/canvas/components/Ports/index.jsx
app/src/editor/canvas/state/index.js

Helps you more clearly see what's connected to what on messy canvases.
* Shows currently dragged cable on top of modules
* Shows cables of currently dragged module on top of other modules
* Hides port "options" during drag (DI/NR buttons)
* Fixes regression where after cancelling a drag with esc, dragging was permanently cancelled.
* Fixes regression where reconnecting to same port after starting a drag would disconnect the port.
Includes commits from glitching cables PR #634.

Highlight cables related to selected module

---

app/package-lock.json
app/package.json
app/src/docs/components/DocsLayout/Navigation/index.jsx
app/src/editor/canvas/components/Canvas.jsx
app/src/editor/canvas/components/Canvas.pcss
app/src/editor/canvas/components/CanvasController/useCanvasUpdater.jsx
app/src/editor/canvas/components/Module.jsx
app/src/marketplace/containers/ProductPage/index.jsx
app/src/shared/components/AutoScroll/index.jsx

Partial improvement for [PLATFORM-973](https://streamr.atlassian.net/browse/PLATFORM-973). Adds a ponyfill for scrolling items into view if needed, smoothly. https://caniuse.com/#feat=scrollintoview
Eliminates annoying jump on selecting a module:
> Scroll position also jumps annoyingly on simply selecting a module 
And partially addresses:
> On a high canvas (scrollable vertically), when I start dragging modules on the visible part of the canvas, the scroll position annoyingly changes
Not a full fix, needs something more sophisticated to handle dragging modules in and out of the canvas bounds, but this PR makes it less annoying.
Also fixes smooth-scrolling `SearchPanel` results in Safari.

[PLATFORM-973] Prevent annoying scroll to module on selection

---

app/src/shared/modules/resourceKey/actions.js
app/src/shared/test/modules/resourceKey/actions.test.js
app/src/userpages/components/StreamPage/Show/KeyView/index.jsx

Ensures resource keys are always fetched. Fixes bug where sometimes (most times) resource keys weren't loading because the `disabled` state was removed after `streamId` was added, but component didn't trigger resource key load.
Also fixes another bug where a resource keys wouldn't appear after adding it.

[PLATFORM-1003] Fix loading of stream resource keys

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/shared/components/SearchPanel/index.jsx

When module search results are closed e.g. via X button or automatically when a canvas starts, upon reopening, search is in a weird state where the search input is still set, but no search results are shown.
This fixes that by resetting the state via `key` whenever a `SearchPanel` with a `resetOnClose` flag set is closed.
Also fixed an issue where the canvas search "open" button was not toggling the visibility of the canvas search panel. It was closing the search on button mousedown (due to "close on blur" behaviour) and reopening it on mouseup (i.e. click).

[PLATFORM-969] Clearing search results on close

---

app/src/editor/canvas/components/Ports/Value/Select/index.jsx
app/src/editor/canvas/components/Ports/Value/Select/select.pcss

What do you think @timoxley?
The `optionMap.get(value) || value` really isn't perfect. It seems to work tho. And I think we should address the issue at its core (e&e). This should do it for now tho.
Please try to break it.

[PLATFORM-981] Force the default possible value do display “correctly”

---

app/src/app/index.jsx
app/src/auth/utils/loginInterceptor.js
app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/Embed.jsx
app/src/editor/canvas/components/Embed.pcss
app/src/editor/canvas/index.jsx
app/src/editor/shared/components/Client.jsx
app/src/routes/definitions.json
app/src/shared/components/Layout/index.jsx
app/src/userpages/hooks/useEmbed.js

Prevents edits, hides nav & toolbar in embed mode.
Fixes generated embed code.
Prevents redirecting to login for embed urls.
To test:
* Share a canvas publicly.
* Get embed code.
* Access the url in embed code directly while logged in & logged out (i.e. incognito mode). e.g. http://localhost/canvas/embed/sUc-jCKxSKaVx4KFJGZ75wjOTJOzEfTnWFwiJJRRsgEA
* Drop embed code iframe on a docs page, access docs page see iframe works logged in & logged out.
~~*update*: Just noticed running canvases have a recursive loop issue if user is logged out.~~ Fixed

[PLATFORM-990] Minimal embeds canvases

---

app/src/editor/canvas/components/Cables.jsx
app/src/editor/canvas/components/Preview.jsx

* Fixes preview cable rendering. Wasn't working due to recent update to cable drawing code using `width` which wasn't being passed in preview cable's data.
* Also now draws cables from appropriate edge rather than middle of modules, which looks more like full version.
To Test:
The previews in the canvas list page cables should render. Cables should appear to emerge from vertical center+left/right edge of modules.

Fix preview cable rendering

---

app/package-lock.json
app/package.json
app/src/editor/shared/components/Map/Map.jsx
app/src/editor/shared/components/Map/Map.pcss
app/src/editor/shared/components/modules/Map.jsx

The autozoom feature causes the map to zoom and pan automatically so all the markers are visible. Autozoom currently gets disabled for a number of interaction events but doesn't get disabled when the user clicks the visible zoom buttons, so when a user manually adjusts the zoom, the next time a marker update arrives, their zoom level is clobbered by autozoom. 
This PR makes a few changes to improve the issues described in https://streamr.atlassian.net/browse/PLATFORM-1006:
* Adds 20% padding around the autozoomed points so they don't always sit at the edges of the map. This addresses @fonty1's "make it zoomed out more" request in the JIRA ticket.
* Disables autozoom when user clicks the zoom buttons
* Disables autozoom only if user presses keys that adjust zoom or pan (arrows and +/-), …

[PLATFORM-1006] Improve Geo Map Autozoom UX

---

app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/canvas/components/ModuleSidebar.pcss
app/src/editor/canvas/components/Ports/Value/Select/index.jsx
app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/shared/components/Sidebar/sidebar.pcss
app/src/shared/components/EditableText/editableText.pcss
app/src/shared/components/EditableText/index.jsx

@tumppi added a few tweaks on top your sidebar PR:
* Repurposed Port `Select` component for sidebar, doesn't match mock but better than unstyled.
* Did some magic to allow label clicks to give focus to `EditableText` inputs like normal inputs.
* Adjusted line-height & whitespace

[PLATFORM-994] Module sidebar tweaks updated

---

app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/index.jsx

This error can occur if you start a canvas "too fast" i.e. streams haven't been created yet.
Resolution is to wait for `start` request to respond before starting subscriptions.
Also fixes stop logic to handle empty stop response body.
(quickly)
1. Create new canvas
2. Connect `Clock` to `Table`
3. Start realtime canvas 
4. Should work, data should flow
Also try stopping & starting historical canvases. Should also work.

[PLATFORM-877] Fix "Not Authorised to Subscribe to Stream"

---

app/src/shared/components/EditableText/editableText.pcss

Possibly due to this bug, opened 11 years ago: https://bugs.webkit.org/show_bug.cgi?id=13820

[PLATFORM-993] Fix big input cursor in Safari

---

app/src/editor/canvas/components/KeyboardShortcutsSidebar.jsx
app/src/editor/canvas/index.jsx

Quick fix.
Terrible, confusing logic. The worst.
Canvas sidebar logic needs reworking at some point. Whatever, seems to work.

[PLATFORM-995] Click canvas background/esc to close KeyboardShortcutsSidebar

---

app/src/userpages/components/Header/Tab/tab.pcss

Active tab text colour should look the same as hover.
The style was set but wasn't specific enough.
Also added text colour transition on hover.
Also added an "underline" transition, though it doesn't currently work because the app is remounting the entire content area on navigation, but the transition should just work if/when we ever fix that.

[PLATFORM-996] Fix active tab colour

---

app/src/editor/canvas/components/Canvas.jsx
app/src/editor/canvas/components/Canvas.pcss
app/src/editor/canvas/components/CanvasWindow.jsx
app/src/editor/canvas/components/CanvasWindow.pcss
app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.jsx
app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.pcss
app/src/editor/canvas/components/CodeEditor/DebugWindow.jsx
app/src/editor/canvas/components/CodeEditor/index.jsx
app/src/editor/canvas/components/CodeEditor/useInitPosition.js
app/src/editor/canvas/components/DraggableCanvasWindow.jsx
app/src/editor/canvas/components/DraggableCanvasWindow.pcss
app/src/editor/shared/hooks/useUniqueId.jsx

* Code Editor is always centered in the window by default. Not possible to not see an opened code window now (primary fix for original issue).
* Renders `CanvasWindow`s on own layer. `CanvasWindow`s now ignore the panning of canvas, like `ModuleSearch`. (secondary fix)
Also:
* Renders debug window offset slightly from code window by default (ensures it is visible). 
* Before, debug always rendered on top of code, now the last selected window will render on top.
* The "Edit code", and "show debug" buttons now toggle opened state.
* Window positions are bound to canvas dimensions.
* Window positions get reset on window resize (simple workaround to prevent windows disappearing)
* Various minor refactorings.

[PLATFORM-660] Fix code editor position & window behaviour

---

app/src/shared/components/BodyClass/index.jsx
app/src/shared/components/SortableList/SortableList.pcss
app/src/shared/components/SortableList/index.jsx

1. Use Safari/Firefox
2. Create stream
3. Add two fields
4. Drag to reorder fields
5. No selection highlight should be visible.

[PLATFORM-438] Disable user-select when dragging SortableList items

---

app/src/shared/components/Tile/tile.pcss

Userpages tiles now always 200px high, across all break points (matches design).
Images seem to scale/crop appropriately if aspect ratio not right.

[PLATFORM-1011] Consistent tile size

---

app/src/editor/shared/components/modules/Table.jsx

Table module receives all row values as strings, but the backend module `MapAsTable` doesn't seem to perform the same String coercion before sending row values, so booleans don't render in the frontend. 
This should really be fixed on the backend so the table modules are consistent, but here's a workaround that forcibly coerces non-undefined/null table row values to `String`s.
The "true" and "false" values appear in the `MapAsTable`'s table.
No values appear in the `MapAsTable`'s table.

Coerce non-null/undefined table values to strings.

---

app/src/editor/canvas/components/Ports/Value/value.pcss
app/src/editor/shared/components/StreamSelector.pcss

Sans matches design.
Also tweaked stream selector dropdown to be a bit friendlier to multi-line values:

Use sans font for port values

---

app/src/editor/canvas/components/Ports/Menu/index.jsx
app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/shared/components/StreamSelector.jsx
app/src/shared/components/ContextMenu/ContextMenuItem/contextMenuItem.pcss
app/src/shared/components/ContextMenu/ContextMenuItem/index.jsx
app/src/shared/components/EditableText/index.jsx

Currently there's no way to see or get access to the stream id for the selected stream in the stream module.
This PR adds a "Copy value" option to port context menu.
Useful for copying stream id for stream inputs. Not perfect ~~since you can't paste the id back into an input since the stream search doesn't work with ids~~ (update: added support for this), but better.
Option will be disabled if connected or non-simple type of data.

Copy port value

---

app/src/editor/shared/components/Chart/index.jsx

Accounts for timezone offset on point values. Might be a better way to do this with some highcharts config but I couldn't figure it out.

[PLATFORM-1027] Show chart tooltip's timestamp in local timezone.

---

app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/CanvasController/useCanvasDuplicateCallback.jsx
app/src/editor/canvas/components/CanvasController/useCanvasLoadCallback.js
app/src/editor/canvas/components/CanvasController/useCanvasPermissions.jsx
app/src/editor/canvas/components/CanvasController/useEmbedMode.jsx
app/src/editor/canvas/index.jsx
app/src/editor/canvas/services.js

Prevents attempt to save before duplicating if user doesn't have write permission.
1. Create Canvas with `tester1@streamr.com`
2. Share canvas as read-only with `tester2@streamr.com`
3. Login in different window with `tester2@streamr.com`
4. Open the shared canvas
5. Duplicate Canvas should work, no errors in network panel or console due to trying to save unwritable canvas first.

[PLATFORM-1034] Prevent autosave on duplicate if not writable

---

app/src/editor/shared/components/SearchPanel/index.jsx
app/src/shared/hooks/wrapCallback.js

Doesn't fully fix [the underlying issue](https://streamr.atlassian.net/browse/PLATFORM-966) but there's [some limitations with react-draggable](https://github.com/mzabriskie/react-draggable/pull/392) that prevent us from solving this properly without forking or reimplementing react-draggable's bounds calculation code. 
Quick solution is to just reset position of search box on resize.

[PLATFORM-966] Reset search box location on window resize

---

app/src/editor/canvas/components/Ports/Value/List/ListEntry/index.jsx
app/src/editor/canvas/components/Ports/Value/List/ListEntry/listEntry.pcss
app/src/editor/canvas/components/Ports/Value/List/index.jsx
app/src/editor/canvas/components/Ports/Value/List/list.pcss
app/src/editor/canvas/components/Ports/Value/Text/text.pcss
app/src/editor/canvas/components/Ports/Value/index.jsx
app/src/editor/canvas/components/Ports/Value/value.pcss
app/src/editor/canvas/state/index.js

Currently it's not possible to set List type values, the UI was never implemented. It was on the TODO for a while but… disappeared.
To quickly remedy this missing functionality I've done up an adaption of the current Map type port UI for List type ports so it's at least possible to input something of the correct type. We'll need proper designs for this eventually, but the Map port UI will need an update at the same time and I think there are some more discussions to be had on how that should work.
This closes 3 tickets:
https://streamr.atlassian.net/browse/PLATFORM-1035
https://streamr.atlassian.net/browse/PLATFORM-1036
https://streamr.atlassian.net/browse/PLATFORM-1037

[PLATFORM-1036] Add support for 'List' type ports

---

app/src/userpages/components/StreamPage/Show/PreviewView/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx
app/src/userpages/modules/userPageStreams/actions.js

* Prevents flash of previous stream data before current stream data loads.
* Block field edits while loading stream data, prevents changing fields while saving or loading data.
* Show loading indicator on Stream show page.
* Prevents creation of new "Untitled Stream" if hitting the save button before the current stream loads.
* Prevent some "setState on unmount" errors.
Try creating and editing streams before & after this PR with network latency set to 3s in devtools.

Improve stream edit page load/save behaviour

---

app/src/docs/components/CanvasModuleHelp/Empty.jsx
app/src/docs/components/CanvasModuleHelp/index.jsx
app/src/docs/content/canvasModules/Empty.jsx
app/src/editor/canvas/components/ModuleHelp.jsx
app/src/editor/canvas/components/ModuleSidebar.jsx
app/src/editor/canvas/components/ModuleSidebar.pcss
app/src/editor/shared/components/Sidebar/Content.jsx
app/src/editor/shared/components/Sidebar/Header.jsx
app/src/editor/shared/components/Sidebar/Section.jsx

Changes docs loader to match on module `id`,  rather than `name`ish & `id`. Name of file mainly there so the docs files are human readable, `id` is important part.
This also fixes `Canvas` module docs loading, since a subcanvas `module.name` is user-defined, not `"Canvas"`, so it never matches `Canvas-81.jsx`.
Shows "There is no documentation for this module at this time." if docs can't be loaded, rather than nothing.
Also prevents network error if the module help is not found e.g. currently no `Stream` docs.
Closes https://streamr.atlassian.net/browse/PLATFORM-908

Handle missing docs in canvas sidebar.

---

app/src/editor/canvas/components/Ports/Port/index.jsx
app/src/editor/canvas/components/Ports/Port/port.pcss
app/src/editor/canvas/components/Ports/Value/Text/index.jsx
app/src/editor/canvas/components/Ports/Value/Text/text.pcss
app/src/shared/assets/stylesheets/fonts/ibm-plex.css
app/src/shared/components/EditableText/editableText.pcss
app/src/shared/components/EditableText/index.jsx

Some minor styling tweaks to canvas ports:
* Adjusts port name's colour to match design (from #323232 to #525252).
* Adds some colour contrast between placeholder text and actual values.
* Prevents EditableText input content jumping down 1px when entering edit mode in ports.
* Adds real italic variant of IBM Plex Sans. We're using this in a few places and the real version looks a lot nicer than the pseudo-italics produced by the browser.

Minor canvas port styling tweaks

---

app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogInputRow/index.jsx
app/src/userpages/hooks/useEmbed.js
app/src/userpages/i18n/en.po
app/src/userpages/tests/components/ShareDialog/ShareDialogContent/ShareDialogInputRow/shareDialogInputRow.test.jsx

These changes were discussed in a meeting RE canvas sharing.
1. Adds mention of 'Ethereum account' in 'Enter email address' text.
2. Uses editor link, rather than embed link, for canvas "copy link" button in share dialog.

Share dialog tweaks

---

app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/state.test.js

Backend currently doesn’t parse the date string correctly, it doesn’t take the time offset into account so historical canvases start at 00:00 utc time, possibly on the wrong date, instead of in user’s timezone.
Backend does correctly parse timestamp format though, so this PR:
1. Sends new canvas start/end dates as timestamps instead of ISO 8601 strings.
2. Updates existing canvas ISO 8601 start/end dates to be timestamps.
1. Plug a clock into a Table.
2. Switch to historical mode, pick a start and end date.
3. Start as historical canvas in 1x mode.
4. Note bottom entry in table should match the begin date you selected.
Also, old canvases with historical dates set as a date string should not break, should now run at correct date.

[PLATFORM-1072] Historical Date Strings vs Timestamps

---

app/src/editor/canvas/components/EmbedToolbar.jsx

Opens embed mode "View on Streamr" links in a new tab, but only if viewing from within an iframe.
1. Go to any canvas, open share dialog. 
1. Copy link.
1. Make public.
1. Paste copied link into new tab.
1. Click "View on Streamr" button, should open login in current tab.
1. Close tab, go back to canvas editor.
1. Open share dialog.
1. Go to embed
1. Copy embed code, paste into new html file or whatever. (or hack `<div dangerouslySetInnerHTML={{__html: embedCode}} />` into `EmbedDialogContent.jsx`) 
1. View embedded iframe.
1. Click "View on Streamr" button within iframe, should open login in new tab.

[PLATFORM-1060] Make 'View on streamr' button open in new tab

---

app/src/editor/canvas/index.jsx
app/src/editor/dashboard/index.jsx
app/src/marketplace/containers/ProductController/index.jsx
app/src/shared/components/PendingContextProvider/index.jsx
app/src/shared/hooks/usePending.jsx
app/src/shared/test/hooks/usePending.test.jsx

Adds some tests around the `usePending` hook, possible now that we have async `act`.
Also:
* Fixes issue with pending count being incorrect when sub-components unmount
* Adds support for "nested" pending contexts e.g. creating a pending context within a pending context, the parent context is considered still pending if the child context(s) is pending.

Add tests around `usePending` hook

---

app/src/editor/canvas/components/Ports/Value/Select/index.jsx
app/src/editor/canvas/components/Ports/Value/index.jsx

Fixes `PLATFORM-1063` where a select port is showing the `value` rather than the `name`. 
Issue was the wrapper that displays a TextInput instead of a Select when the control is disabled didn't use the same `name` extracting code as the Select.
1. Add "Moving Average" module.
2. Start canvas
3. Notice moving average module stays reporting "events" as value, rather than "EVENTS".
Also to test (things which are very sensitive to the `select` config/styles):
1. Should be able to change select value
2. Canvas module select should work
3. Module resizes appropriately after selection

[PLATFORM-1063] Fix read-only select to show selected `name`, not `value`

---

app/src/editor/canvas/index.jsx
app/src/editor/canvas/tests/java.test.js

Ensures module connections are maintained when updating definition. e.g. java/solidity 
This flow is basically what happens in [the tests](https://github.com/streamr-dev/streamr-platform/pull/703/files#diff-eeb66bc30681825cb00bb921b0ea946bR47-R93).
1. Add `Java` module
2. Add two `Constant` modules
3. "Edit Code" of `Java` module. Uncomment the first two lines, i.e.:
```java
TimeSeriesInput input = new TimeSeriesInput(this,"in");
TimeSeriesOutput output = new TimeSeriesOutput(this,"out");
```
4. Apply change.
5. Connect constants to the new input & output.
6. Add a new input & output i.e. add these lines after the previous lines
```java
TimeSeriesInput input2 = new TimeSeriesInput(this,"in2");
TimeSeriesOutput output2 = new TimeSeriesOutput(this,"out2");
```
7. Apply change.
8. Notice …

[PLATFORM-1080] Prevent losing connections on module definition update

---

app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/copyPaste.test.js

Generates a new uiChannel id on copy.
1. Create a canvas with Clock -> Table.
2. Run canvas for a moment to get some data in the table.
3. Copy/Paste Table.
4. Run Canvas.
5. New Table should not be filled with old Table's uiChannel data.

[PLATFORM-1090] Don't copy uiChannel with copy/paste

---

app/src/editor/canvas/components/Camera/index.jsx

Fixes annoying bug with pan keyboard shortcuts being activated when focus is within the module search or other module text editor e.g. java module, comment module.
Issue was that the "should I ignore this event" priority was incorrect, should ignore the event if it's coming from an editable element *before* checking if the event target is within a "camera control" container.

[editor/canvas Camera] Correctly ignore pan keyboard controls.

---

app/package.json
app/travis_scripts/build-docker-env.sh
app/travis_scripts/unit-tests.sh
app/travis_scripts/utils.sh

Solution was lowering global test coverage threshold to 34%. 🤷‍♀ 
Also:
* Engine and editor `/api/v1/users/me` in the docker env seems to give `302` now instead of `401`.
* broker-node `/api/v1/ws` seems to give `426` (protocol upgrade required) now instead of `404`.
* Added in the expected/actual status code, and the url into the "not up" retry text. i.e. `echo "$name not up. Expected: $expected_status. Got: $http_code from $url";`
Seems the docker build was semi-broken for a long time (it'd never detect e&e being up) but if the docker step failed it'd run the tests anyway so we never really noticed an issue. Fixed this so that the build fails if the docker build fails (via `set -e` in the unit tests script). Also by fixing the status code checks it should start running the actual tests …

Try fix CI

---

app/src/marketplace/components/ProductPage/ProductDetails/index.jsx
app/src/marketplace/containers/EditProductPage2/EditControllerProvider.jsx
app/src/marketplace/containers/EditProductPage2/state.js
app/src/marketplace/containers/EditProductPage2/tests/productState.test.js
app/src/marketplace/containers/ProductController/useOriginalProduct.js
app/src/marketplace/containers/ProductController/useProductActions.js
app/src/marketplace/containers/ProductController/useProductLoadCallback.js
app/src/marketplace/containers/ProductController/useProductUpdater.js
app/src/shared/components/UndoContextProvider/UndoContext.test.jsx
app/src/shared/components/UndoContextProvider/index.jsx

You'll need to update to latest version of e&e to test this (ie. icludes fix https://github.com/streamr-dev/engine-and-editor/commit/b9c140b07f9c9de2ff49fca924b0e8943336cf97)
To test, create a free published product and edit some fields. Product page should show the original information but going back to edit will display the edited changes. When editing an unpublished version, all changes are saved immediately to the product. 
Not included here:
- Publishing pending changes
- Notification icons for pending changes in editor navigation or product page
- Saving pending changes when unpublishing

[PLATFORM-1074] Save pending changes

---

app/package-lock.json
app/package.json

I got a tip off that this version may help improve our unhandled rejection error reporting. Looking through the feature diff makes me a little skeptical, but the update looks like its worth a test. 
https://github.com/getsentry/sentry-javascript/releases
Looks like they removed some old polyfills and got the bundle size down a bit. 
https://packagephobia.now.sh/result?p=%40sentry%2Fbrowser%405.7.1

Update @sentry/browser to 5.7.1

---

app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.jsx

Clicking the title to focus the editor was losing the editor focus immediately after setting it. Oops.
1. Add Java Module
2. Edit Code
3. Click canvas background to ensure code editor is not focussed.
4. Click Code Editor title bar
5. Focus should be in the code editor, you should be able to type to change code content

[PLATFORM-1081] Fix code editor text focus bug 

---

app/package-lock.json
app/package.json
app/src/app/index.jsx
app/src/editor/canvas/components/Status.jsx
app/src/links.js
app/src/marketplace/components/Hero/index.jsx
app/src/marketplace/components/ProductPage/MembersGraph/index.jsx
app/src/marketplace/components/ProductPage/ProductOverview/index.jsx
app/src/marketplace/components/ProductPage/ProductOverview/productOverview.pcss
app/src/marketplace/components/ProductPage/StreamListing/streamListing.pcss
app/src/marketplace/components/ProductTile/index.jsx
app/src/marketplace/containers/ProductPage2/Page.jsx
app/src/marketplace/containers/ProductPage2/ProductDetails.jsx
app/src/marketplace/containers/ProductPage2/index.jsx
app/src/marketplace/containers/ProductPage2/page.pcss
app/src/marketplace/modules/communityProduct/services.js
app/src/marketplace/modules/contractProduct/services.js
app/src/shared/components/DonutChart/donutChart.pcss
app/src/shared/components/DonutChart/index.jsx
app/src/shared/components/Dropdown/dropdown.pcss
app/src/shared/components/Dropdown/index.jsx
app/src/shared/utils/time.js
app/stories/shared.stories.jsx

Add overview section for product page that gets shown when we're dealing with a community product. It will query `/stats` endpoint. Member graph uses `joinPartStream` to plot member count as a function of time.
Missing features:
- getting subscriber count and admin fee from blockchain (https://github.com/streamr-dev/streamr-platform/pull/696 will enable us to get at least admin fee)
Here's some test data for joinPartStream. Basically you have to deploy a CP and use stream editor to upload this data for the joinPartStream.
https://www.dropbox.com/s/sw50bef3vrxbh7b/joinpart_data.csv?dl=0

[PLATFORM-1067] Community product statistics

---

app/package.json
app/src/editor/canvas/components/ModuleRenderer/ModuleRenderer.test.jsx

There were a whole bunch of issues when trying to render our storybook via enzyme/jsdom, issues  seemed to come primarily from within 3rd party libs trying to attaching event handlers to missing refs, so I gave up on that for now.
Achieved something similar by using the module renderer to render every module, this improves global line coverage up to 41% and isn't an entirely dumb test to do.
Also:
* excluded docs content & .story/flowtype files from coverage reports.
* Switched default coverage reporter to `text-summary`, which should make test log output a lot easier to read:
If you want to turn the full reporter back on, invoke `jest` like: 
```
npx jest --coverageReporters=text
```

Improve code coverage

---

app/src/editor/canvas/state/index.js
app/src/editor/canvas/tests/copyPaste.test.js
app/src/editor/canvas/tests/java.test.js
app/src/editor/shared/components/ModuleUI.jsx

This was silly on my part, was making ports unique on copy, not paste, so pasting again would do weird stuff because the port ids weren't unique.
I've fixed this and added a test.
Also:
* Java module test seems to time out sometimes, upped the timeout.
* Cherry-picked a fix for a regression in loading module runtime state

[PLATFORM-1104] Make ports unique on paste

---

app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleRenderer/index.jsx
app/src/editor/canvas/components/ModuleRenderer/useModule.js
app/src/editor/canvas/index.jsx
app/src/editor/shared/components/ColorPicker.jsx
app/src/editor/shared/components/ColorPicker.pcss
app/src/editor/shared/components/modules/Button.jsx
app/src/editor/shared/components/modules/Comment.jsx
app/src/editor/shared/components/modules/Custom.jsx
app/src/editor/shared/components/modules/Scheduler.jsx
app/src/editor/shared/components/modules/Solidity.jsx
app/src/editor/shared/components/modules/Switcher.jsx
app/src/editor/shared/components/modules/TextField.jsx

Original ticket just about copy/paste when in read-only mode, expanded on this somewhat.
Changed:
* Copy works when running or no write permission (i.e. always).
* Cut becomes Copy when running or no write permission.
* Paste disabled when running or no write permission.
Also discovered other restrictions needed to be added:
Disables all edits/interactions when running or no write permissions except:
* Button enabled when running, disabled if no write permissions.
* Switcher enabled whether running or not, disabled if no write permissions.
* TextField send button only enabled when running, disabled if no write permissions.
Solidity/Java module:
* Code is read only when running or no write permissions.
* Edit/Apply/Deploy disabled when running or no write permissions.
Also:
* Adds support …

[PLATFORM-1051] Disable custom module interactions when read-only.

---

app/src/editor/shared/components/modules/Table.jsx

Following up on an old but still relevant ticket: https://streamr.atlassian.net/browse/PLATFORM-703
Timestamps in tables are now consistent with how they are shown in the Marketplace Stream Preview Table.

[PLATFORM-703] Table timestamp formatting

---

app/src/auth/utils/loginInterceptor.js
app/src/editor/canvas/components/CanvasController/index.jsx
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/index.jsx
app/src/editor/i18n/en.po
app/src/marketplace/components/ErrorPageView/index.jsx
app/src/shared/utils/withErrorBoundary.jsx

Should show error page if there's an error loading or creating a canvas, unless error is 401/403 in which case it'll redirect to login.
1. Open a canvas
2. `streamr-docker-dev stop engine-and-editor`
3. Refresh canvas
4. Should show error page
5. Go to the "create" url http://localhost/canvas/editor/
6. Should show error page
7. `streamr-docker-dev start engine-and-editor`
8. Refresh, log out and go back to canvas.
9. Should redirect you to login with a redirect back to canvas
10. Go to the "create" url http://localhost/canvas/editor/ while logged out
11. Should redirect you to login with a redirect back to create canvas page

Fix infinite retry load create canvas

---

app/src/shared/modules/entities/reducer.js
app/src/store.js
app/src/userpages/components/StreamPage/Show/ConfigureView/NewFieldEditor/index.jsx
app/src/userpages/components/StreamPage/Show/ConfigureView/index.jsx
app/src/userpages/components/StreamPage/constants.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/tests/modules/userPagesStreams/update.test.js

When the edit stream is updated into the `entities.streams`, it was *merging* the array items rather than replacing them, so if the old stream had `[field1, field2]`, then  removing `field2` would make it merge `[field1]`  with `[field1, field2]` to become `[field1, field2]` rather than `[field2]`.
Changed the update entities logic to it never merges array items, and added a test at the stream update level, but I'm not sure if this breaks something elsewhere that was depending on the array merge behaviour. No tests break but that's not very reassuring because the current userpages test suite is so heavily mocked out that the tests there don't really verify anything particularly insightful about the the state of the app actually working.
1. Add 2 fields to a stream
2. Save and Exit stream …

[PLATFORM-1110] Ensure stream fields are replaced rather than merged.

---

app/src/editor/shared/components/modules/Table.jsx
app/src/userpages/components/StreamPage/List/index.jsx

Storybook seems broken because `Table` editor module used `moment.tz` and the imported lib was `'moment'` instead of `'moment-timezone'`. For some reason it works elsewhere 🤷‍♂ 
I changed also stream listing to use this lib, as that was another place where `moment.tz` is used.

Use moment from moment-timezone (Fix CI)

---

app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogPermissionRow/ShareDialogPermission/index.jsx
app/src/userpages/components/ShareDialog/ShareDialogContent/ShareDialogPermissionRow/shareDialogPermissionRow.pcss

As per the ticket:
> In share dialogue, users are shown as being able to access the resource they are sharing. 
However, they cannot adjust the settings for their own user account nor remove themselves from the list, so the UI is pointless & should be removed.
Now ignores current user, only shows other users. In screenshot below, current user is tester1, canvas is shared with tester2

[PLATFORM-1106] Remove self from list of users in share dialog.

---

app/src/marketplace/components/ActionBar/SearchInput/searchInput.pcss

[PLATFORM-1123] Prevent search text being cut off at top/bottom

---

app/src/marketplace/containers/ProductPage2/CollapsedText.jsx

Prevent crash on hitting back button in product editor

---

app/src/docs/components/CanvasModuleHelp/index.jsx
app/src/docs/content/canvases/modulesBasics.mdx
app/src/shared/components/AutoScroll/index.jsx
app/src/shared/containers/RouteWatcher/index.js

Added:
- IDs for individual modules, inside the module docs.
- A few inline links to these modules inside the docs.
- Smooth scroll to hash element ID when a hash fragment is present in the URL.
I noticed that hash linking wasn't working that well out of the box.. looked into it and it seems to compete with our Autoscroll measures, which ensure that page navigations render at the top of the new page.
To test, visit: http://localhost/docs/module-reference/time-series#roundtostep

[DOCS-100] Hash link scrolling

---

app/src/shared/components/DropdownActions/index.jsx
app/src/shared/components/Tile/index.jsx
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/modules/permission/actions.js

In this PR I disable the "Share" link when a user does not have permission to share a resource. Simple as that.
FYI, I didn't spend too much time on refactoring. First let's use hooks for both Stream and Canvas listing pages and then write some fancy reusable logic for utilizing permissions.
❗️ Requesting a merge into #749.

[PLATFORM-1030] Disable share link for unsharable resources

---

app/src/docs/components/CanvasModuleHelp/canvasModuleHelp.pcss
app/src/docs/components/CanvasModuleHelp/index.jsx
app/src/docs/content/moduleReference/CountByKey-221.jsx
app/src/docs/content/moduleReference/Map_geo-214.md
app/src/docs/content/moduleReference/Split-203.md
app/src/docs/content/moduleReference/SumByKey-222.jsx

Fixes:
**Map Geo**
- remove unnecessary linebreak after "WGS84 coordinates given to the" and before  "inputs latitude and longitude" in the .md file
- line 21 in the .jsx file - remove unnecessary period at end of line (shows as double periods in docs)
**Sum by Key**
- all entries in Input sections have 2 periods at end of line. ie remove the ones in the JSX file as looks like yr adding periods programatically.
**Split Help**
- code examples have very weird spacing - maybe an unnecessary line break in between them ?
- Outputs shows "List List" ie remove the unnecessary "list"
**Expression**
- link in .md file somehow breaks out of text box
Also adds some code that defends against double full stops and doubling of name and type when they are identical (Split Help issue).

[DOCS-101] Module Ref Fixes

---

app/src/auth/utils/post.js
app/src/editor/shared/utils/api.js
app/src/shared/utils/request.js
app/test/unit/components/AuthPage/utils/post.test.js

Removes `withCredentials: true` from `utils/request.js`. This should not be needed anymore for every request we make. I believe this was added when we used cookies for authentication. Now with token based authentication we don't need this.
Everything seemed to work fine with this line removed. Can you think of anything that could possibly break because of this?
The need for this occured because some new CP endpoints are sending a wildcard CORS header `Access-Control-Allow-Origin: *` which does not work if we use `withCredentials`.

Remove withCredentials from requests

---

app/src/editor/canvas/components/Camera/state.js
app/src/editor/canvas/components/CanvasSearch.jsx
app/src/editor/canvas/components/CanvasSearch.pcss
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss

* Changes vertical spacing in toolbar dropdowns to 28px.
* Reduces vertical spacing in canvas search to 32px.
* Aligns bottom of menus to same position (mostly)
* Uses sans font for all buttons and dropdown items
* Flips checkmark in historical speed menu from left to right side
Also resolves `PLATFORM-1126`:
* Changes order and content of zoom menu to match design
* Makes zoom menu same offset and width as the zoom controls area
Also:
* Prevents camera moving when using arrow keys in toolbar dropdown menu

[PLATFORM-1064] Consistency pass on Toolbar menus

---

app/src/editor/canvas/components/Camera/index.jsx
app/src/editor/canvas/components/KeyboardShortcutsSidebar.jsx
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss
app/src/editor/canvas/hooks/useCanvasCamera.js
app/src/editor/shared/components/KeyboardShortcutsSidebar/index.jsx
app/src/editor/shared/tests/shortcuts.test.js
app/src/editor/shared/utils/shortcuts.js
app/src/shared/utils/platform.js
app/test/unit/utils/platform.test.js
app/test/unit/utils/useragents.js

Going forward we should probably use this type of thing for any shortcuts which aren't replacing built-in behaviour e.g. not for cut/copy/paste/undo
* Fixes issue with the zoom shortcuts e.g. cmd+1 not working in Safari by using a "safe" meta key combo.
* Fixes issue with undo shortcut in Safari restoring last closed tab (event wasn't being cancelled properly).
* As discussed with @mattatgit have removed the keyboard shortcuts from the dropdown menu, they only appear in the sidebar now.
Uses this table for changing the appropriate chord depending on browser/os: https://en.wikipedia.org/wiki/Access_key#Access_in_different_browsers

[PLATFORM-1127] Use platform-specific chord to trigger zoom shortcuts.

---

app/src/marketplace/components/Modal/DeployingCommunityDialog/index.jsx
app/src/marketplace/containers/EditProductPage2/DeployCommunityModal.jsx
app/src/marketplace/containers/GlobalInfoWatcher/index.jsx
app/src/marketplace/flowtype/store-state.js
app/src/marketplace/modules/global/actions.js
app/src/marketplace/modules/global/constants.js
app/src/marketplace/modules/global/reducer.js
app/src/marketplace/modules/global/selectors.js
app/src/marketplace/modules/global/services.js
app/src/marketplace/modules/global/types.js
app/src/marketplace/utils/web3.js
app/src/shared/utils/web3.js
app/test/unit/containers/GlobalInfoWatcher/GlobalInfoWatcher.test.jsx
app/test/unit/containers/WithContractProduct/WithContractProduct.test.jsx

Adds `averageBlockTime` method to estimate block mining time for community deployment (+ constant time to wait for API to start up).
To test, create a community product and deploy it.
Other changes:
- Show error message from exception in CP deploy dialog
- Removed `isWeb3Injected` and `metamaskPermission` from `global` reducer state, they didn't seem to be used for anything.

Calculate Community product deployment estimate

---

app/src/editor/canvas/components/Resizable/resizeable.stories.jsx
app/src/editor/shared/components/ModuleHeader/moduleHeader.stories.jsx
app/src/marketplace/components/ProductPage/EditorNav/editorNav.stories.jsx
app/src/marketplace/components/StreamSelector/index.jsx
app/src/marketplace/components/StreamSelector/streamSelector.pcss
app/src/marketplace/containers/EditProductPage2/CoverImage.jsx
app/src/marketplace/containers/EditProductPage2/PriceSelector.jsx
app/src/marketplace/containers/EditProductPage2/ProductDescription.jsx
app/src/marketplace/containers/EditProductPage2/ProductDetails.jsx
app/src/marketplace/containers/EditProductPage2/ProductName.jsx
app/src/marketplace/containers/EditProductPage2/ProductStreams.jsx
app/src/marketplace/containers/EditProductPage2/index.jsx
app/src/shared/components/DropdownActions/dropdownActions.pcss
app/src/shared/components/DropdownActions/index.jsx
app/src/shared/components/EditableText/editableText.stories.jsx
app/src/shared/components/ImageUpload/imageUpload.pcss
app/src/shared/components/ImageUpload/imageUpload.stories.jsx
app/src/shared/components/ImageUpload/index.jsx
app/src/shared/components/Meatball/index.jsx
app/src/shared/components/Meatball/meatball.pcss
app/src/shared/components/Onboarding/onboarding.stories.jsx
app/src/shared/components/TextControl/textControl.stories.jsx
app/stories/shared.stories.jsx
app/stories/userpages.stories.jsx

Disable editor inputs while saving is in progress. Added some `opacity: 0.5` to cover image and stream selector while disabled but inputs don't have any designed disabled state so I left it out for now.
To test, edit any product and hit save (try changing the network speed to slow to see). All inputs should be properly disabled.

[PLATFORM-1134] Disable editor inputs while saving

---

app/src/editor/shared/components/modules/Comment.jsx
app/src/editor/shared/components/modules/TextField.jsx
app/src/shared/components/EditableText/index.jsx
app/src/shared/components/TextControl/index.jsx
app/src/shared/components/TextControl/textControl.stories.jsx

The effect to update local state with prop was running recursively, causing comment module to die.
Fixed so the TextControl always uses the passed-in prop while not editing, and always uses local state when editing, copies prop to local state on focus, only fires commit when value changes.

[PLATFORM-1152] Fix comment module

---

app/src/marketplace/components/MarkdownEditor/index.jsx
app/src/marketplace/components/MarkdownEditor/markdownEditor.pcss
app/src/marketplace/components/ProductPage/CollapsedText/collapsedText.pcss
app/src/marketplace/components/ProductPage/CollapsedText/collapsedText.stories.jsx
app/src/marketplace/components/ProductPage/CollapsedText/index.jsx
app/src/marketplace/components/deprecated/ProductPageEditor/index.jsx
app/src/marketplace/components/deprecated/ProductPageEditor/productPageEditor.pcss
app/src/marketplace/containers/ProductPage/description.pcss
app/src/marketplace/containers/ProductPage/page.pcss

Styling of the generated markdown text. Note that these are not finished, just added some default styles as example:
@mattatgit Can you do a pass on these text stylings?

[PLATFORM-1149] Markdown formatting styles

---

app/src/auth/components/LogoutPage/index.jsx
app/src/marketplace/modules/categories/services.js
app/src/marketplace/modules/communityProduct/services.js
app/src/marketplace/modules/deprecated/editProduct/services.js
app/src/marketplace/modules/myProductList/services.js
app/src/marketplace/modules/myPurchaseList/services.js
app/src/marketplace/modules/product/services.js
app/src/marketplace/modules/productList/services.js
app/src/marketplace/modules/publish/services.js
app/src/marketplace/modules/purchase/services.js
app/src/marketplace/modules/relatedProducts/services.js
app/src/marketplace/modules/streams/services.js
app/src/marketplace/modules/unpublish/services.js
app/src/shared/modules/integrationKey/services.js
app/src/shared/modules/resourceKey/services.js
app/src/shared/modules/user/services.js
app/src/shared/utils/api.js
app/src/shared/utils/request.js
app/src/userpages/components/StreamPage/Show/index.jsx
app/src/userpages/components/WebComponents/StreamrWidget/index.jsx
app/src/userpages/modules/canvas/actions.js
app/src/userpages/modules/dashboard/services.js
app/src/userpages/modules/permission/actions.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/services.js
app/test/unit/utils/api.test.js

Added option to omit the authorization header from requests.
These endpoints now don't send authorization header:
- `/categories` (product list & product page)
- `/products/${id}/streams` (product page)
- `/products/` (product list)
- `/products/${id}/related` (product page)

[PLATFORM-1109] Fix permission errors on public endpoints

---

app/src/marketplace/containers/ProductController/index.jsx
app/src/marketplace/containers/ProductController/useRelatedProductsLoadCallback.js
app/src/marketplace/containers/ProductPage/index.jsx
app/src/marketplace/modules/product/actions.js
app/src/marketplace/modules/product/services.js
app/src/marketplace/modules/relatedProducts/actions.js
app/src/marketplace/modules/relatedProducts/services.js

Picking up from #788, this changes related products and product streams to send auth when logged in or if the product is not deployed.

[PLATFORM-1109] Fix permission errors on public endpoints (part 2)

---

app/src/shared/components/Meatball/index.jsx
app/src/shared/components/SortableList/SortableItem/sortableItem.pcss
app/src/shared/components/SortableList/index.jsx
app/src/shared/components/TextField/TextFieldWithActions/index.jsx
app/src/shared/components/TextField/index.jsx
app/src/shared/components/TextField/textField.pcss
app/src/userpages/components/KeyField/index.jsx
app/src/userpages/components/KeyField/keyField.pcss
app/src/userpages/components/StreamPage/Show/ConfigureView/configureView.pcss
app/src/userpages/components/StreamPage/Show/ConfigureView/index.jsx
app/src/userpages/components/StreamPage/Show/InfoView/index.jsx
app/src/userpages/tests/components/KeyField/KeyField.test.jsx
app/stories/shared.stories.jsx

Moved some actions (streamId copy, field delete) behind a meatball menu on input.
Refactored `TextField` to support providing actions array, which contains `DropdownActions.Item`s.

[PLATFORM-1142] Meatball menus for stream editor

---

app/src/userpages/components/StreamPage/Show/SecurityView/Slider.jsx

Quick little thing. `getBoundingClientRect` gives an object with zeros when the slider is invisible (mobile). `p.left` is a 0 for all positions.

Fix dupped keys in SecurityView’s slider

---

app/src/index.html

Moved before `title`, which helps ensure `charset` meta tag exists within first 1024 bytes.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset

[PLATFORM-760] Move charset declaration to top of index.html 

---

app/src/shared/components/ImageUpload/index.jsx

Fix regression from #806, need to augment `image` with `preview` instead of creating new object.

Fix image upload

---

app/src/shared/components/TextField/NumberField/index.jsx
app/src/shared/components/TextInput/index.jsx

2 bugs here:
1. Not being able to override TextInput's `onBlur` and `onFocus`, and
2. `NumberField` not pushing changes to its parents when requested (unable to override `onChange`).
Both fixed.
Other known issues:
`+` and `-` buttons on the `NumberField` don't trigger `onChange`.

[PLATFORM-1186] Fix partition field

---

app/src/shared/components/FormControl/formControl.pcss
app/src/shared/components/TextField/index.jsx
app/src/shared/components/TextInput/index.jsx
app/src/shared/i18n/en.po
app/src/userpages/components/KeyField/keyField.pcss
app/src/userpages/components/SplitControl/splitControl.pcss
app/src/userpages/components/StreamPage/ConfirmCsvImportDialog/confirmCsvImportDialog.pcss
app/src/userpages/components/StreamPage/ConfirmCsvImportDialog/index.jsx
app/src/userpages/components/StreamPage/Show/HistoryView/historyView.pcss
app/src/userpages/components/StreamPage/Show/HistoryView/index.jsx
app/src/userpages/i18n/en.po
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js

Add unit selection for storage period (this still gets stored as days on the backend).
Also did some fixes for CSV upload process. I removed invisible toast notifications (because of modal) and moved the error messages to the input element instead.
This seems to include same fixes Juha implemented in https://github.com/streamr-dev/streamr-platform/pull/808 already but they shouldn't be an issue.

[PLATFORM-1144] Add unit support for storage days

---

app/src/editor/canvas/components/Canvas.jsx
app/src/editor/canvas/components/CanvasController/Run.jsx
app/src/editor/canvas/components/CodeEditor/CodeEditorWindow.jsx
app/src/editor/canvas/components/ConsoleSidebar.jsx
app/src/editor/canvas/components/ConsoleSidebar.pcss
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/Module.pcss
app/src/editor/canvas/components/ModuleRenderer/ModuleRenderer.stories.jsx
app/src/editor/canvas/components/ModuleRenderer/index.jsx
app/src/editor/canvas/components/ModuleRenderer/useModule.js
app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/canvas/components/Toolbar.jsx
app/src/editor/canvas/components/Toolbar.pcss
app/src/editor/canvas/index.jsx
app/src/editor/canvas/index.pcss
app/src/editor/canvas/state/index.js
app/src/editor/canvas/state/messages.js
app/src/editor/canvas/tests/copyPaste.test.js
app/src/editor/canvas/tests/state.test.js
app/src/editor/i18n/en.po
app/src/editor/shared/components/Sidebar/sidebar.pcss
app/src/editor/shared/utils/bounds.js
app/src/shared/components/SvgIcon/index.jsx

Following a discussion with Matt, this sidebar now only contains validation messages rather than validation messages and a log of the notifications sent, at least for this first version. It wasn't immediately clear how the validation messages should/could work within an event log.
Main motivation for this feature is to start being able to help users with common issues e.g. selecting a stream with no fields configured. Realtime log much lower value than being able to provide these messages.
Needs some additional design feedback e.g. for the message grouping headers, which I will collect from Matt if/when the PR deploys.
Added frontend "validation" for:
* Stream module with no stream selected.
* Stream module with a stream selected but that stream has no fields configured.
* Also grabbed …

[PLATFORM-1145] Canvas message log sidebar

---

app/webpack.config.js

I would argue that they don't bring enough value given this is an English app.
**Before:**
**After:**

[PLATFORM-1193] Drop momentjs locales from the build

---

.travis.yml
app/travis_scripts/deploy-docker.sh

Currently tagged production builds are failing, 
Problem seems to be:
> "$OWNER/$IMAGE_NAME:$TRAVIS_TAG" Travis Tag doesnt have a value
> Error parsing reference: "streamr/platform:" is not a valid repository/tag: invalid reference format
https://github.com/streamr-dev/streamr-platform/blob/development/app/travis_scripts/deploy-docker.sh#L25
This PR tests if it's meant to be: `TRAVIS_TAG` -> `TAG`
Example:
https://github.com/streamr-dev/data-api/blob/515c008f4a7d25f73daf1691924a7cc3d774c5ec/.travis_scripts/deploy_docker.sh
Hopefully the echos will indicate whether this is right or not, otherwise, try it in production? 😅

[PLATFORM-1207] Docker versioning fix

---

app/src/editor/canvas/components/Toolbar/Toolbar.pcss
app/src/editor/canvas/components/Toolbar/index.jsx
app/src/editor/dashboard/components/Toolbar.jsx

I'd like to make a couple of structural changes to the toolbar; compact it and make it more readable. A lot is going there and the first step is to give it a folder and keep related (future) components close together.
Opening this PR to avoid unreadable diffs in the near future. Baby steps!
cc @timoxley

Give canvas toolbar its own folder

---

app/src/userpages/components/StreamPage/Show/KeyView/index.jsx
app/src/userpages/components/StreamPage/Show/index.jsx

In this PR I make the app notify about key loading failures, altho I'm not sure if this is the best way. Normally it wouldn't be a failure. It simply wouldn't show (?) sections a user can't modify, I guess.
Any suggestions on how to make it better?

[PLATFORM-1189] Handle key loading failures

---

app/src/editor/canvas/components/Toolbar/Toolbar.pcss
app/src/editor/canvas/components/Toolbar/ToolbarInner.jsx
app/src/editor/canvas/components/Toolbar/ToolbarLayout.jsx
app/src/editor/canvas/components/Toolbar/index.jsx
app/src/editor/dashboard/components/Toolbar.jsx
app/src/editor/dashboard/components/Toolbar.pcss

In this PR I define `ToolbarLayout` component that defines left, center and right "sides" of the toolbar with the following behaviour:
- both left and right have the same width as far as it's possible,
- the one in the center takes as much space as the "start/stop" button group itself needs, that's it.
It's quite nice and flexible.
I used `styled-components` in this one. It's something I'm trying out. lmk if you have strong opinions against it. Otherwise I'll roll with that. 💃

[PLATFORM-1166] Editor's toolbar rearranged for better resize behaviour

---

app/src/app/index.jsx
app/src/marketplace/components/ErrorPageView/index.jsx
app/src/marketplace/components/NewProductPage.jsx
app/src/marketplace/components/ProductTypeChooser/index.jsx
app/src/marketplace/containers/CreateProductModal/createProductModal.pcss
app/src/marketplace/containers/CreateProductModal/index.jsx
app/src/routes/definitions.json
app/src/userpages/components/LoadingIndicator/index.jsx
app/stories/marketplace.stories.jsx

Instead of creating products directly in `CreateProductModal` we now do it in `NewProductPage` component. It's a page-like component that comes with an endpoint – `/core/products/new`. This way if the product creation fails for a 403/401-reason the app takes us to the login page and, after successful login, takes us back to the product creator – plays really well with the interceptor logic we have for general unauthorized access.
If the backend creation fails for a non-auth reason the user is gonna see the generic error page instead of previous nothing.
It's subjective, of course, but I feel like this way is also much cleaner.

[PLATFORM-1187] Redirect back to the creator after successful login

---

app/src/shared/utils/diagnostics.js

Adds the version for `streamr-client` and all other package version info to `streamr.info()`. Handy for staging/production debugging.

Extend streamr.info()

---

app/src/marketplace/components/Modal/ChooseAccessPeriodDialog/chooseAccessPeriod.pcss
app/src/marketplace/components/Modal/ChooseAccessPeriodDialog/index.jsx
app/src/marketplace/components/Modal/PurchaseSummaryDialog/index.jsx
app/src/marketplace/components/Modal/PurchaseSummaryDialog/purchaseSummaryDialog.pcss
app/src/marketplace/containers/ProductPage/PurchaseModal.jsx
app/src/marketplace/i18n/en.po
app/src/shared/components/Dialog/dialog.pcss
app/stories/modal.stories.jsx

Mainly changes to **'Complete your purchase'** some tweaks to **'Choose your access period'** too. Tested with and without CP flag. 
**Complete your purchase (desktop design)**
**Complete your purchase (desktop implemented)**
**Complete your purchase (mobile implemented)**
**Complete your purchase (mobile design)**

[PLATFORM-1225] Purchase modal styling updates

---

app/src/userpages/components/ProductsPage/index.jsx

Before in staging:
After update (with or without `COMMUNITY_PRODUCTS` flag):

[PLATFORM-1196] Fix inconsistent styling in Core > Products

---

app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx

Fixes a bug where cover images added to Community Products do not show in the deploy onboarding modal unless the user has clicked Save & exit at least once.
To test:
- Create a new community product
- Input some info on all fields and upload a cover image
- Click continue to deploy the community
Result:
Uploaded image is shown in the modal preview.

[PLATFORM-1231] Fix cover image not appearing in Community Products deploy process modal

---

app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/i18n/en.po
app/src/userpages/utils/constants.js

Added "Recent" default sort option. Also "Published" and "Drafts" (renamed from "Draft") are sorted by the `lastUpdated` field. 
For purchases, we don’t have the information when the purchase was made, only when the subscription ends so left that as it is for now.

[PLATFORM-1238] Add a "Recent" sort option to Core Products view

---

app/src/marketplace/containers/EditProductPage/BeneficiaryAddress.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.jsx
app/src/shared/components/ActionsDropdown.jsx
app/src/shared/components/Ui/Text/SelectAllOnFocusDecorator.jsx
app/src/shared/hooks/useAccountAddress.js

I created another hook – `useAccountAddress`. It returns the address of the current eth account. This way may be different to what we used to do for the previous version of the creator. I didn't want to spend too much time digging that up.
lmk if you have any suggestions!
Demo:

[PLATFORM-1188] Pre-fill recipient ETH address

---

app/src/shared/components/Tile/tile.pcss

In this PR I make sure image wrapper itself is 200px so that enough space is preserved for the actual thumbnail (before it loads).

[PLATFORM-1217] Preserve space for thumbnails

---

app/src/shared/components/TimeSeriesGraph/timeSeriesGraph.stories.jsx

This way graphs are shown always for the same date range. It fixes the “new day, new non-empty chromatic diff” issue.

[PLATFORM-1257] Freeze TimeSeriesGraph’s S/B stories in time

---

app/src/marketplace/modules/dataUnion/services.js

This will fix error we sometimes get when adding joinPartStream permissions. Firing `POST` requests to `/permissions` can result in a race condition on the backend and fail the request with no reason. Adding permissions in series fixes this.

Add joinPartStream permissions in series instead of parallel

---

app/src/app/index.jsx
app/src/marketplace/containers/EditProductPage/BeneficiaryAddress.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.pcss
app/src/marketplace/containers/EditProductPage/ProductEditorDebug.jsx
app/src/marketplace/containers/EditProductPage/beneficiaryAddress.pcss
app/src/marketplace/i18n/en.po
app/src/shared/components/SvgIcon/index.jsx

This adds different layout for standard products price setting:
Design: https://share.goabstract.com/53ce3bc8-b8fb-49c8-9859-84c0485e96f0?mode=design&sha=8e5e8db7de798d4970de1594ea92ea8f22776f34
Data union product remains the same:
Design: https://share.goabstract.com/f110e1ef-fad8-481d-ba62-5c3f27175290?mode=design&sha=8e5e8db7de798d4970de1594ea92ea8f22776f34

[PLATFORM-1228] Improve the layout of Set Price section for standard products

---

app/src/editor/shared/tests/ModuleSubscription.test.jsx
app/src/editor/shared/tests/Subscription.test.jsx
app/src/shared/components/Subscription/index.jsx

Adds a test that checks module data is flowing on a canvas that has been restarted, based on this report by @fonty1: https://github.com/streamr-dev/streamr-platform/pull/735#issuecomment-547766988
Seems to fail currently. 
WIP

Test restarting canvas. WIP

---

app/src/marketplace/i18n/en.po
app/src/shared/components/ImageUpload/imageUpload.pcss
app/src/shared/components/ImageUpload/imageUpload.stories.jsx
app/src/shared/components/ImageUpload/index.jsx

Minor fix to Avatar upload responsive view (line break)
Desktop:
Tablet:
Mobile:

[PLATFORM-960] Fix image upload responsive text

---

app/src/userpages/components/ProfilePage/ChangePassword/changePassword.pcss
app/src/userpages/components/ProfilePage/ChangePassword/index.jsx
app/src/userpages/i18n/en.po
app/stories/modal.stories.jsx

Adds responsive view for the password change modal.
Desktop:
Mobile:
Forgot password link doesn't seem to work, though. @mondoreale Any ideas where it should lead?

[PLATFORM-959] Fix password change layout on mobile

---

app/src/userpages/components/PermissionKeyField/PermissionKeyFieldEditor/index.jsx
app/src/userpages/components/PermissionKeyField/index.jsx
app/src/userpages/components/PermissionKeyField/permissionKeyField.pcss
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/integrationKeyList.pcss
app/src/userpages/components/ProfilePage/ProfileSettings/profileSettings.pcss
app/src/userpages/components/StreamPage/Show/KeyView/PermissionCredentialsControl/permissionCredentialsControl.pcss
app/src/userpages/i18n/en.po

Address spacing between various `KeyField` component fields.
Profile Eth keys:
Profile Api keys:
Stream Api credentials:
Also fixed profile form spacing:

[PLATFORM-1247] Fix KeyField component margins

---

app/src/marketplace/containers/ProductPage/PurchaseModal.jsx

Wait states were not being shown because of wrong prop names.
> Also setting the allowance higher than the current allowance should reset the allowance to zero first and then set the correct allowance. 
Setting a DATA allowance, and then setting higher allowance works ok (reset before setting again). DAI doesn't work at least locally due to this code returning always `0` even after setting an allowance:
```js
export const getMyDaiAllowance = (): SmartContractCall<BN> => {
const web3 = getWeb3()
return web3.getDefaultAccount()
.then((myAddress) => call(daiTokenContractMethods().allowance(myAddress, marketplaceContract().options.address)))
.then(fromAtto)
}
```
Let's test in staging, see if it works.

[PLATFORM-1268] Fix allowance dialog wait states

---

app/src/marketplace/containers/EditProductPage/index.jsx

Hide editor debug unless DATA_UNIONS flag is present

[PLATFORM-1197] Remove Community Product debug info from editor

---

app/src/marketplace/containers/ProductPage/SubscriberGraph.jsx
app/src/marketplace/modules/contractProduct/services.js
app/src/shared/components/TimeSeriesGraph/index.jsx
app/src/userpages/components/ProductsPage/Stats/index.jsx

Adds missing subscriber graph for data union stats page.
It shows a graph of subscriptions read from `Subscribed` events of the marketplace contract. The loading state is just a white spinner currently. We probably want something else there.
You can test the graph by creating a data union (+deploy & publish) and buying the product from marketplace.

[PLATFORM-1201] Add subscriber graph

---

app/src/marketplace/components/StreamPreviewPage/StreamLivePreview/index.jsx
app/src/shared/components/Button/index.jsx
app/src/userpages/components/StreamPage/Show/PreviewView/index.jsx
app/src/userpages/components/StreamPage/Show/PreviewView/previewView.pcss
app/src/userpages/i18n/en.po

Included stream data live preview table with empty rows when there's no data in the stream.
Also tweaked the intro text for preview section to include docs link. I had to revert the description text to previous version since Abstract (still) has wrong text for the preview section (there's no possibility to configure fields there). I remember getting this current version from Matt some time ago.
Details here: https://streamr.atlassian.net/browse/PLATFORM-1219
What do you think about including the docs link to the section description even if there's data in the stream? I included it because otherwise there would a noticeable "bump" in the UI when data starts to flow.

[PLATFORM-1219] Fix live preview to show empty table if there's no data

---

app/src/auth/components/ForgotPasswordPage/index.jsx
app/src/userpages/components/ProfilePage/ChangePassword/index.jsx

Forgot password link in user profile (change password dialog) wasn't working because the route wasn't accessible to logged in users. Back link is shown if there is a url parameter, otherwise works as before.

[PLATFORM-1262] Broken "Forgot password?" link in Change password dialog

---

app/src/shared/utils/request.js

Product pages for non-existing products (both view and edit) take you to /404. This is a shared behaviour between different resources: canvases, dashboards, and now products.
There's a ticket – [`PLATFORM-1283`](https://streamr.atlassian.net/browse/PLATFORM-1283) – for the actual redirections (which I consider to be an issue).

[PLATFORM-1263] Show 404 page for non-existing products

---

app/src/userpages/components/KeyField/index.jsx
app/src/userpages/components/KeyField/keyField.pcss
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/index.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/integrationKeyList.pcss

I fix 2 things here.
First one is this vertical alignment issue:
I do it with class, naturally, in 0d6d5fb! 💃 
The second is name's ability to adopt to available space – subject of [`PLATFORM-1279`](https://streamr.atlassian.net/browse/PLATFORM-1279). Here's how it's gon' be now:
I preserve a round 8px of space between the balance and the name.

[PLATFORM-1279] Fix overflowing identity names

---

app/src/marketplace/containers/ProductPage/SubscriberGraph.jsx
app/src/shared/components/TimeSeriesGraph/index.jsx

Subscriber graph now draws a zero line when there are no purchases for given product. Previously it would render nothing.

[PLATFORM-1271] Add support for empty subscriber graph

---

app/src/shared/components/EditableText/index.jsx

Fixes this bug in the editor:
**Steps to reproduce**
* Edit canvas
* Add any stream module with stream search
* Type to search stream, select one
* Click outside of module to blur text field
* Focus stream field, start typing
**Expected outcome**
Stream list is refreshed with new results
**Actual outcome**
Only the current result (= stream selected from first search results) is shown 
Fix was to pass the `immediateCommit` to `EditableText` which was `false` by default.

[PLATFORM-1269] Fix stream selector search

---

app/src/marketplace/components/Modal/DeployingDataUnionDialog/index.jsx
app/src/marketplace/components/ProductTypeChooser/index.jsx
app/src/marketplace/containers/EditProductPage/ProductEditorDebug.jsx
app/src/marketplace/containers/EditProductPage/tests/productState.test.js
app/src/marketplace/containers/Products/index.jsx
app/src/marketplace/i18n/en.po
app/src/marketplace/modules/dataUnion/services.js
app/src/marketplace/utils/constants.js
app/src/marketplace/utils/product.js
app/stories/modal.stories.jsx
app/test/unit/utils/product.test.js

Renames product type `COMMUNITY` to `DATAUNION`. This value will be sent to the API when e.g. creating products.
Also calls to `/communities` have been renamed to use `/dataunions` instead.
Needs https://github.com/streamr-dev/engine-and-editor/pull/736 to work.

[PLATFORM-1276] Rename to use new data union endpoints

---

app/package-lock.json
app/package.json
app/src/userpages/tests/components/KeyField/KeyField.test.jsx
app/src/userpages/tests/modules/canvas/actions.test.js
app/src/userpages/tests/modules/canvas/reducer.test.js
app/src/userpages/tests/modules/dashboard/actions.test.js
app/src/userpages/tests/modules/permission/actions.test.js
app/src/userpages/tests/modules/userPagesStreams/actions.test.js

Use `toMatchObject` instead of `toEqual` so that new property `response` in error objects will not cause problems.
I migrated these files to use `expect` instead of `assert-diff` so that one day we only have one assertion library. Also removed library `expect` from `package.json` because it's part of jest already.

Fix broken test cases

---

app/src/marketplace/components/Modal/NoBalanceDialog/index.jsx

I didn't want to spend too much time getting to the root of the problem since this will fix itself shortly, once MP2 is released. This fix will avoid the hard crash when there's no DATAcoin in the wallet. 
https://streamr.atlassian.net/browse/PLATFORM-1289

[PLATFORM-1289] Avoid hard crash when no data coin on deprecated Purchase Modal

---

app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/List/streamsList.pcss
app/src/userpages/i18n/en.po

Current implementation shows a meatball menu for every stream, always. Design shows a meatball menu only for the currently hovered stream, with a separate (darker) state when the icon itself is hovered
Prototype:
Implementation:

[PLATFORM-1292] Bring Core Stream List hover states into line with design

---

app/src/marketplace/flowtype/product-types.js
app/src/marketplace/flowtype/store-state.js
app/src/marketplace/modules/myPurchaseList/actions.js
app/src/marketplace/modules/myPurchaseList/reducer.js
app/src/marketplace/modules/myPurchaseList/selectors.js
app/src/marketplace/modules/myPurchaseList/types.js
app/src/marketplace/modules/product/selectors.js
app/src/shared/modules/entities/schema.js
app/src/shared/test/modules/entities/reducer.test.js
app/src/userpages/components/PurchasesPage/index.jsx
app/test/unit/containers/ProductPage/ProductPage.test.jsx
app/test/unit/modules/myPurchaseList/actions.test.js
app/test/unit/modules/myPurchaseList/reducer.test.js
app/test/unit/modules/myPurchaseList/selectors.test.js
app/test/unit/modules/product/selectors.test.js

This adds a default "Recent" filter to purchases page (date fields are exposed in PR https://github.com/streamr-dev/engine-and-editor/pull/739, make sure you update the env before testing).
The PR also refactors how subscriptions are handled, I noticed that if a product is purchased with different accounts, the products end up showing up twice (+ an error in console about duplicate keys). I've changed the logic to reduce the subscription list to only unique products so that the subscription `lastUpdated` and `endsAt` times are updated to the most recent one.

[PLATFORM-1286] Purchases page - Add recent sort option, refactor subscription handling

---

app/src/shared/components/Button/button.stories.jsx
app/src/shared/components/Button/newButton.pcss
app/stories/shared.stories.jsx

I took a stab at the stories for buttons today. It exposed the bug from [`PLATFORM-1298`](https://streamr.atlassian.net/browse/PLATFORM-1298) and I fixed it in 33fed94.

[PLATFORM-1298] Outline button style fixes

---

app/src/marketplace/components/MarkdownEditor/index.jsx
app/src/marketplace/components/ProductPage/EditorNav/editorNav.stories.jsx
app/src/marketplace/components/ProductPage/EditorNav/index.jsx
app/src/marketplace/components/ProductPage/EditorNav/test/editorNav.test.jsx
app/src/marketplace/containers/EditProductPage/BeneficiaryAddress.jsx
app/src/marketplace/containers/EditProductPage/CoverImage.jsx
app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/marketplace/containers/EditProductPage/EditorNav.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.jsx
app/src/marketplace/containers/EditProductPage/ProductDescription.jsx
app/src/marketplace/containers/EditProductPage/ProductDetails.jsx
app/src/marketplace/containers/EditProductPage/ProductName.jsx
app/src/marketplace/containers/EditProductPage/ProductStreams.jsx
app/src/marketplace/containers/EditProductPage/state.js
app/src/marketplace/containers/EditProductPage/tests/productState.test.js
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/test/validationContext.test.jsx

Change editor validation so that errors are only shown when the user publishes a product.
New product with name set:
When user returns to edit a draft, the completed sections are shown as blue ticks, otherwise empty:
When user clicks "Publish" and there are incomplete sections:
When editing a published product, the update icon is shown:
Other notes:
- Inline errors shown only after publish clicked
- Added unit tests for validation context and product nav component
@mattatgit I left it so that the errors are also triggered when deploying a data union which happens before publish. What do you think, should we show error only when publishing?

[PLATFORM-1293] Product editor error handling

---

app/src/userpages/components/ProductsPage/index.jsx

I used `Product#state` to indicated ongoing deployment. I ported the previous behaviour (the 1 I fix here) from before #907 but never understood why fetching members indicates deploying.
@juhah @tumppi can you confirm that's the correct way?

[PLATFORM-1300] Fix deploying badge

---

app/src/shared/components/TimeSeriesGraph/index.jsx
app/src/shared/components/TimeSeriesGraph/timeSeriesGraph.stories.jsx

Small fixes to TimeSeriesGraph component.
1. Y-axis values are now better aligned with the XYPlot container. This will result in better use of 
space and it also scales as numbers grow larger.
1. X-axis tick labels are now aligned on right side of the tick. Previously they were centered.
1. Ticks are also now a bit shorter (6px as designed) and will be rendered only towards outside of the graph. 
I also removed day names (all but the first) for the week view as designed.
Old:
New:

[PLATFORM-1301] Graph tweaks

---

app/src/userpages/components/StreamPage/Show/index.jsx

> Currently the status query fails often due to cassandra problems. I noticed that when that happens, the stream page does not display, instead it stays white with only the spinner showing.
This fixes the issue when stream status query fails, stream page does not display at all.
You can test this by blocking the stream status request or temporarily replacing the `getStreamStatus` method with:
```js
export const getStreamStatus = (id: StreamId): ApiResult<StreamStatus> => new Promise((resolve, reject) => {
reject(new Error('fail'))
})
```
I will hotfix this separately to production once approved.

[PLATFORM-1304] Fix stream page load when stream status query fails

---

app/src/userpages/modules/userPageStreams/actions.js

> On the stream list page, if one status query fails, the whole process of fetching statuses will be interrupted and no further queries are made. Is this a bug or a feature? IMO it would be better to continue fetching the statuses despite the failure, as the results for different streams are independent.
Similar to #925, continue if a stream status query fails in stream list.

[PLATFORM-1306] Ignore error from individual stream status query and continue

---

app/src/app/index.jsx
app/src/userpages/components/ProductsPage/index.jsx

This changes the features hidden under `DATA_UNIONS` flag so that only the data union creation is disabled if flag is not present. Otherwise they are enabled with `NEW_MP_CONTRACT` flag. 
This way we can test the existing data union products in staging but not enable users to create them themselves.

Hide data union creation under DATA_UNIONS flag

---

app/src/app/index.jsx
app/src/userpages/components/ProductsPage/index.jsx

> we are sending the owner to 2 different links depending if they access the product via their products page or Marketplace
Fixes editor route in production.

Fix product edit route

---

app/src/app/Marketplace.jsx
app/src/app/Userpages.jsx
app/src/app/index.jsx
app/src/marketplace/components/ActionBar/index.jsx
app/src/shared/components/Tile/index.jsx
app/src/shared/test/components/ProductTile/ProductTile.test.jsx
app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/tests/components/ProductsPage/CreateProductButton.test.jsx
app/src/userpages/tests/components/ProductsPage/MenuItems.test.jsx
app/test/unit/app/Marketplace.test.jsx
app/test/unit/app/Userpages.test.jsx
app/test/unit/components/ActionBar/CreateProductButton.test.jsx

I separated the `UserpagesRouter` and `MarketplaceRouter` for easier testability and added some tests around components that depend on the `NEW_MP_CONTRACT` flag. Hopefully this will prevent some bugs from leaking in to production before we get rid of the flags.

Add tests around NEW_MP_CONTRACT dependent routes

---

app/src/marketplace/components/PriceField/index.jsx
app/src/marketplace/components/PriceField/priceField.pcss
app/src/marketplace/components/SetPrice/index.jsx
app/src/marketplace/components/SetPrice/setPrice.pcss

Fixing [`PLATFORM-1254`](https://streamr.atlassian.net/browse/PLATFORM-1254) in here.
SetPrice component layout is consistent across browsers. 3000 words:
**Firefox**
**Chrome**
**Safari**

[PLATFORM-1254] Fix SetPrice's layout on Firefox

---

app/src/auth/components/LogoutPage/index.jsx
app/src/shared/hooks/useFailure.js
app/src/shared/hooks/useOnMount.js

`LogoutPage` doesn’t render anything. It either throws an error or logs out and our auth stuff takes care of the redirecting. ✨ 
In this PR I introduce `useFailure` hook. It's a shortcut for going from a promise rejection to an exception catchable by error boundary. I use it in #943 so this one goes live first, ideally.
@fonty1 @tumppi it's a small PR. The smallest I could arrange. Trying to move fast with small puzzles. Should be easy to look through.
Cheers!

Refactor LogoutPage “convey” component

---

app/src/shared/utils/constants.js

This PR gives some extra breathing room for transactions that could reasonably approach their gas limit.

[PLATFORM-1319] Higher gas limits

---

app/src/editor/shared/tests/ModuleSubscription.test.jsx

Makes ModuleSubscription tests less likely to fail if backend is feeling sluggish.

Relax ModuleSubscription Tests

---

app/src/auth/components/SessionProvider/index.jsx
app/src/auth/tests/SessionProvider.test.jsx
app/src/marketplace/containers/ProductPage/index.jsx
app/src/marketplace/containers/deprecated/ProductPage/index.jsx
app/src/shared/modules/user/reducer.js
app/src/shared/test/modules/user/reducer.test.js
app/test/unit/containers/ProductPage/ProductPage.test.jsx

Adds a date to localstorage variable whenever the login token is set. Token is not sent if the date is not set or **more** than 6 hours old (typo edited, was: ~less~). This value should be the same as returned from the login enpoint. This value is not exposed by the StreamrClient API, though, so I set it in the frontend. It will still redirect to login if the sent token is bad but that can't be really helped.

[PLATFORM-1316] Workaround for Marketplace expired token

---

app/src/marketplace/components/Modal/CropImageModal/cropImageModal.test.jsx
app/src/marketplace/components/Modal/CropImageModal/index.jsx

From issue description:
> Surprisingly this seems ok in the old product editor (perhaps we are compressing) before sending? In the new editor, when I uploaded an image 4.2mb large, the server returns 413 but no UI warnings:
After investigating this issue, it seems to happen in the new editor because we use the cropping tool to create a new image whose file size is not necessarily dependant on the original image. Also there are differences between browsers, see: https://stackoverflow.com/questions/9773154/canvas-todataurl-increases-file-size-of-image
So the old editor works because we submit the original image. The new editor will also give an error if you try to give it an image that is over 5MB.
I changed the crop tool to use `canvas.toBlob` instead of `canvas.toDataUrl` and introduced a …

[PLATFORM-1312] When an image is uploaded that is too large, it silently fails

---

app/src/shared/contexts/StreamrClient/index.jsx

Always fetch apiKey if we don't currently have it. Should fix missing auth credentials issues on login.
A bug exists where client tries to subscribe without sending auth keys.
To reproduce bug reliably:
1. Create a stopped Clock->Table canvas.
2. Log out.
3. Log in.
4. Open Canvas
5. Click Run
Canvas won't appear to start and you will see an error saying something like "user doesn't have permission to subscribe to stream X"
Issue seemed to be that the apiKey is fetched automatically by some other component in the app if the user was already logged in when the app started. On the initial login however, the apiKey is not there, and the client doesn't go fetch it.  This is why a refresh fixes it and why we don't see it all the time, because we're usually developing on a page after already …

Fetch API Key for Client if it doesn't have it already.

---

.travis.yml
app/src/editor/shared/tests/ModuleSubscription.test.jsx
app/test/test-utils/setupTests.js

Minor change but Node 8 is very old and no longer maintained:
Node 10 should be faster too so CI install/builds/tests might be a little faster?

Use Node 10 on Travis

---

app/src/marketplace/components/StreamSelector/index.jsx
app/src/marketplace/components/StreamSelector/streamSelector.pcss
app/src/marketplace/components/StreamSelector/streamSelector.stories.jsx

While investigating https://streamr.atlassian.net/browse/PLATFORM-1324 I noticed there is no styling for Stream selector load state. I added one like this (disabled & center text replaced):
The actual problem itself seems to be backend related (`/streams` endpoint doesn't return more than 1000 results).

[PLATFORM-1324] Add loading state to stream list

---

app/src/marketplace/components/SetPrice/index.jsx
app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.test.jsx
app/src/marketplace/containers/ProductController/tests/useEditableProductActions.test.jsx
app/src/marketplace/containers/ProductController/useEditableProductActions.js

In this PR when "Fix price in fiat" is enabled `priceCurrency` turns into $ and `pricePerSecond` represents $ not DATA. Previously it was \*always\* converted to DATA thus "fixed" was quite loose.
Wrote a buncha specs for it. Hope they're any good (lmk!)
—
_Post-feedback TODO_

[PLATFORM-1330] Fix price conversion in SetPrice component + specs

---

app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/tests/ValidationContextProvider.test.jsx
app/src/marketplace/containers/ProductController/tests/useEditableProductActions.test.jsx
app/src/marketplace/containers/ProductController/useEditableProductActions.js
app/test/unit/utils/product.test.js

Fixes a bug when uploading a new cover image to a published product did not mark it as republishable.
To test:
1) Edit a published product
2) Upload a new cover image
Navigation icon should change to "update" icon and toolbar button to “Republish”.

[PLATFORM-1332] Cover image republish fix

---

app/src/marketplace/containers/EditProductPage/tests/usePublish.test.jsx
app/src/marketplace/containers/EditProductPage/usePublish.js
app/src/marketplace/modules/createContractProduct/services.js
app/src/marketplace/utils/smartContract.js
app/src/shared/utils/constants.js
app/test/unit/modules/createContractProduct/services.test.js
app/test/unit/utils/smartContract.test.js

Fixes failing `updateContractProduct` call when updating published product's price. Also added some checks to publish dialog so that it shows the error even when the transaction fails before it has started, before it just got stuck while waiting for progress.

[PLATFORM-1348] Fix updating contract product price failure

---

app/src/editor/shared/tests/Client.test.jsx
app/src/editor/shared/tests/ModuleSubscription.test.jsx
app/src/editor/shared/tests/Subscription.test.jsx
app/src/shared/contexts/StreamrClient/index.jsx

We should use the same session token that we are using for HTTP requests to init the StreamrClient instead of API key.
Note: There is another `StreamrClientProvider` under `userpages` which will be removed in #969.

[PLATFORM-1344] Use session token to initiate the `StreamrClient` instead of API key

---

app/package-lock.json
app/package.json

Quick one!
Thought we're already there, tbh. 5.1.0 introduces `useParams`, `useLocation`, `useHistory`, and `useRouteMatch` hooks. It's very convenient.
—
RRD's changelog:
https://github.com/ReactTraining/react-router/releases

Update react-router-dom to 5.1.0+

---

app/src/marketplace/modules/dataUnion/services.js

Removes old code needed for transition phase when moving from `communities` to `dataunions`. Currently production is ahead of development environment so this cannot be merged without breaking local environment.
Let's wait until `dev` tag of `data-union-server` is up to date so this works for both production and development.

Fix /dataunions response to use dataunions instead of communities

---

app/src/auth/components/SessionProvider/index.jsx
app/src/auth/tests/SessionProvider.test.jsx
app/src/editor/shared/tests/Client.test.jsx
app/src/editor/shared/tests/ModuleSubscription.test.jsx
app/src/editor/shared/tests/Subscription.test.jsx
app/src/editor/shared/tests/utils.js
app/src/marketplace/containers/ProductPage/index.jsx
app/src/shared/contexts/StreamrClient/index.jsx
app/src/shared/utils/getAuthorizationHeader.js
app/src/shared/utils/sessionToken.js
app/src/shared/utils/sessionToken.test.js

I took a stab at refactoring our session token storage feature. Extracted `getStoredToken` and `storeToken` from `SessionProvider`, simplified them and put them in the `sessionToken` utility.
Main reason for it is that I want to be able to interact with the token directly from the e2e tests and don't wanna fight its config and import too much.
Hope you guys like it.

Refactor session token storage

---

app/src/docs/content/dataUnions/dataUnionsCore.mdx
app/src/docs/content/dataUnions/introToDataUnions.mdx
app/src/docs/content/dataUnions/joinAndWithdraw.mdx

Introduction to Data Unions
- add missing linking to Framework roles page
- added highlight for the create button
Join & Withdraw page
- add missing linking to Auth & Identity page

[DOCS-129] Add missing DU docs links

---

app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx

Small fix to extend the member limit check to include the case when the stats are not ready, ie. when the DU is in "Deploying..." state.

[PLATFORM-1389] Disable publish while DU is being deployed

---

app/src/shared/components/Table/table.pcss

Updated the shared table font:

[PLATFORM-1398] Update table header font

---

app/src/routes/definitions.json
app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/i18n/en.po
app/src/userpages/modules/transactionHistory/actions.js
app/src/userpages/modules/transactionHistory/services.js

Fixes the transaction list so that it can fetch purchases (using the new contract) and at least not crash 🙄 The trickiest part is fetching the payments coming to the user, Uniswap purchases don't show when searching with the `to` address filter. In the end I wound up using a list of the products owned by the current user to do that filtering.
The timestamp is off (showing "50 years ago") but that is the timestamp returned for the block, I suspect this is due to Parity). It's not exactly the Unix epoch but in fact sometime after, ie. timestamp is not being returned as `0`.
Buying your own product will show the money spent and received:
PR test url: http://streamr-marketplace-pr-32daf1076b2dc7e992872f2cd5919c7296efa039.s3-website-eu-west-1.amazonaws.com/core/transactions

Refactor transaction list, fix transaction fetching

---

app/src/shared/components/TOCPage/TOCNav.jsx
app/src/shared/components/TOCPage/index.jsx
app/src/userpages/components/StreamPage/View.jsx

Add truncation for read-only stream title:
Editable stream:
Profile page:

[PLATFORM-1385] Fix read-only stream title

---

app/src/marketplace/components/StreamPreviewPage/index.jsx

A permissions check seemed to trip up the Stream Editor Live Preview - reproducible in local & prod.

[PLATFORM-1425] Fix Stream Preview

---

app/src/marketplace/components/Modal/PublishTransactionProgress/index.jsx
app/src/marketplace/components/Modal/PurchaseTransactionProgress/index.jsx

Adds some comfort noise to purchase and publish modal progress bars by adding the number of steps and initial progress.

[PLATFORM-1414] Add more steps to progress bars

---

app/src/marketplace/components/ProductPage/Terms/index.jsx
app/src/marketplace/containers/EditProductPage/Editor.jsx
app/src/marketplace/containers/EditProductPage/EditorNav.jsx
app/src/marketplace/containers/EditProductPage/Preview.jsx
app/src/marketplace/containers/EditProductPage/TermsOfUse.jsx
app/src/marketplace/containers/EditProductPage/state.js
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/useEditableProductActions.js
app/src/marketplace/containers/ProductPage/Page.jsx
app/src/marketplace/containers/ProductPage/Terms.jsx
app/src/marketplace/flowtype/product-types.js
app/src/marketplace/i18n/en.po
app/src/shared/assets/images/checkbox-checked.svg
app/src/shared/assets/images/checkbox.svg

Adds terms of use section to product editor and also to product page (& preview).
Related designs:
- https://share.goabstract.com/1e34f51b-97f2-4310-a0c2-26ff6c6995b6?mode=design&sha=22fda9a67b422eb66e3a86d23687ca30a90593e5
- https://share.goabstract.com/5e6cff3f-703b-41fc-9f8a-a78630a1498c?mode=design&sha=2143b193b923e9df49dcb8dc32897fdc204a1a01
PS. I noticed that somehow after adding the terms of use section to product editor, it seems that editor always scrolls to that section when opening a product. I couldn't figure out why this is happening. Could it be related to the ScrollSpy?

[PLATFORM-1290] Terms of use

---

app/src/userpages/components/ProductsPage/Header/index.jsx
app/src/userpages/components/ProductsPage/Members/index.jsx
app/src/userpages/components/ProductsPage/Members/members.pcss
app/src/userpages/components/ProductsPage/Stats/index.jsx
app/src/userpages/components/ProductsPage/Stats/stats.pcss

Fix Stats & Members views to keep header visible while switching between them.

[PLATFORM-1409] Keep header visible while loading DU data

---

app/src/userpages/components/ShareSidebar/ShareSidebar.test.jsx
app/src/userpages/components/ShareSidebar/state.js
app/src/userpages/modules/permission/actions.js

Fixes `Invalid userId: undefined` issue reported by @fonty1 via Sentry: https://sentry.io/organizations/streamr/issues/1732638237/?project=1203154 
1. Create a stream via UI
2. Add an API Access key in stream edit
3. Save
4. Open share sidebar
5. Note no `undefined` user listed, no errors when saving

Fix streams with API keys in share sidebar

---

app/src/shared/components/HoverCopy/hoverCopy.stories.jsx
app/src/shared/components/HoverCopy/index.jsx
app/src/shared/components/SvgIcon/index.jsx
app/src/shared/i18n/en.po

Improved ETH address copy to use icons instead of text.
https://streamr.atlassian.net/browse/PLATFORM-1428

[PLATFORM-1428] Use icons instead of text for ETH address copy

---

app/src/shared/components/Tile/index.jsx
app/src/userpages/components/ProductsPage/index.jsx
app/src/userpages/i18n/en.po

When a Data Union is deployed but not published, the product tile shows 'Deployed'.

[PLATFORM-1436] Show unpublished & deployed DU status in product tile

---

app/src/userpages/components/DocsShortcuts/index.jsx

Link to DU docs was missing from userpages shortcuts:

[PLATFORM-1442] Data Unions docs link missing in Core shortcuts

---

app/src/marketplace/containers/EditProductPage/ConnectEthIdentity.jsx
app/src/marketplace/containers/EditProductPage/EditorNav.jsx
app/src/marketplace/containers/EditProductPage/PriceSelector.test.jsx
app/src/marketplace/containers/EditProductPage/tests/EditControllerProvider.test.jsx
app/src/marketplace/containers/ProductController/ValidationContextProvider.jsx
app/src/marketplace/containers/ProductController/tests/ValidationContextProvider.test.jsx
app/src/marketplace/containers/ProductController/tests/useEditableProductActions.test.jsx

Now product editor shows a validation error when user tries to deploy a data union but has no ethereum identity connected.

[PLATFORM-1434] Add validation rule for ethereum identity

---

app/src/shared/components/SortableList/index.jsx

`SortableList` uses dynamic `z-index` to keep proper order of items (for dropdown menus, IIRC). See:
Toolbars are at `z-index: 5` so 5-6th field would render above the toolbar.
**Solution**: I give sortable list's outer element `z-index: 0` which scopes layering produced by individual sortable items.

[PLATFORM-1351] Fix field list layering bug

---

app/src/docs/components/CanvasModuleHelp/index.jsx
app/src/docs/components/DocsLayout/index.jsx

Integrated `BusLine` component with `DocsLayout` so `BusStop` can now be used all over the place. Solves the issue, plus adds some extras: on-scroll hash updating, same-page click-to-scroll, etc.
@fonty1 lmk your thoughts!

[PLATFORM-1358] Scroll-to-hash for module docs

---

app/src/marketplace/containers/ProductPage/Hero.jsx

Fixes purchase button not working locally or in staging because the whitelist check is not called when the feature is not enabled 🐛

Fix broken purchase button / whitelist check

---

app/src/marketplace/modules/dataUnion/services.js

Change `joinPartStream` permissions:
- Leave `stream_share` to the user
- Don't add `stream_edit` to E&E
@hpihkala Original intention in the issue was to revoke `stream_share` from E&E but looks like `stream_share` is needed to revoke `stream_edit` and `stream_delete` from the user. Otherwise those revoke calls fail with `Cannot revoke only SHARE permission of JoinPart stream for data union 0x...`.

[PLATFORM-1457] Tweak joinPartStream permissions

---

app/src/auth/components/ForgotPasswordPage/index.jsx
app/src/auth/components/RegisterPage/index.jsx
app/src/auth/components/ResetPasswordPage/index.jsx
app/src/auth/components/SignupPage/index.jsx
app/src/auth/utils/post.js
app/src/shared/modules/user/services.js
app/src/shared/test/modules/user/services.test.js
app/test/unit/components/AuthPage/utils/post.test.js

Changes content type for endpoints from `application/x-www-form-urlencoded` to `application/json`, using the same parameters as before.
Affected pages:
- sign up
- forgot password
- register
- change password in profile
Tested locally and seemed to fix the issue.

Fix content type for auth endpoints

---

app/src/marketplace/components/ProductPage/EditorNav/editorNav.pcss

All ellipsis to overflowing text

[FRONT-15] Fix overflowing button in product editor nav

---

app/src/marketplace/containers/GlobalInfoWatcher/index.jsx
app/src/shared/modules/user/actions.js
app/src/userpages/components/ProfilePage/ProfileSettings/index.jsx
app/src/userpages/i18n/en.po

Changes email field to to be editable if user is logged in via Metamask. For normal users, email is read-only because of backend constraint.

[FRONT-6] Add editable email field for ETH users in profile

---

app/src/marketplace/containers/ProductPage/Hero.jsx

Add a check for whitelist loading so that it is only done for paid products. Otherwise it never gets loaded if Metamask is not active or account is not present.

Don't do a whitelist check on free products

---

app/src/shared/components/Tile/Summary.jsx

Fixes long product owner name overflowing.

[FRONT-48] Truncate product owner name

---

app/package-lock.json
app/package.json
app/src/shared/contexts/StreamrClient/index.jsx

Old client fails at creating streams – via `client.createStream` – i.e. for activity lists. Reason? Backend has become more restrictive about the `Content-Type` header. The old client uses `text/plain` for JSON bodies.
LMK if you know something about the new client I don't but I should. ;)

Update streamr-client: 3.1.0 → 4.1.1

---

app/src/marketplace/components/StreamPreview/index.jsx

> Live data Inspector needs to be vertically scrollable, but currently users are unable to scroll on all device breakpoints.
Add vertical scrolling to live data inspector in stream preview. To test, have some data in a stream with multiple fields and select a data point to view. The data points should all be scrollable into view (and not hidden by the toolbar in mobile).

[FRONT-94] Live data Inspector doesn't scroll

---

app/src/marketplace/containers/EditProductPage/SharedSecretEditor.jsx
app/src/userpages/components/KeyField/AddKeyField/index.jsx
app/src/userpages/components/KeyField/KeyFieldEditor/index.jsx
app/src/userpages/components/KeyField/KeyFieldEditor/keyFieldEditor.stories.jsx
app/src/userpages/components/KeyField/index.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/index.jsx
app/src/userpages/i18n/en.po
app/src/userpages/tests/components/KeyField/KeyFieldEditor/KeyFieldEditor.test.jsx

> When user goes to edit the eth account details via the meatball menu, the first field is labelled "Key name" which is incorrect.

[FRONT-96] Add separate label for KeyField name input

---

app/src/marketplace/containers/ProductController/index.jsx
app/src/marketplace/containers/ProductController/useProductLoadCallback.js
app/src/marketplace/containers/ProductPage/index.jsx

> Once a product got published users end up seeing a confirmation dialog with "Copy link" link and "View product" button. While the copied link works just fine when opened in a new tab the "View product" button takes the user to a 404 page (despite correctly linking to the product).
This bug was caused by the old product state being fetched from redux which didn't have time to clear before reloading the product and triggering that error. I moved the check to happen after reloading and only done on the product page.

[FRONT-50] "View product" button in post-publish modal takes users to the Not Found page

---

app/src/shared/components/List/list.stories.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/TransactionPage/List/index.jsx

> is it possible that such a bug could slip in during your recent table refactoring?
Fixes status icon mapping on list views, it was indeed broken when I refactored the list views 😰

[FRONT-102] Stream traffic indicator broken

---

app/src/auth/components/EthereumLogin/index.jsx
app/src/docs/content/streams/code/streams.js
app/src/marketplace/components/ProductPage/Description.jsx
app/src/marketplace/containers/ProductController/index.jsx
app/src/marketplace/containers/ProductPage/Hero.jsx
app/src/marketplace/containers/ProductPage/PurchaseModal.jsx
app/src/marketplace/containers/ProductPage/index.jsx
app/src/marketplace/i18n/en.po
app/src/marketplace/modules/contractProduct/services.js
app/src/shared/web3/web3Provider.js

I checked the `web3` Metamask provider injection and we should we quite safe with our implementation since everywhere the Web3 wrapped lib is used instead of the one provided by Metamask. I added a convenience property `metamaskProvider` to our `StreamrWeb3` object that is given to eg. Streamr client.
I made two other fixes to the product page here that I noticed while testing:
- Product page prompts immediately for Metamask if locked. I changed it so that the metamask is not prompted, if whitelisted the button will still say "Request access" but Metamask is prompted only when clicking it. If user is whitelisted, the purchase can continue - if not, it will show the email dialog
- Having a non-linked account created a new account instead of connecting the current one.

[FRONT-121] Add metamask provider, fix product page Metamask prompt

---

app/cypress/integration/StreamPage.spec.js
app/cypress/support/commands.js
app/package-lock.json
app/package.json
app/src/marketplace/modules/streams/services.js
app/src/routes/definitions.json
app/src/shared/components/Meatball/index.jsx
app/src/shared/components/StatusIcon/index.jsx
app/src/shared/components/StreamrClientProvider.jsx
app/src/shared/components/TOCPage/TOCSection.jsx
app/src/shared/flowtype/stream-types.js
app/src/shared/hooks/useLastMessageTimestamp.js
app/src/shared/utils/getClientConfig.js
app/src/shared/utils/getStreamActivityStatus.js
app/src/shared/utils/getStreamActivityStatus.test.js
app/src/userpages/components/StreamPage/Edit/PreviewView.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/List/Row.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/index.jsx
app/src/userpages/i18n/en.po
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/services.js

In this PR I replace fetching stream status via e&e with fetching it via ~~`streamr-client`~~ the API. Notes:
- `useLastMessageTimestamp` hook lets you determine the latest message timestamp.
- `getStreamActivityStatus` utility turns a timestamp in a proper `StatusIcon` instance.
- I extracted `ClientProvider` from `PreviewView` and wrapped everything in `StreamPage/index.jsx` with it (both `View` and `Edit` components) – see 773bb2c.
- Wrote a couple of new `cypress` commands so that you can, for example, publish a message to a stream (it waits for it to complete).
And a bunch of other things. Hope you guys like it. Cheers!

[FRONT-109] Fetch stream activity status through StreamrClient

---

app/src/marketplace/containers/GlobalInfoWatcher/index.jsx
app/src/shared/web3/web3Poller/web3Poller.js
app/src/shared/web3/web3Provider.js
app/test/unit/containers/GlobalInfoWatcher/GlobalInfoWatcher.test.jsx

Disables Metamask's auto reload feature that will soon be deprecated, now we handle the reload in `GlobalInfoWatcher`. We wouldn't need to necessarily reload always, just would have to make sure all places that make transaction have validated the web3 instance before usage.

[FRONT-122] Reload page on network change

---

app/package-lock.json
app/package.json
app/src/editor/shared/tests/Client.test.jsx

`streamr-client-react` no longer recreates clients on disconnection and failures. Now it's reflected in local tests.

Fix Client tests

---

app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/modules/permission/reducer.js

For color… `StreamPage/index` uses current user's permissions to render either the `View` or the `Edit` component. Before this PR closing the share sidebar caused user's own permission to be reset. `StreamPage/index` would then have to re-fetch permissions and rebuild the page. It looked strange. Lotta flashing of the loading state, etc.
This PR is a quick fix. Instead of resetting permissions I refetch them right away. I also make sure that if permissions coming from the server match the ones we currently hold we skip an update.

[FRONT-151] Reasonable permission refreshing vs Share sidebar

---

app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/shared/hooks/usePreventNavigatingAway.js
app/src/userpages/components/ShareSidebar/Sidebar.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/New.jsx

Certain areas of the app ask users to confirm a reload. `usePreventNavigatingAway` hook's here to help. I replaced all eligible instances of the same logic with the new hook.
Less code. Same effect.

usePreventNavigatingAway hook

---

app/src/shared/utils/sharing/canShareToUserId.js
app/src/shared/utils/sharing/isValidUserId.js
app/src/userpages/components/ShareSidebar/InputNewShare.jsx
app/src/userpages/components/ShareSidebar/Sidebar.jsx
app/src/userpages/components/ShareSidebar/hooks/useUserPermissionState.js
app/src/userpages/components/ShareSidebar/state.js

Doing a small refactoring to the share sidebar. A couple of tweaks I want to merge in as part of the first small wave:
- I move `isValidUserId` out of `state.js` and simplify it.
- I move `canShareToUser` out of `state.js` and rename it to `canShareToUserId`.
- I refactor ordering of permissions using `Set` to skip filtering intermediate collections.
Hope you like it. I'll merge it soon.

Share sidebar tweaks

---

app/src/docs/components/DocsLayout/DocsNav.jsx
app/src/shared/components/Layout/Nav.jsx

Quick one, the `DocsMenu` is the same in Core and the docs menu so why not combine them?

Reuse docs menu in all core nav

---

app/src/marketplace/containers/ProductPage/PurchaseModal.jsx
app/src/shared/web3/web3Provider.js

You might have seen this warning in console:
https://eips.ethereum.org/EIPS/eip-1102
This adds the new call to use `ethereum.request` to make the `eth_requestAccounts` request and prompt Metamask usage. The `request` method exists since Metamask 8 so I left the old method as fallback just in case.

Prefer 'eth_requestAccounts' RPC method instead of etherum.enable()

---

app/src/editor/canvas/index.jsx
app/src/editor/dashboard/index.jsx
app/src/shared/components/Sidebar/SidebarProvider.jsx
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/ShareSidebar/Sidebar.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx

`useBeforeClose` is a wrapper for sidebar's `addTransitionCheck` and `removeTransitionCheck`. Makes it easy to define transition checks.
```js
const Sidebarowsky = () => {
useBeforeClose(() => false) // block closing the sidebar
// …
}
```

Define useSidebar and useBeforeClose

---

app/src/docs/components/DocsLayout/docsLayout.pcss
app/src/docs/components/DocsLayout/index.jsx

Uses `docsMap` to extract underlying file path for editing on GitHub and shows button when the path is available. This means that _Module Reference_ definitions are not currently editable.

[FRONT-125] Add 'Edit on GitHub' button to documentation pages

---

app/src/shared/components/CodeSnippets.jsx
app/src/shared/components/TOCPage/TOCNav.jsx
app/src/shared/components/TOCPage/index.jsx
app/src/userpages/components/StreamPage/New.jsx
app/src/userpages/i18n/en.po

Improvements from [FRONT-177](https://linear.app/streamr/issue/FRONT-177/improve-stream-namespace-create-process):
* Grey out the other side nav menu items (apart from details) until stream has been created
* Have Code Snippets already on the page, but empty and with comment inside the widget “Create your stream above in order to get your code snippet”
* Add some extra intro text “Choose your stream path name & create it in order to adjust stream settings”
* Update the tooltip (remove mention of "sandbox" domain)
**Not** implemented:
* Don’t have the page refresh on creation
Too much hassle atm to rethink the stream loading.

[FRONT-177] Improve stream namespace create process

---

app/src/docs/content/api/authentication.mdx
app/src/docs/content/api/code/api.js
app/src/docs/content/core/introToCore.mdx
app/src/docs/content/gettingStarted/gettingStarted.mdx
app/src/docs/content/sdk/overview.mdx
app/src/docs/content/sdk/python.mdx
app/src/docs/content/streams/code/streams.js
app/src/docs/content/streams/usingStreamsInCore.mdx
app/src/docs/content/streams/usingStreamsViaSdk.mdx
app/src/docs/content/tutorials/buildingPubSub.mdx
app/src/docs/content/tutorials/code/tutorials.js

There were some mentions of API Keys that trip up external devs. 
Also removed the email/pass authentication as that gets phased out soon and replaced any email mentions with Eth address.
Also added that CLI tool can authenticate with Eth and Python library should not be used.

[DEVRL-26] API Key mentions removed from Docs

---

app/cypress/integration/LoginPage.spec.js
app/src/auth/components/AuthPanel/index.jsx
app/src/auth/components/LoginPage/index.jsx
app/src/auth/components/SignupPage/index.jsx
app/src/auth/components/UsernamePasswordLogin/index.jsx
app/test/unit/components/AuthPage/AuthPanel/index.test.jsx

Removes the controls from the sign up page and replace them with a notice:
The email & password login still works for users to be able login and add an eth account before the whole login gets replaced with the wallet-only auth (#1135).

[FRONT-188] Implement signup replacement notice

---

app/src/editor/canvas/components/ModuleSearch.jsx
app/src/editor/shared/components/StreamSelector.jsx
app/src/marketplace/components/ProductPage/StreamListing/index.jsx
app/src/marketplace/components/StreamSelector/index.jsx
app/src/marketplace/containers/EditProductPage/BeneficiaryAddress.jsx
app/src/shared/components/Layout/User.jsx
app/src/shared/components/StreamPreview/index.jsx
app/src/shared/components/Web3ErrorDialog/UnlockWalletDialog/index.jsx
app/src/shared/utils/diagnostics.js
app/src/shared/utils/text.js
app/src/userpages/components/KeyField/index.jsx
app/src/userpages/components/KeyField/keyField.stories.jsx
app/src/userpages/components/ProductsPage/Header/index.jsx
app/src/userpages/components/ProductsPage/Members/index.jsx
app/src/userpages/components/ProfilePage/IdentityHandler/index.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/index.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/integrationKeyList.stories.jsx
app/src/userpages/components/ProfilePage/IntegrationKeyHandler/index.jsx
app/src/userpages/components/ShareSidebar/UserPermissions.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/New.jsx
app/src/userpages/components/StreamPage/shared/useStreamPath.jsx
app/src/userpages/components/StreamPage/shared/useStreamPath.test.jsx
app/src/userpages/components/TransactionPage/List/index.jsx
app/src/userpages/tests/components/ProfilePage/IntegrationKeyHandler/IntegrationKeyList/integrationKeyList.test.jsx
app/test/unit/utils/text.test.js

Replaces the old `truncate` method so that it will replace any instance of an ETH address or transaction hash and truncate it given length. By default, the format is first 5 characters, ellipsis, 5 last characters which applied to all addresses and stream paths. The expection is the transaction hash, which i left at 10 chars per "side".
Let me know if I missed any 👍

[FRONT-107] Improve consistency of truncation of Eth addresses

---

app/src/editor/canvas/components/Camera/index.jsx
app/src/editor/canvas/components/Camera/state.js
app/src/editor/canvas/components/Canvas.jsx
app/src/editor/canvas/components/CanvasWindow.jsx
app/src/editor/canvas/components/DragDropContext.jsx
app/src/editor/canvas/components/DraggableCanvasWindow.jsx
app/src/editor/canvas/components/Module.jsx
app/src/editor/canvas/components/ModuleRenderer/index.jsx
app/src/editor/canvas/state/diff.js
app/src/editor/canvas/tests/diff.test.js
app/src/shared/utils/withErrorBoundary.jsx

Both panning and zooming should be silky smooth now, 99% of the time (it will still jank for some frames whenever the canvas updates).
The fix is changing the spring's `onRest` handler to use the debounced commit, rather than commit immediately. See ef7c27a. Also added some debug names for components & some other minor perf improvements and that I looked at before narrowing down the major actual fix.
Note: There might have been a reason that I've forgotten as to why this was using throttle, not debounce, but I could not figure out how to break it while using debounce. Perhaps something to do with receiving delayed updates while dragging? Possible some hybrid approach is required.
Closes FRONT-176.

[FRONT-176] Fix Pan+Zoom performance for Canvases

---

app/src/routes/index.js
app/src/routes/routes.test.js

This PR addresses the error of defining a variable with a port:
```js
define('<api>/resource', () => ({
api: 'http://localhost:80',
}))
```
This causes an error `Uncaught TypeError: Expected “80” to be a string` when the route is generated.
Fixed by reversing the route generation so that the route params are parsed first and then replacing the external variables.

[FRONT-214] Handle route params before replacing variables

---

app/src/userpages/components/ProfilePage/IdentityHandler/CopyPrivateKeyDialog/index.jsx

> When creating a new Ethereum account via the profile page, the copy private key button at the end of the wizard copies the address with the "0x" prefix. This is not wrong, but the "0x" is usually omitted for private key hex representations to clearly distinguish it from addresses. We could follow this convention.
Fixes private key copying.

[FRONT-228] Copy private key without 0x prefix

---

app/src/marketplace/components/ProductPage/ProductDetails/index.jsx

Now expiration counter shows only for 48 hours after expiration for marketplace products.

[FRONT-86] Smarter expiration counter

---

app/src/marketplace/modules/dataUnion/services.js

This will fix issue when trying to deploy a DU after it failed first somewhere after creating `joinPartStream`.

[FRONT-245] Use existing joinPartStream if possible

---

app/package-lock.json
app/package.json
app/src/marketplace/modules/dataUnion/services.js

Updates Web3 to version `1.3.3`, this fixes the notification in Metamask about using deprecated Web3 API. This was actually a Metamask bug (https://github.com/MetaMask/metamask-extension/issues/10356) which manifested itself by using an older version of web3.
Metamask will include that fix in a future release but this should get rid of the notification by using a newer version which doesn't trigger that notification. All transactions seemed to work normally but please have a look if something is misbehaving.
NOTE: PR based on #1162, use node 12 or 14 to compile

[FRONT-246] Fix deprecated web3 notification in Metamask

---

app/src/marketplace/components/ProductPage/DataUnionPending/index.jsx
app/src/marketplace/components/ProductPage/Terms.jsx
app/src/marketplace/containers/EditProductPage/TermsOfUse.jsx
app/src/shared/components/DeploySpinner/index.jsx
app/src/userpages/components/ProductsPage/Members/index.jsx
app/src/userpages/components/ProductsPage/Members/members.pcss

Fixes Terms & conditions formatting in the product editor and product page:
Also added minor tweaks for DU deployment spinner as it broke the page in smaller displays... in real life it probably won't ever happen.

[FRONT-249] Fix terms & conditions formatting

---

app/src/marketplace/modules/contractProduct/services.js
app/src/marketplace/modules/dataUnion/services.js
app/src/marketplace/modules/product/services.js
app/src/marketplace/utils/smartContract.js
app/src/shared/utils/constants.js

Here are results of testing MetaMask gas limit estimation:
Operation | Hardcoded value | MetaMask estimate
-- | -- | --
Deploy data union | 4 000 000 | 4 242 412
Publish product | 400 000 | 237 276
Unpublish product | 300 000 | 74 178
Update product | 300 000 | 79 182
Update DU admin fee | 400 000 | 43 972
Buy product with DATA | 300 000 | 140 668
Buy product with ETH | 500 000 | 273 357
Buy product with DAI | 600 000 | 7 600 000
Whitelist enable/disable | 100 000 | 61 975
Whitelist add/remove address | 100 000 | 64 251
DU deploy estimate is only a bit higher than our hardcoded value. Buying product with DAI (or other ERC20) estimate is crazy probably due to Uniswap. We should keep our hardcoded value there.
Other values are a good 👍
PS. This was tested on local Parity network but I …

[FRONT-230] Remove hardcoded gas limits

---

app/src/marketplace/components/ActionBar/index.jsx
app/src/marketplace/i18n/en.po

I noticed a bug when "Latest" sort by filter was selected, it didn't keep the label visible.

Fix sort by filter when Latest is selected

---

app/src/shared/utils/text.js
app/src/userpages/components/ShareSidebar/Share.jsx
app/test/unit/utils/text.test.js

~I wanted to use a slightly larger `length` parameter just because we got room for it (see the attached image). `truncate` function didn't let me though. Apparently if you go with an address that's 42-char long (0x+40 chars) it does not let you use larger `length` than 5 (regular expression doesn't match because of the hardcoded `32`; `32 + 5 + (5 - 2)` → `40`).~
~Updated the function so it doesn't work on addresses shorter than 40 but accepts any length larger than 2 and respects the implicit max. length.~
cc @mattatgit

[FRONT-263] Sidebar truncations

---

app/src/marketplace/modules/product/services.js
app/src/shared/utils/constants.js

Gas limits restored for buying products as MP1 contract products causes problems with MetaMask gas limit estimation.

[FRONT-277] Restore gas limit for buying products

---

app/cypress/integration/StreamPage.spec.js
app/cypress/support/commands.js

Fix missing `regeneratorRuntime` and permissions to be handled with Ethereum identities.
PS. Do you have problems getting Cypress tests to run consistently? I seem to get a couple of failing test cases per run with timeouts and It's not the same cases every time. They will pass when retrying the run.

[FRONT-274] Fix Cypress tests

---

app/src/marketplace/modules/contractProduct/services.js

Seems like our current Web3 version does not return `BigNumber`s anymore for `getPastEvents` calls.
This will fix https://sentry.io/organizations/streamr/issues/2221024678/?referrer=slack

[FRONT-291] Fix timestamp handling for Ethereum events

---

.ci_scripts/smoke_test.sh
.github/workflows/docker.yml

Seems Docker build has been failing for a while due to these reasons:
- Wrong script path in github action file
- Having an old Travis var reference in it, fixed to work with Github actions
- `docker-compose.override.yml` was removed in `streamr-docker-dev`
Tried it with PR builds and seemed to work, now restored to happen only for tagged and master builds (https://github.com/streamr-dev/streamr-platform/actions/runs/704869393).

[FRONT-319] Fix docker build / smoke test

---

app/src/marketplace/containers/EditProductPage/DeployDataUnionModal.jsx
app/src/marketplace/containers/EditProductPage/EditControllerProvider.jsx
app/src/marketplace/containers/EditProductPage/tests/EditControllerProvider.test.jsx

Fixes a bug when creating a Data Union, the beneficiary is only actually saved when dialog is closed. If the transaction runs long and user exits the page, DU contract address was not saved as the product's beneficiary address.
**To test**
1. Create DU product, fill fields
2. Click Continue to deploy
3. Accept transaction
4. Before transaction completes, refresh page
Product list should status as "Deployed".

[FRONT-321] Save the new DU address immediately to product

---

app/src/marketplace/containers/Products/index.jsx

Small fix to improve #1209, reload DU stats when returning to Marketplace (eg. by back button) when the whole product list does not need to be fetched.

[FRONT-320] Reload DU stats when returning marketplace

---

app/package-lock.json
app/package.json
app/src/app/index.jsx
app/src/auth/components/LogoutPage.jsx
app/src/marketplace/components/NewProductPage.jsx
app/src/marketplace/containers/ProductPage/Hero.jsx
app/src/shared/contexts/ModalApi/index.jsx
app/src/shared/modules/user/actions.js
app/src/shared/test/modules/user/actions.test.js
app/src/store.js
app/src/userpages/components/CanvasPage/List/index.jsx
app/src/userpages/components/DashboardPage/List/index.jsx
app/src/userpages/components/ProductsPage/Header.jsx
app/src/userpages/components/ProfilePage/DeleteAccount/index.jsx
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/List/Row.jsx
app/src/userpages/components/StreamPage/New.jsx
app/src/userpages/components/StreamPage/View.jsx
app/src/userpages/tests/components/ProfilePage/profilePage.test.jsx

More cleanup, this removes the `connected-react-router` lib. The only redux action where redirects were actually used was the logout action. I moved all redirects to happen at component level. One more dependency gone 🎉

Remove connected-react-router

---

app/src/userpages/components/StreamPage/Edit/ConfigureView/index.jsx
app/src/userpages/flowtype/states/stream-state.js
app/src/userpages/modules/userPageStreams/actions.js
app/src/userpages/modules/userPageStreams/reducer.js
app/src/userpages/modules/userPageStreams/selectors.js
app/src/userpages/modules/userPageStreams/services.js
app/src/userpages/tests/modules/userPagesStreams/reducer.test.js

Removes unsupported API calls for stream field detection and uses the feature from `streamr-client`.

[FRONT-187] Use detectFields from streamr-client

---

app/src/marketplace/containers/ProductPage/MembersGraphV2.jsx
app/src/marketplace/modules/dataUnion/hooks/useDataUnionMembers.jsx
app/src/marketplace/modules/dataUnion/services.js
app/src/shared/utils/ethereum.js

xDai RPC would timeout when fetching smart contract events in one go. This PR will make calls to `getPastEvents` in batches.
I also changed `getSidechainEvents` and `getJoinsAndParts` to be generator functions so that we don't have to wait for all results to be fetched and processed before using them. xDai is so slow that the graph would show a flat line for ages without this change.

[FRONT-377] Fix MemberGraph to work on xDai

---

app/src/docs/content/streams/usingStreamsViaApi.mdx

Replace double quotes by single quotes to avoid the error on command execution: `{"error":"Invalid JSON in stream: {foo:hello,bar:24.5}. Error while parsing was: SyntaxError: Unexpected token f in JSON at position 1"}%`
Wrong: `"{"foo":"hello","bar":24.5}"`
Correct: `'{"foo":"hello","bar":24.5}'`
Webpage: https://streamr.network/docs/api/using-streams-via-api

Fix JSON quotes

---

app/src/userpages/components/ProfilePage/ProfileSettings/index.jsx
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/StreamPage/Edit/ConfigureView/index.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/Inspector.jsx
app/src/userpages/components/StreamPage/List/Row.jsx
app/src/userpages/components/StreamPage/List/index.jsx
app/src/userpages/components/StreamPage/New.jsx
app/src/userpages/components/StreamPage/index.jsx

Add generic error messages in places where before we were directly showing the error from backend. The actual error gets shown in console, but show a generic notification message in the UI.

[FRONT-430] Add generic error messages

---

app/src/docs/components/Warning/warning.pcss
app/src/docs/content/streamrNetwork/usingALightNode.mdx
app/src/docs/content/streams/endToEndEncryption.mdx
app/src/docs/content/streams/publishAndSubscribe.mdx

Just adding a minor reminder to developers about the differences between 5.x client and 6.x client.

Docs: Add warning labels about 5.x and 6.x client differences

---

app/src/marketplace/modules/product/services.js

Remove `dataUnionVersion` parameter when creating a new product, it's not needed anymore as DU 1.0 functionality is removed form backend.

Remove dataUnionVersion parameter

---

app/src/marketplace/containers/EditProductPage/DeployDataUnionModal.jsx

Fixes an issue where when DU deploy fails, resetting the `beneficiaryAddress` didn't call the API to update product. 
There is a separate backend issue where setting the `beneficiaryAddress` to `null` does not save the value ([BACK-197](https://linear.app/streamr/issue/BACK-197/allow-resetting-beneficiaryaddress)) but this will at least make the call now.

[FRONT-710] Revert beneficiaryAddress if DU deploy fails

---

app/src/marketplace/containers/ProductPage/Hero.jsx
app/src/shared/hooks/useWeb3Status.js
app/src/shared/web3/web3Provider.js

Follow up for https://github.com/streamr-dev/core-frontend/pull/1278 (FRONT-723), this makes the timeout for unlocking Metamask prompt optional. For example when logging in, it waits for the Metamask approval. Otherwise, it shows as failed before the user unlocks.

Add opt-in for validateWeb3 timeout

---

app/src/marketplace/containers/EditProductPage/editProductPage.pcss
app/src/marketplace/containers/EditProductPage/index.jsx
app/src/shared/components/Layout/Core.jsx
app/src/shared/components/Layout/core.pcss
app/src/shared/components/Toolbar/Toolbar.stories.jsx
app/src/shared/components/Toolbar/index.jsx
app/src/userpages/components/Layout/index.jsx
app/src/userpages/components/ProfilePage/index.jsx
app/src/userpages/components/ProfilePage/profilePage.pcss
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/New.jsx
app/src/userpages/components/StreamPage/index.jsx

Some pages had a custom style to make the Toolbar loading indicator sticky and some didn't. This combines that functionality into the `Toolbar` components and removes the `loading` prop from `CoreLayout`.

Move loading indicator to Toolbar

---

app/src/marketplace/containers/EditProductPage/usePublish.js
app/src/marketplace/containers/ProductController/useProductLoadCallback.js
app/src/marketplace/modules/contractProduct/services.js
app/src/userpages/modules/transactionHistory/actions.js

Fixes an issue where after switching network, the purchase modal shows an error ([FRONT-769](https://linear.app/streamr/issue/FRONT-769/switching-network-from-purchase-modal-gives-an-error)).
Error happens because the contract product was fetching from the network selected in Metamask, not the public network. I changed it so that contract product is fetched from public chain by default.

[FRONT-769] Switching network from purchase modal gives an error

---

app/src/marketplace/containers/EditProductPage/usePublish.js
app/src/marketplace/containers/ProductController/useLoadAllStreamsCallback.js
app/src/userpages/components/StreamPage/List/index.jsx

Client's `getAllStreams` was actually getting *all* streams regardless of user. Replaced those calls with `searchStreams` that has a `user` filter.

[FRONT-847] Replace getAllStreams with searchStreams

---

app/src/userpages/components/StreamPage/shared/Storage.jsx
app/src/userpages/components/StreamPage/shared/useStreamStorageNodeAddresses.js

`getStorageNodes` is now more down-to-earth and simply returns an array of addresses. I also make any comparisons case insensitive.

FRONT-845: Storage node checkboxes fixed

---

app/src/userpages/components/StreamPage/shared/patchStorageNodeUrlGetter.js
app/src/userpages/components/StreamPage/shared/useStreamStorageNodeToggle.js

Read my comment in [`patchStorageNodeUrlGetter`](app/src/userpages/components/StreamPage/shared/patchStorageNodeUrlGetter.js) for details.
I do it on runtime because patching storage node reg's prototype feels even uglier.

Monkey-patch getting dev storage node URL

---

app/src/shared/components/TOCPage/TOCSection.jsx
app/src/shared/flowtype/stream-types.js
app/src/userpages/components/StreamPage/Edit/MigrateView.jsx
app/src/userpages/components/StreamPage/Edit/index.jsx
app/src/userpages/components/StreamPage/New.jsx
app/src/userpages/components/StreamPage/shared/Icons.jsx

Adds a toggle to mark stream enabled for Brubeck migration.
Still needs a correct **Learn more** link once the blog post is published.

[FRONT-818] Brubeck stream migration

---

app/src/userpages/components/StreamPage/Edit/StatusView.jsx

Smashing it the simplest way possible. `inactivityThresholdHours` is `NaN` by default. Weird but hey.

FRONT-813: Fix falsely unsaved stream edits

---

app/src/analytics.js
app/src/routes/definitions.json
app/src/shared/hooks/useScrollToTop.js
app/src/shared/test/modules/user/services.test.js
app/test/unit/modules/categories/services.test.js
app/test/unit/modules/myProductList/services.test.js
app/test/unit/modules/myPurchaseList/services.test.js
app/test/unit/modules/product/services.test.js
app/test/unit/modules/productList/services.test.js
app/test/unit/modules/relatedProducts/services.test.js
app/travis_scripts/e2e-tests.sh

The bug was… incorrect URL of the logout API endpoint. `v1` (old) vs `v2` (new).
I also took a minut and grepped for all v-ones, and changed them to `v2`.

FRONT-874: Logout fix

---

app/src/shared/components/Ui/Label.jsx
app/src/shared/components/Ui/Label.unstyled.jsx
app/src/shared/test/components/KeyField/KeyField.test.jsx
app/src/shared/test/components/KeyField/KeyFieldEditor/KeyFieldEditor.test.jsx
app/src/userpages/components/StreamPage/shared/FormGroup.jsx

I’m trying something new.
- There's `$ui/Label` which is just the logic of a regular `Label`, and
- there's `$ui/Label.styled` which is a styled version of `Label` with no logic side effects.
Is this something we can try out? I'd like to see how it work on a wider range of components, over time. Best case scenario - we like it. Worst, we merge them back in.
@tumppi, I'm eager to hear your opinion!

Separate styled and unstyled $ui/Label

---

app/src/config/development.toml
app/src/getters/getCoreConfig.ts
app/src/marketplace/containers/EditProductPage/StreamSelector.tsx
app/src/pages/AbstractStreamEditPage/AccessControlSection/PermissionList.tsx
app/src/pages/NewStreamListingPage/index.tsx
app/src/services/streams.ts
app/src/shared/components/StreamSelectTable/index.tsx
app/src/shared/components/StreamTable/index.tsx
app/src/shared/components/Tile/index.tsx
app/src/shared/hooks/useFetchStreamsFromIndexer.ts
app/src/shared/hooks/useStreamStats.ts
app/stories/exampleProjectList.json

Adds a new hook `useFetchStreamsFromIndexer` which uses `stream-metrics-indexer` to load streams with stats included. API is compatible with existing `useFetchStreams` which uses `streamr-client` to fetch data.

[FRONT-1140] Stream stats

---

app/package.json
app/src/app/index.tsx
app/src/shared/components/AbstractToast.tsx
app/src/shared/hooks/usePreventNavigatingAway.ts
app/src/shared/toasts/AbstractToast.tsx
app/src/shared/toasts/Toast.tsx
app/src/utils/Layer.ts

This PR does not come with any uses of the new toasts. Eventually though it'll replace all `Notification.push` hits.
To pop up a simple detached toast you can do
```ts
async function onClick() {
await toaster(Toast, Layer.Toast).pop({
title: 'My toast',
type: ToastType.Success,
})
}
```
Note that dismissing a toast manually or via the `autoCloseAfter` (automatically) throws an exception. Technically it's a promise rejection. That's how it's build. You can build a toastable that resolves on dismiss, no probs. It's failry easy actually!
Good thing about the new toasts? They're highly customizable because… `toasterhea` doesn't come with any toastables ("Bring your own bread, eh!?").
This is how you create a confirmation toast:
```tsx
async function onClick() {
try {
await toaster(Toast, …
```

FRONT-1345: Tastefull toasts

---

app/src/pages/NewStreamListingPage/index.tsx
app/src/pages/StreamPage.tsx
app/src/shared/components/DetailsPageHeader/index.tsx
app/src/shared/components/Globals.tsx
app/src/shared/stores/routeMemory.ts

In this PR I make sure that when you go to "Your streams", open one, and hit "←" (go back) you'll end up seeing the list of your streams, not the list of \*all\* streams. This used to be quite annoying and inconsistent.
@tumppi @pmichalowski here I introduce a new concept: Route memory. Have a look at the `routeMemory.ts` to learn more about it. Naming may seem a bit off, or not. I'm quite happy with it, actually.
LMK if you have any other ideas.
Here are some I considered:
- Local/session storage: without some trickery this would make "Streams" link (top nav) go back to your previous selection. Not ideal.
- More routes: how would the connect page know where to go if I came through Stream list → Overview → Connect?

FRONT-1341: Go back like a Pro

---

app/src/marketplace/containers/ProjectEditing/BeneficiaryAddress.tsx
app/src/pages/AbstractStreamEditPage/InfoSection/StreamId.tsx
app/src/shared/components/CopyButton/CopyButton.tsx
app/src/shared/components/StreamConnect/index.tsx
app/src/shared/components/StreamPreview/Feed.tsx
app/src/shared/components/StreamPreview/Toolbar.tsx
app/src/shared/hooks/useCopy.ts
app/src/shared/toasts/AbstractToast.tsx
app/src/utils/toast.ts

So, first things first, popping up a toast has never been easier. From literally anywhere you can now
```tsx
import { successToast } from '$utils/toast'
successToast({ title: 'I am indeed a toast.' })
```
I've integrated it with the `useCopy` hook, so now, if you wanna copy something using the hook you can
```tsx
function Foo() {
const { copy } = useCopy()
return (
<button
type="button"
onClick={() => void copy('Bar', {
toastMessage: 'I am indeed a toast.',
})}
>
Copy!
</button>
)
}
```

New copy toasts

---

app/src/app/index.tsx
app/src/getters/index.ts
app/src/marketplace/components/PaymentRate/index.tsx
app/src/marketplace/containers/ProjectPage/Hero/ProjectHero2.tsx
app/src/marketplace/containers/ProjectPage/utils.tsx
app/src/marketplace/utils/project-mapper.ts
app/src/pages/ProjectPage/AccessManifest.tsx
app/src/pages/ProjectPage/GetAccess.tsx
app/src/pages/ProjectPage/TabbedPage.tsx
app/src/pages/ProjectPage/index.tsx
app/src/routes/definitions.json
app/src/services/projects.ts
app/src/shared/components/Layout/index.tsx
app/src/shared/components/Layout/layout.pcss
app/src/shared/components/Tile/index.tsx
app/src/shared/stores/projectAbilities.ts
app/src/shared/stores/projectEditor.tsx
app/src/shared/stores/purchases.ts
app/src/shared/types/index.ts

In this PR I make it possible to switch between Project overview, Connect, and the Live data pages without remounting pretty much the entire page.
It sure is more than just the tabs though. I prep for some project create/edit flow restructuring to make it more robust.
The pages I touch here use a different loading mechanism (less `Context`, more `zustand`).
Cheers!

FRONT-1361: Smooth project page tabs

---

app/src/marketplace/containers/ProjectEditing/EditProjectPage.tsx
app/src/marketplace/containers/ProjectEditing/ProjectEditor.tsx

When the current user does not have edit permissions, he will be redirected to the project overview. When a user does not have delete permissions, he will not see the delete button

[FRONT-1401] & [FRONT-1366] Checking for permissions in project editing 

---

app/src/marketplace/containers/ProjectEditing/DeleteProject.tsx
app/src/services/projects.ts

Fix project CRUD transactions to not fail when transaction is mined slowly as it is expected if user chooses low gasPrice or network is otherwise congested. Now the toast will represent actual state of the transaction.
Before this change transactions could fail if they were not confirmed within 50 blocks.
PS. Also added missing redirect after project delete.

[FRONT-1351] Fix project transactions

---

app/webpack.config.js

You can now have `CONFIG_ENV` set to `production` locally and see all the products and streams known to the Polygon Netzwerk.
Leave the var blank everywhere else (staging, production, …).
@pmichalowski @tumppi I'll get that in but won't deploy. I think it makes life so much easier. Let's take it back if we decide to!
Cheers!

Add `CONFIG_ENV` for better DX against production streams and projects

---

app/src/marketplace/containers/ProjectEditing/EditProjectPage.tsx
app/src/marketplace/containers/ProjectEditing/NewProjectPage.tsx
app/src/shared/components/Globals.tsx
app/src/shared/hooks/usePreventNavigatingAway.ts

**Reason?**
`history.block` can only be called once at a time. This makes the previous `usePreventNavigatingAway` limited to a single block per route. We have 2, in most cases (stream page and the one in `Globals`).
**So(u)lution**
I set up a blocker registry and make `history.block` go through it and use the first eligible blocker. If it doesn't find any, it idles.
It does require us to keep an eye out on how we use `usePreventNavigatingAway` hook. `isDirty` better not be different on each rerender (i.e. use `useCallback`, or `useRef`).

FRONT-1409: Better navigation blocker

---

.github/workflows/ci.yml
app/src/app/index.tsx
app/src/modals/BaseModal.tsx
app/src/modals/FormModal.tsx
app/src/pages/AbstractStreamEditPage/InfoSection/StreamId.tsx
app/src/shared/components/Ui/Label.tsx
app/src/shared/utils/chains.tsx
src/components/Help.tsx
src/modals/BecomeOperatorModal.tsx
src/modals/CreateSponsorshipModal.tsx
src/modals/DelegateFundsModal.tsx
src/modals/FundSponsorshipModal.tsx
src/modals/JoinSponsorshipModal.tsx
src/pages/OperatorsPage/index.tsx

This PR implements the following dialogs:
- Create Sponsorship
- Fund Sponsorship
- Delegate (to Operator)
- Become an Operator
- Join Sponsorship as Operator
There's also a dummy new page for Operators – `/hub/operators` – from where you can open up each of them modals.
This here is only about the visuals. I left a designated space for async logic in each of the dialogs. Additionally, each modal can take initial values for each of their input fields and resolves properly on submittion.
Cheers!
---

FRONT-1472, FRONT-1474, FRONT-1475, FRONT-1479: Modal dialogs for Sponsorships and Operators

---

app/src/shared/components/StreamConnect/index.tsx

2 things were broken:
- Light node code was never correct (we used to pass current broker code snippet to `copy`),
- Broker code snippet tabs were hardcoded to preselect `websocket` tab. It lead to "sometimes" copying the wrong value (display issue).
I also make the snippets more readable to the code people. Eyes used to hurt by looking at the old formatting. I do it with a small sacrifice of performing a couple of string replacements.

FRONT-1492: Fix copying code snippets

---

app/src/pages/AbstractStreamEditPage/AccessControlSection/index.tsx

We let people with GRANT permission edit access options. It no longer incorrectly relies on the EDIT permission.

FRONT-1498: Respect GRANT permission in the stream editor

---

app/src/shared/stores/streamEditor.tsx

I.e. not on the page it links to.

FRONT-1491: Show Open link when it's really needed

---

src/modals/NewStreamPermissionsModal.tsx
src/services/projects.ts
src/shared/stores/streamEditor.tsx
src/utils/index.tsx
src/utils/toastedOperation.ts

Few things about this PR
- Includes a bunch of new comments on the process.
- Adds `refresh` (next to `next` callback) callback to `toastedOperations` so that you can refresh the states on demand.
- `isMessaged` is gone. It was a dupped `isMessagedObject`.
This and a couple more I won't mention here (see the self-review for more).

Use `toastedOperations` for stream persisting

---

src/hooks/useOperatorLiveNodes.ts

Previously, the same node id could be counted multiple times because of race conditions between checking `liveNodes.includes(address)` and updating `liveNodes`. Fix this by turning `liveNodes` into an object instead of an array, in which case the updates become idempotent.
Please feel free to take over this PR if you prefer a different approach!

FRONT-1565 idempotent live nodes

---

src/components/OperatorChecklist.tsx
src/shared/stores/operatorReachability.ts

Give `useOperatorReachability` a collection of heartbeats to learn the condition of your fleet. It also caches per-URL probe for a minute, comes with timeout support, etc. It's pretty neat.

FRONT-1592: Operator nodes reachability

---

src/components/Nav/index.tsx

I actually remove it completely. Once we need it again let's just bring it back from the dead, eh?

FRONT-1606: Hide "Network Explorer" link from the navigation

---

src/components/NetworkUtils.tsx
src/components/QueriedSponsorshipsTable.tsx
src/components/Table.tsx
src/pages/NetworkOverviewPage.tsx
src/pages/OperatorsPage.tsx
src/pages/SingleOperatorPage.tsx
src/pages/SingleSponsorshipPage.tsx

In short,
- I add "Funded until" to all Sponsorship tables,
- I fix and unify all Operator Id cells (avatar + name), and
- I unify all Stream id cells for Sponsorships – they all, asynchronously fetch stream descriptions now, too!
Addresses the following tickets
- FRONT-1614
- FRONT-1611
- FRONT-1610

FRONT-1614: Add missing / fix invalid table columns

---

src/services/sponsorships.ts

There's one policy missing from sponsorships. Without it flagging and voting don't work.

Urgent: add SponsorshipVoteKickPolicy

---

src/components/ActionBars/OperatorActionBar.tsx

If delegation amount for the current wallet is 0 then we keep it disabled.

FRONT-1599: Only enable "Undelegate" button when the user have delegated funds to the Operator

---

src/components/Nav/index.tsx

Click on Network accordion items should dismiss the whole nav overlay. Here's the fix.

FRONT-1624: Fix Network accordion item clicks

---

src/components/Nav/index.tsx

Well, first of all, the items are all anchors nested within buttons… Yeah.
In this PR I don't fight the library (`reactstrap@whateverversionitis`). After a short tryout I picked the 0-effort solution and let buttons be buttons.
Reminder: we want to drop `reactstrap`, `sass`, and that whole club.

FRONT-1625: Items in the Network dropdown main nav are not all clickable

---

src/components/ActionBars/AboutEntity.tsx
src/components/ActionBars/AboutOperator.tsx
src/components/ActionBars/AboutSponsorship.tsx
src/components/ActionBars/OperatorActionBar.tsx
src/components/ActionBars/SponsorshipActionBar.tsx

It's mostly about making "About Sponsorship" and "About Operator" boxes look alike. Plus, there's the stream link.
Previous
New
And for reference, About Operator box

FRONT-1630: Link to the stream on sponsorship page

---

src/components/ActionBars/AboutEntity.tsx
src/components/ActionBars/AboutSponsorship.tsx
src/components/ActionBars/SponsorshipActionBar.tsx
src/components/QueriedSponsorshipsTable.tsx
src/components/Table.tsx
src/parsers/OperatorParser.ts
src/parsers/SponsorshipParser.ts

Notes
- I make parsers for sponsorships and operators support no-stream edge case and display improvised UIs in all places I could think of.
- I disable UIs for joining orphanized sponsorships as an operator, and for sponsoring it. Users can still edit their stake.

FRONT-1635: Sponsorships of deleted streams

---

src/services/sponsorships.ts

I've got a hunch that `getSponsorshipsAndEarnings` can give us addresses with NaNish earnings = a nasty no no.
In this PR squish invalid BNs to 0 and warn about the situation. The warning will help us investigate it further w/o NaNs in them nice UIs.
Cheers!

FRONT-1636: Prevent `NaN` uncollected earnings

---

src/components/OperatorChecklist.tsx
src/hooks/useInterceptHeartbeats.ts
src/shared/stores/operatorReachability.ts

The reachability check is back. It does not actually probe declared websocket connectivity information. It just checks if it's defined. Later on we'll bring back the real check.

FRONT-1638: Bring back the nodes reachable check (light version)

---

src/components/Nav/index.tsx
src/components/NetworkUtils.tsx
src/components/NoWalletOverlay.tsx
src/modals/ChainSelectorModal.tsx
src/modals/ConnectModal.tsx
src/pages/SingleOperatorPage.tsx
src/shared/stores/wallet.ts
src/shared/test/components/Nav/nav.test.tsx
src/utils/errors.ts

Few extras:
- `ConnectModal` is now represented by a single toaster instance. 1 is enough.
- `getSigner` will always verify if the wallet is unlocked and pop up the "Connect wallet" modal if it isn't.

FRONT-1657: Collect earnings fails when the wallet is not connected

---

src/modals/CreateSponsorshipModal.tsx
src/modals/DelegateFundsModal.tsx
src/modals/EditStakeModal.tsx
src/modals/FundSponsorshipModal.tsx
src/modals/JoinSponsorshipModal.tsx
src/modals/UndelegateFundsModal.tsx

Found a couple of places where step was not specified and thus defaulting to `1`. Now we allow entering decimal values for token amounts.

[FRONT-1675] Allow decimal values for token amounts

---

src/modals/FundSponsorshipModal.tsx

The new end date extends the current end date, and not *today's* date.

FRONt-1683: Fix the "new end date" calculation in the "Fund sponsorship" modal

---

src/components/ActionBars/OperatorActionBar.tsx
src/hooks/operators.ts
src/modals/DelegateFundsModal.tsx
src/modals/FundSponsorshipModal.tsx
src/pages/SingleOperatorPage.tsx
src/services/operators.ts

This one is simple because the associated modals have already been refactored and simplified.

Wait for block after funds delegation

---

src/getters/index.ts
src/hooks/sponsorships.ts
src/modals/CreateSponsorshipModal.tsx
src/pages/SponsorshipsPage.tsx
src/services/sponsorships.ts

In this PR
- I make the app wait for the sponsorship to be indexed by the Graph,
- Take the user to the page of the newly created sponsorship, and
- Address the FRONT-1685 issue where users could not open sponsorship pages using ids that contain capital letters.
Builds up onto #1710.

Refactor sponsorship creation

---

src/generated/gql/network.ts
src/getters/index.ts
src/hooks/operators.ts
src/queries/network.ts

With this, additionally,
- Users can search operators by sponsorship id as well as
- Search sponsorships by operator id.
Similar information is shown on individual sponsorship/operator pages but being able to search from the listing page allows users to sort and scout for interesting things from a single spot.
As an extra, I removed redundant query (search operators by id) because I wrap the following interactions into a single (existing) query:
- searching by metadata,
- searching by a operator id, and
- searching by a sponsorship id.
Onwards!

Make operators by searchable by sponsorships and vice versa

---

src/components/Nav/Nav.styles.tsx
src/components/Nav/index.tsx
src/hooks/index.tsx
src/hooks/useInterceptHeartbeats.ts
src/shared/test/components/Nav/nav.test.tsx

I add "My Operator" and "Become an Operator" menu items to the profile menu on narrow-screened toys like mobile phones.
I also make a very superficial pass on the styling. Mobile breakpoints needs true love though!
---
In this PR our own quick `useMediaQuery` hook is born. 😉

FRONT-1720: Add operator CTAs to account menu

---

src/components/Table.tsx

I give the icons fixed widths so that they don't shrink.

FRONT-1754: Keep expiration date icons visible on narrow screens

---

src/components/Abbr.tsx
src/components/Anchor.tsx
src/components/Tooltip.tsx
src/modals/CreateSponsorshipModal.tsx
src/modals/DelegateFundsModal.tsx
src/modals/EditStakeModal.tsx
src/modals/FormModal.tsx
src/modals/FundSponsorshipModal.tsx
src/modals/JoinSponsorshipModal.tsx
src/modals/OperatorModal.tsx
src/modals/UndelegateFundsModal.tsx
src/shared/components/Ui/Label.tsx

In this PR I address a couple of problems:
- fields with high min-width that push the appendix outside of the field wrap (the white area),
- labels that don't wrap when the space is tight,
- long big numbers that don't wrap or get truncated,
- wallet addresses that don't wrap or get truncated.

FRONT-1756: Responsive operator/sponsorship modals

---

src/components/Abbr.tsx
src/modals/DelegateFundsModal.tsx
src/modals/EditStakeModal.tsx
src/modals/FormModal.tsx
src/modals/FundSponsorshipModal.tsx
src/modals/JoinSponsorshipModal.tsx
src/modals/UndelegateFundsModal.tsx
stories/Spinner.stories.tsx

Here I add a "convenience" button that populates the amount with the available wallet or operator balance. I do it for amount fields in the following modal dialog boxes:
- Delegate funds to O
- Undelegate funds from O
- Join S as O
- Edit stake
- Sponsor S
Onwards!

FRONT-1744: Add "MAX" buttons to selected amount fields

---

.github/workflows/ci.yml

I had to implement this fix differently. The Brubeck specific broker images are now suffixed with `-brubeck`.

fix ci (v2): use brubeck docker images

---

src/components/ProjectProperty.tsx
src/hooks/streams.tsx
src/pages/ProjectPage/DataUnionFee.tsx
src/pages/ProjectPage/DataUnionPayment.tsx
src/pages/ProjectPage/EditorHero.tsx
src/pages/ProjectPage/EditorNav.tsx
src/pages/ProjectPage/EditorStreams.tsx
src/pages/ProjectPage/ProjectEditorPage.tsx
src/pages/ProjectPage/TermsOfUse.tsx
src/pages/ProjectPage/index.tsx
src/pages/SingleOperatorPage.tsx
src/shared/stores/projectAbilities.ts
src/stores/projectDraft.tsx

In this PR I switch from re-exporting individual draft-related hooks (w/ custom names) to exporting \*just\* the `ProjectDraft` object. It's the same technique we've used on Streams (and `StreamDraft`). Example:
- `useProjectDraft` → `ProjectDraft.useDraft`,
- `useProject` → `ProjectDraft.useEntity`, etc.
The aim is to make things more readable and to know where things belong without digging too deeply.

Simplifications and tweaks

---

src/app.tsx

I give modals and toasts layers 11 and 12 respectively. This makes them appear on top of anything else at all times.

FRONT-1765: Bring modals and toasts to front

---

src/pages/AbstractStreamEditPage/HistorySection/StorageNodeList.tsx

In this PR I make sure we correctly display the fact that a stream comes with storage.

FRONT-1839: Fix storage node state display

---

src/app.tsx
src/pages/ProjectPage/index.tsx
src/pages/StreamPage/index.tsx
src/stores/projectDraft.tsx
src/stores/streamDraft.tsx
src/utils/draft.test.tsx
src/utils/draft.ts

This PR addresses an issue where during a multi-step stream creation (metadata + permisisons and/or storage) the changes done to permissions or storage (anything beyond metadata info) would \*seem\* lost after relocating from `/streams/new` to `/streams/:id`.
Additionally I eliminate the need to re-fetch newly created streams (and the weird blank page loading screen that accompanies the fetching). Better UX!
---

FRONT-1850: Fix stream creation flow

---

package-lock.json
package.json
src/config/chains.toml
src/getters/getChainConfigExtension.ts
src/getters/getClientConfig.ts
src/getters/getGraphClient.ts

In this PR I eliminate confusion on the graph URL piece (we call it `networkSubgraphUrl`).
We used to have a "fallback" URL within Hub. Now it's the custom, and if it's defined that's what we use. And we use the one coming from the config package (called `theGraphUrl`) otherwise.
If none is specified I make the code explode. Using some default endpoint does not help!

Network subgraph URL tweaks (and SDK update → v5.3.6)

---

src/marketplace/containers/ProjectPage/Hero/ProjectHero2.tsx

The editor, even annotated with the `readOnly` attribute does spam the console with a nasty deprecation warning. We don't want that.
I use a static markdown formatter (`react-markdown`) on the overview page (like it should be) and eliminate the warning.
In the future we have to deal with the editor deprecation. Baby steps for now, though.

FRONT-1793: Resolve deprecation warnings on the Project overview pages

---

src/components/Stats.tsx
src/components/StreamSummary.tsx
src/consts/index.tsx
src/pages/StreamPage/index.tsx
webpack.config.js

In this PR I wrap data coming from _StreamGPT_ and display it nicely on stream pages.
This PR is the final step. Other components (StreamGPT and the [modded Network Explorer](https://github.com/streamr-dev/network-explorer/pull/325)) are already in place, deployed and ready.
Note that streams that have very little traffic usually won't show the new Summary section. It's normal.
Future improvements
- Edit feature for each field.

FRONT-1854: AI-driven summary section for the stream page

---

src/hooks/streams.tsx

The indexer doesn't allow us to list streams by permissions. Instead I use stream ids from the graph (which does) to accurately ask the indexer for "my" collection of streams.
Hacky.

FRONT-1818: Fix "Your streams" list

---

src/components/QueriedStreamsTable.tsx
src/hooks/streams.tsx
src/pages/ProjectPage/EditorStreams.tsx
src/pages/ProjectPage/index.tsx
src/pages/StreamsPage.tsx
src/services/streams.ts

The aim here is to be smarter about what gets loaded and who triggers the loading. In short,
- `QueriedStreamsTable` no longer takes `onBatch` and `statsQuery` – I've eliminated the dependency between the stats query and the streams query.
- `QueriedStreamsTable` component loads stats on its own, per page, and only when auxiliary stats are needed (they aren't if streams come from the indexer).
- I've done some dead/repeated code shake-off.
Onwards!

Optimize stream list queries

---

src/components/DropdownMenuItem.tsx

The new approach is to make the dropdown content to never go beyond the available space and nicely trim it if it would.

FRONT-1763: Prevent extra long stream names from pushing the "return" icon away

---

package-lock.json
package.json

Previous route utility used this package but it's no longer the case.

Remove `path-to-regexp`

---

src/utils/networkPreflight.ts

`blockExplorerUrls` has to be an array of strings.

FRONT-1925: Fix auto-adding networks in the preflight

---

src/hooks/operators.tsx
src/pages/OperatorPage/SponsorshipTable.tsx
src/pages/OperatorPage/index.tsx
src/services/sponsorships.ts

I added a new `Collect all` button to sponsorship listing footer on operator page.
PS. While on it, I also extracted sponsorship table on operator page into a new component `SponsorshipTable` to keep things separated.

[FRONT-1933] Add collect all button

---

src/components/ActionBars/NetworkActionBar.tsx
src/hooks/useUrlParams.ts
src/pages/OperatorsPage.tsx
src/pages/SponsorshipsPage.tsx
src/shared/stores/wallet.ts

We now keep search parameter and selected tab in the URL for both operator listing and sponsorship listing pages. For sponsorships we also keep current filters in the URL parameters.

[FRONT-1679] Keep view parameters in URL

---

src/components/Stats.tsx
src/getters/getStreamStats.ts
src/hooks/useStreamStats.tsx
src/shared/components/Tile/Badge.tsx
src/shared/components/Tile/index.tsx

Stream count and messages per second are now shown on project tile.
Still waiting for mobile designs so let's not merge yet.

[FRONT-1544] Add stream stats badge to project listing tiles

---

package-lock.json
package.json
src/components/ChainSelector.tsx
src/consts.tsx
src/getters/getClientConfig.ts
src/getters/getEnvironmentConfig.ts
src/pages/ProjectPage/ProjectEditorPage.tsx
src/parsers/ProjectParser.ts
src/types/index.ts
src/utils/chains.ts
src/utils/contracts.ts
src/utils/routes.ts

In this PR I make sure we're using the latest `@streamr/config` package (exposes proper types for the config and chains). I also clean things up a bit. There's room for more but I don't wanna pollute it just yet (#1965 could be addressed first).
- The new config package exposes `ChainKey` (`polygon`, `dev0`, …) which could be use to narrow hub's types even further.

FRONT-1978: Update `@streamr/config` to the "typed" version (v5.5.0) + clean up

---

src/components/ChainSelector.tsx
src/config/chains.toml
src/config/environments.toml
src/utils/chainConfigExtension.ts
src/utils/chains.ts
src/utils/routes.ts

In this PR I eliminate the special case where we'd use `amoy` as a chain key (fake) for what should've been `polygonAmoy` (the actual chain key for Polygon Amoy testnet).
I do so in the following way:
1. Add `slug` to config extension (to `polygonAmoy`'s config) – see `chains.yml`.
2. Use the slug in `getChainKey` to map it to the actual chain key, and in `routeOptions` for proper search query output.
This way any chain (new or existing) can have a short preferred identifier to be used in urls. All for the sake of making adding new chains easier.
In addition, the `getPreferredChainName` got renamed to `getChainKey` and refactored. It now always returns a `ChainKey`. It defaults to `defaultChainKey` if it fails to identify the candidate, and warns about such situation via `console.warn`.

Add chain "slug"; use proper chain key for Polygon Amoy (in local configs)

---

src/components/ChainSelector.tsx
src/components/SalePointSelector/SalePointOption.tsx
src/config/chains.toml
src/modals/AccessPeriodModal.tsx
src/modals/ChainSelectorModal.tsx
src/modals/SwitchNetworkModal.tsx
src/pages/ProjectPage/AccessManifest.tsx
src/pages/ProjectPage/GetAccess.tsx
src/pages/ProjectPage/ProjectEditorPage.tsx
src/parsers/ProjectParser.ts
src/shared/utils/constants.ts
src/shared/utils/tokenAssets.ts
src/types/projects.ts
src/utils/chainConfigExtension.ts
src/utils/chains.test.ts
src/utils/chains.ts
src/utils/index.tsx
src/utils/networkPreflight.ts

We now have the `getChainDisplayName` that uses local chain config extensions (see `chains.yml`) for any local per-chain human readable name customisation.
We used to have `formatChainName`, `chain.name` (modded in `chains.ts`), and the `ethereumNetworks` id-to-name map. Now it's all packed nicely into the new utility function.
This should help us a bunch.
I've also identified that we've been using human readable names to key sale points in the "project" part of the hub. Not ideal, to say the least. Switched it up to the chain key.

Chain's display name done right

---

src/modals/JoinSponsorshipModal.tsx
src/shared/utils/nodeVersion.test.ts
src/shared/utils/nodeVersion.ts

We now require all operator nodes to be version 102.0.0 or greater.

[FRONT-1977] Node version check when joining sponsorship

---

.github/workflows/ci.yml
src/modals/NewStreamPermissionsModal.tsx
src/pages/AbstractStreamEditPage/AccessControlSection/Checkbox.tsx
src/pages/AbstractStreamEditPage/AccessControlSection/PermissionEditor.tsx
src/pages/AbstractStreamEditPage/AccessControlSection/PermissionItem.tsx
src/pages/AbstractStreamEditPage/AccessControlSection/PermissionList.tsx
src/pages/AbstractStreamEditPage/AccessControlSection/StreamTypeSelector.tsx
src/pages/AbstractStreamEditPage/AccessControlSection/index.tsx
src/pages/AbstractStreamEditPage/InfoSection/index.tsx
src/shared/utils/text.test.ts
src/shared/utils/text.ts

- `NewStreamPermissionsModal` changes:
- Allows the user to input any hex string instead of Ethereum address
- However Grant, Edit, and Delete permission can only be given to Ethereum addresses
- Some permissions must be checked for the submit button to be enabled
- Copy changes on stream page to replace 'account' terminology with 'keys' or 'Public Key' terminology depending on context.
- Fix overflow issue in case of long public keys (*screenshots below)
- Unrelated fix: CI was broken due to trying to start no-longer-existing `nginx` service
(*) Before:
After:

feat: [FRONT-2099] support arbitrary hex strings for granting pubsub permissions on Hub
